/*
 * activesession_get_current_v1_response_m_payload.h
 *
 * Payload for GET /1/object/activesession/getCurrent
 */

#ifndef _activesession_get_current_v1_response_m_payload_H_
#define _activesession_get_current_v1_response_m_payload_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct activesession_get_current_v1_response_m_payload_t activesession_get_current_v1_response_m_payload_t;

#include "activesession_response_compound.h"
#include "activesession_response_compound_apikey.h"
#include "activesession_response_compound_user.h"
#include "field_e_activesession_ezsign.h"
#include "field_e_activesession_ezsignaccess.h"
#include "field_e_activesession_ezsignprepaid.h"
#include "field_e_activesession_origin.h"
#include "field_e_activesession_realestateinprogress.h"
#include "field_e_activesession_usertype.h"
#include "field_e_activesession_weekdaystart.h"
#include "field_e_systemconfiguration_ezsignofficeplan.h"
#include "field_e_user_ezsignaccess.h"
#include "field_e_user_ezsignprepaid.h"

// Enum  for activesession_get_current_v1_response_m_payload

typedef enum  { ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__NULL = 0, ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__AgentBroker, ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__Assistant, ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__EzsignSigner, ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__EzsignUser, ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__Normal } ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__e;

char* activesession_get_current_v1_response_m_payload_e_activesession_usertype_ToString(ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__e e_activesession_usertype);

ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__e activesession_get_current_v1_response_m_payload_e_activesession_usertype_FromString(char* e_activesession_usertype);

// Enum  for activesession_get_current_v1_response_m_payload

typedef enum  { ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__NULL = 0, ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__BuiltIn, ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__External } ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__e;

char* activesession_get_current_v1_response_m_payload_e_activesession_origin_ToString(ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__e e_activesession_origin);

ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__e activesession_get_current_v1_response_m_payload_e_activesession_origin_FromString(char* e_activesession_origin);

// Enum  for activesession_get_current_v1_response_m_payload

typedef enum  { ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__NULL = 0, ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__Sunday, ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__Monday, ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__Tuesday, ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__Wednesday, ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__Thursday, ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__Friday, ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__Saturday } ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__e;

char* activesession_get_current_v1_response_m_payload_e_activesession_weekdaystart_ToString(ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__e e_activesession_weekdaystart);

ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__e activesession_get_current_v1_response_m_payload_e_activesession_weekdaystart_FromString(char* e_activesession_weekdaystart);

// Enum  for activesession_get_current_v1_response_m_payload

typedef enum  { ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__NULL = 0, ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__No, ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__Read, ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__Modify, ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__Full } ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__e;

char* activesession_get_current_v1_response_m_payload_e_activesession_ezsign_ToString(ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__e e_activesession_ezsign);

ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__e activesession_get_current_v1_response_m_payload_e_activesession_ezsign_FromString(char* e_activesession_ezsign);

// Enum  for activesession_get_current_v1_response_m_payload

typedef enum  { ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__NULL = 0, ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__No, ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__PaidByOffice, ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__PerDocument, ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__Prepaid } ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__e;

char* activesession_get_current_v1_response_m_payload_e_activesession_ezsignaccess_ToString(ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__e e_activesession_ezsignaccess);

ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__e activesession_get_current_v1_response_m_payload_e_activesession_ezsignaccess_FromString(char* e_activesession_ezsignaccess);

// Enum  for activesession_get_current_v1_response_m_payload

typedef enum  { ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__NULL = 0, ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__No, ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__Basic, ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__Standard, ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__Pro } ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__e;

char* activesession_get_current_v1_response_m_payload_e_activesession_ezsignprepaid_ToString(ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__e e_activesession_ezsignprepaid);

ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__e activesession_get_current_v1_response_m_payload_e_activesession_ezsignprepaid_FromString(char* e_activesession_ezsignprepaid);

// Enum  for activesession_get_current_v1_response_m_payload

typedef enum  { ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__NULL = 0, ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__No, ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__Read, ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__Modify, ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__Create } ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__e;

char* activesession_get_current_v1_response_m_payload_e_activesession_realestateinprogress_ToString(ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__e e_activesession_realestateinprogress);

ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__e activesession_get_current_v1_response_m_payload_e_activesession_realestateinprogress_FromString(char* e_activesession_realestateinprogress);

// Enum  for activesession_get_current_v1_response_m_payload

typedef enum  { ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__NULL = 0, ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__Standard, ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__Pro } ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__e;

char* activesession_get_current_v1_response_m_payload_e_systemconfiguration_ezsignofficeplan_ToString(ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__e e_systemconfiguration_ezsignofficeplan);

ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__e activesession_get_current_v1_response_m_payload_e_systemconfiguration_ezsignofficeplan_FromString(char* e_systemconfiguration_ezsignofficeplan);

// Enum  for activesession_get_current_v1_response_m_payload

typedef enum  { ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__NULL = 0, ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__No, ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__PaidByOffice, ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__PerDocument, ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__Prepaid } ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__e;

char* activesession_get_current_v1_response_m_payload_e_user_ezsignaccess_ToString(ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__e e_user_ezsignaccess);

ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__e activesession_get_current_v1_response_m_payload_e_user_ezsignaccess_FromString(char* e_user_ezsignaccess);

// Enum  for activesession_get_current_v1_response_m_payload

typedef enum  { ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__NULL = 0, ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__No, ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__Basic, ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__Standard, ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__Pro } ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__e;

char* activesession_get_current_v1_response_m_payload_e_user_ezsignprepaid_ToString(ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__e e_user_ezsignprepaid);

ezmax_api_definition__full_activesession_get_current_v1_response_m_payload__e activesession_get_current_v1_response_m_payload_e_user_ezsignprepaid_FromString(char* e_user_ezsignprepaid);



typedef struct activesession_get_current_v1_response_m_payload_t {
    field_e_activesession_usertype_t *e_activesession_usertype; // custom
    field_e_activesession_origin_t *e_activesession_origin; // custom
    field_e_activesession_weekdaystart_t *e_activesession_weekdaystart; // custom
    int fki_language_id; //numeric
    char *s_company_name_x; // string
    char *s_department_name_x; // string
    int b_activesession_debug; //boolean
    int b_activesession_issuperadmin; //boolean
    int b_activesession_attachment; //boolean
    int b_activesession_canafe; //boolean
    int b_activesession_financial; //boolean
    int b_activesession_realestatecompleted; //boolean
    field_e_activesession_ezsign_t *e_activesession_ezsign; // custom
    field_e_activesession_ezsignaccess_t *e_activesession_ezsignaccess; // custom
    field_e_activesession_ezsignprepaid_t *e_activesession_ezsignprepaid; // custom
    field_e_activesession_realestateinprogress_t *e_activesession_realestateinprogress; // custom
    char *pks_customer_code; // string
    int fki_systemconfigurationtype_id; //numeric
    int fki_signature_id; //numeric
    int fki_ezsignuser_id; //numeric
    int b_systemconfiguration_ezsignpaidbyoffice; //boolean
    field_e_systemconfiguration_ezsignofficeplan_t *e_systemconfiguration_ezsignofficeplan; // custom
    field_e_user_ezsignaccess_t *e_user_ezsignaccess; // custom
    field_e_user_ezsignprepaid_t *e_user_ezsignprepaid; // custom
    int b_user_ezsigntrial; //boolean
    char *dt_user_ezsignprepaidexpiration; // string
    list_t *a_pki_permission_id; //primitive container
    struct activesession_response_compound_user_t *obj_user_real; //model
    struct activesession_response_compound_user_t *obj_user_cloned; //model
    struct activesession_response_compound_apikey_t *obj_apikey; //model
    list_t *a_e_module_internalname; //primitive container

} activesession_get_current_v1_response_m_payload_t;

activesession_get_current_v1_response_m_payload_t *activesession_get_current_v1_response_m_payload_create(
    field_e_activesession_usertype_t *e_activesession_usertype,
    field_e_activesession_origin_t *e_activesession_origin,
    field_e_activesession_weekdaystart_t *e_activesession_weekdaystart,
    int fki_language_id,
    char *s_company_name_x,
    char *s_department_name_x,
    int b_activesession_debug,
    int b_activesession_issuperadmin,
    int b_activesession_attachment,
    int b_activesession_canafe,
    int b_activesession_financial,
    int b_activesession_realestatecompleted,
    field_e_activesession_ezsign_t *e_activesession_ezsign,
    field_e_activesession_ezsignaccess_t *e_activesession_ezsignaccess,
    field_e_activesession_ezsignprepaid_t *e_activesession_ezsignprepaid,
    field_e_activesession_realestateinprogress_t *e_activesession_realestateinprogress,
    char *pks_customer_code,
    int fki_systemconfigurationtype_id,
    int fki_signature_id,
    int fki_ezsignuser_id,
    int b_systemconfiguration_ezsignpaidbyoffice,
    field_e_systemconfiguration_ezsignofficeplan_t *e_systemconfiguration_ezsignofficeplan,
    field_e_user_ezsignaccess_t *e_user_ezsignaccess,
    field_e_user_ezsignprepaid_t *e_user_ezsignprepaid,
    int b_user_ezsigntrial,
    char *dt_user_ezsignprepaidexpiration,
    list_t *a_pki_permission_id,
    activesession_response_compound_user_t *obj_user_real,
    activesession_response_compound_user_t *obj_user_cloned,
    activesession_response_compound_apikey_t *obj_apikey,
    list_t *a_e_module_internalname
);

void activesession_get_current_v1_response_m_payload_free(activesession_get_current_v1_response_m_payload_t *activesession_get_current_v1_response_m_payload);

activesession_get_current_v1_response_m_payload_t *activesession_get_current_v1_response_m_payload_parseFromJSON(cJSON *activesession_get_current_v1_response_m_payloadJSON);

cJSON *activesession_get_current_v1_response_m_payload_convertToJSON(activesession_get_current_v1_response_m_payload_t *activesession_get_current_v1_response_m_payload);

#endif /* _activesession_get_current_v1_response_m_payload_H_ */

