/*
 * attachmentlog_response_compound.h
 *
 * A Attachmentlog Object
 */

#ifndef _attachmentlog_response_compound_H_
#define _attachmentlog_response_compound_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct attachmentlog_response_compound_t attachmentlog_response_compound_t;

#include "attachmentlog_response.h"
#include "field_e_attachmentlog_type.h"

// Enum  for attachmentlog_response_compound

typedef enum  { ezmax_api_definition__full_attachmentlog_response_compound__NULL = 0, ezmax_api_definition__full_attachmentlog_response_compound__AutoValidation, ezmax_api_definition__full_attachmentlog_response_compound__CopyFrom, ezmax_api_definition__full_attachmentlog_response_compound__CopyTo, ezmax_api_definition__full_attachmentlog_response_compound__CopyToEzsign, ezmax_api_definition__full_attachmentlog_response_compound__CreateByEzsign, ezmax_api_definition__full_attachmentlog_response_compound__Download, ezmax_api_definition__full_attachmentlog_response_compound__Deleted, ezmax_api_definition__full_attachmentlog_response_compound__Destroyed, ezmax_api_definition__full_attachmentlog_response_compound__Email, ezmax_api_definition__full_attachmentlog_response_compound__EmailCC, ezmax_api_definition__full_attachmentlog_response_compound__EmailCCI, ezmax_api_definition__full_attachmentlog_response_compound__Fax, ezmax_api_definition__full_attachmentlog_response_compound__ImportedFromExternalSystem, ezmax_api_definition__full_attachmentlog_response_compound__ImportedFromEZA, ezmax_api_definition__full_attachmentlog_response_compound__ImportedFromFaltour, ezmax_api_definition__full_attachmentlog_response_compound__ImportedFromLonewolf, ezmax_api_definition__full_attachmentlog_response_compound__ImportedFromProspects, ezmax_api_definition__full_attachmentlog_response_compound__Move, ezmax_api_definition__full_attachmentlog_response_compound__OpenFromEmail, ezmax_api_definition__full_attachmentlog_response_compound__Purged, ezmax_api_definition__full_attachmentlog_response_compound__Reject, ezmax_api_definition__full_attachmentlog_response_compound__Rename, ezmax_api_definition__full_attachmentlog_response_compound__Restore, ezmax_api_definition__full_attachmentlog_response_compound__Scanned, ezmax_api_definition__full_attachmentlog_response_compound__SendToGED, ezmax_api_definition__full_attachmentlog_response_compound__UnvalidatedBy, ezmax_api_definition__full_attachmentlog_response_compound__Upload, ezmax_api_definition__full_attachmentlog_response_compound__ValidatedBy, ezmax_api_definition__full_attachmentlog_response_compound__VetinfoUpload } ezmax_api_definition__full_attachmentlog_response_compound__e;

char* attachmentlog_response_compound_e_attachmentlog_type_ToString(ezmax_api_definition__full_attachmentlog_response_compound__e e_attachmentlog_type);

ezmax_api_definition__full_attachmentlog_response_compound__e attachmentlog_response_compound_e_attachmentlog_type_FromString(char* e_attachmentlog_type);



typedef struct attachmentlog_response_compound_t {
    int fki_attachment_id; //numeric
    int fki_user_id; //numeric
    char *dt_attachmentlog_datetime; // string
    field_e_attachmentlog_type_t *e_attachmentlog_type; // custom
    char *s_attachmentlog_detail; // string

} attachmentlog_response_compound_t;

attachmentlog_response_compound_t *attachmentlog_response_compound_create(
    int fki_attachment_id,
    int fki_user_id,
    char *dt_attachmentlog_datetime,
    field_e_attachmentlog_type_t *e_attachmentlog_type,
    char *s_attachmentlog_detail
);

void attachmentlog_response_compound_free(attachmentlog_response_compound_t *attachmentlog_response_compound);

attachmentlog_response_compound_t *attachmentlog_response_compound_parseFromJSON(cJSON *attachmentlog_response_compoundJSON);

cJSON *attachmentlog_response_compound_convertToJSON(attachmentlog_response_compound_t *attachmentlog_response_compound);

#endif /* _attachmentlog_response_compound_H_ */

