/*
 * billingentityexternal_get_autocomplete_v2_response_all_of.h
 *
 * 
 */

#ifndef _billingentityexternal_get_autocomplete_v2_response_all_of_H_
#define _billingentityexternal_get_autocomplete_v2_response_all_of_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct billingentityexternal_get_autocomplete_v2_response_all_of_t billingentityexternal_get_autocomplete_v2_response_all_of_t;

#include "billingentityexternal_get_autocomplete_v2_response_m_payload.h"



typedef struct billingentityexternal_get_autocomplete_v2_response_all_of_t {
    struct billingentityexternal_get_autocomplete_v2_response_m_payload_t *m_payload; //model

} billingentityexternal_get_autocomplete_v2_response_all_of_t;

billingentityexternal_get_autocomplete_v2_response_all_of_t *billingentityexternal_get_autocomplete_v2_response_all_of_create(
    billingentityexternal_get_autocomplete_v2_response_m_payload_t *m_payload
);

void billingentityexternal_get_autocomplete_v2_response_all_of_free(billingentityexternal_get_autocomplete_v2_response_all_of_t *billingentityexternal_get_autocomplete_v2_response_all_of);

billingentityexternal_get_autocomplete_v2_response_all_of_t *billingentityexternal_get_autocomplete_v2_response_all_of_parseFromJSON(cJSON *billingentityexternal_get_autocomplete_v2_response_all_ofJSON);

cJSON *billingentityexternal_get_autocomplete_v2_response_all_of_convertToJSON(billingentityexternal_get_autocomplete_v2_response_all_of_t *billingentityexternal_get_autocomplete_v2_response_all_of);

#endif /* _billingentityexternal_get_autocomplete_v2_response_all_of_H_ */

