/*
 * common_response_error_wrong_franchiseoffice.h
 *
 * Error Message when a Franchisebroker is not in this Franchiseoffice.
 */

#ifndef _common_response_error_wrong_franchiseoffice_H_
#define _common_response_error_wrong_franchiseoffice_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct common_response_error_wrong_franchiseoffice_t common_response_error_wrong_franchiseoffice_t;

#include "field_e_error_code.h"

// Enum  for common_response_error_wrong_franchiseoffice

typedef enum  { ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__NULL = 0, ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__BADREQUEST, ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__BADREQUEST_CLOCKSKEW, ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__UNAUTHORIZED_BADAUTH, ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__UNAUTHORIZED_BADMFA, ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__UNAUTHORIZED_EXPIRED, ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__UNAUTHORIZED_REQUEST, ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__FORBIDDEN, ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__FORBIDDEN_CONFIGURATION, ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__FORBIDDEN_MODULE, ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__FORBIDDEN_NOACCESS, ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__FORBIDDEN_PERMISSION, ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__FORBIDDEN_SUBSCRIPTION, ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__FORBIDDEN_USERTYPE, ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__FORBIDDEN_USER_ORIGIN_EXTERNAL, ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__NOTFOUND, ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__NOTFOUND_OBJECT, ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__NOTFOUND_ROUTE, ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__METHODNOTALLOWED, ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__NOTACCEPTABLE_CONTENT, ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__NOTACCEPTABLE_LANGUAGE, ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__UNPROCESSABLEENTITY_ACTIVESESSION_ALREADY_CLONING, ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__UNPROCESSABLEENTITY_CANNOTDELETE, ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__UNPROCESSABLEENTITY_CANNOTMODIFY, ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__UNPROCESSABLEENTITY_CHANGEPASSWORD_INVALID_CURRENT, ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__UNPROCESSABLEENTITY_CHANGEPASSWORD_SAME, ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__UNPROCESSABLEENTITY_DATA_MISSING, ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__UNPROCESSABLEENTITY_DATA_UNIQUE, ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__UNPROCESSABLEENTITY_DATA_VALIDATION, ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__UNPROCESSABLEENTITY_DATA_OUTOFBOUND, ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__UNPROCESSABLEENTITY_DOWNLOAD_ERROR, ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__UNPROCESSABLEENTITY_EZSIGNFORM_VALIDATION, ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__UNPROCESSABLEENTITY_EZSIGNSIGNERCONNECTED, ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__UNPROCESSABLEENTITY_NOTHINGTODO, ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__UNPROCESSABLEENTITY_NOTREADY, ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__UNPROCESSABLEENTITY_PDF_FORM, ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__UNPROCESSABLEENTITY_PDF_SIGNATURE, ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__UNPROCESSABLEENTITY_PDF_FORM_AND_SIGNATURE, ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__UNPROCESSABLEENTITY_PDF_INCOMPATIBLE, ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__UNPROCESSABLEENTITY_PDF_PASSWORD, ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__UNPROCESSABLEENTITY_PDF_WRONG_PASSWORD, ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__UNPROCESSABLEENTITY_PDF_REPAIRABLE, ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__UNPROCESSABLEENTITY_PDF_XFA, ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__UNPROCESSABLEENTITY_TEMPLATE_MISMATCH, ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__UNPROCESSABLEENTITY_UNMODIFIABLE_FIELD, ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__UNPROCESSABLEENTITY_USER_STAGED, ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__TOOMANYREQUESTS, ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__TOOMANYREQUESTS_THIRDPARTY, ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__ERROR_INTERNAL, ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__ERROR_CONFIGURATION, ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__ERROR_NOTIMPLEMENTED } ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__e;

char* common_response_error_wrong_franchiseoffice_e_error_code_ToString(ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__e e_error_code);

ezmax_api_definition__full_common_response_error_wrong_franchiseoffice__e common_response_error_wrong_franchiseoffice_e_error_code_FromString(char* e_error_code);



typedef struct common_response_error_wrong_franchiseoffice_t {
    char *s_error_message; // string
    field_e_error_code_t *e_error_code; // custom
    list_t *a_s_error_messagedetail; //primitive container
    int fki_franchiseagence_id; //numeric
    char *s_franchiseagence_name; // string
    int fki_franchiseoffice_id; //numeric
    char *i_franchiseoffice_code; // string

} common_response_error_wrong_franchiseoffice_t;

common_response_error_wrong_franchiseoffice_t *common_response_error_wrong_franchiseoffice_create(
    char *s_error_message,
    field_e_error_code_t *e_error_code,
    list_t *a_s_error_messagedetail,
    int fki_franchiseagence_id,
    char *s_franchiseagence_name,
    int fki_franchiseoffice_id,
    char *i_franchiseoffice_code
);

void common_response_error_wrong_franchiseoffice_free(common_response_error_wrong_franchiseoffice_t *common_response_error_wrong_franchiseoffice);

common_response_error_wrong_franchiseoffice_t *common_response_error_wrong_franchiseoffice_parseFromJSON(cJSON *common_response_error_wrong_franchiseofficeJSON);

cJSON *common_response_error_wrong_franchiseoffice_convertToJSON(common_response_error_wrong_franchiseoffice_t *common_response_error_wrong_franchiseoffice);

#endif /* _common_response_error_wrong_franchiseoffice_H_ */

