/*
 * common_response_error_s_temporary_file_url.h
 *
 * Generic Error Message
 */

#ifndef _common_response_error_s_temporary_file_url_H_
#define _common_response_error_s_temporary_file_url_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct common_response_error_s_temporary_file_url_t common_response_error_s_temporary_file_url_t;

#include "field_e_error_code.h"

// Enum  for common_response_error_s_temporary_file_url

typedef enum  { ezmax_api_definition__full_common_response_error_s_temporary_file_url__NULL = 0, ezmax_api_definition__full_common_response_error_s_temporary_file_url__BADREQUEST, ezmax_api_definition__full_common_response_error_s_temporary_file_url__BADREQUEST_CLOCKSKEW, ezmax_api_definition__full_common_response_error_s_temporary_file_url__UNAUTHORIZED_BADAUTH, ezmax_api_definition__full_common_response_error_s_temporary_file_url__UNAUTHORIZED_BADMFA, ezmax_api_definition__full_common_response_error_s_temporary_file_url__UNAUTHORIZED_EXPIRED, ezmax_api_definition__full_common_response_error_s_temporary_file_url__UNAUTHORIZED_REQUEST, ezmax_api_definition__full_common_response_error_s_temporary_file_url__FORBIDDEN, ezmax_api_definition__full_common_response_error_s_temporary_file_url__FORBIDDEN_CONFIGURATION, ezmax_api_definition__full_common_response_error_s_temporary_file_url__FORBIDDEN_MODULE, ezmax_api_definition__full_common_response_error_s_temporary_file_url__FORBIDDEN_NOACCESS, ezmax_api_definition__full_common_response_error_s_temporary_file_url__FORBIDDEN_PERMISSION, ezmax_api_definition__full_common_response_error_s_temporary_file_url__FORBIDDEN_SUBSCRIPTION, ezmax_api_definition__full_common_response_error_s_temporary_file_url__FORBIDDEN_USERTYPE, ezmax_api_definition__full_common_response_error_s_temporary_file_url__FORBIDDEN_USER_ORIGIN_EXTERNAL, ezmax_api_definition__full_common_response_error_s_temporary_file_url__NOTFOUND, ezmax_api_definition__full_common_response_error_s_temporary_file_url__NOTFOUND_OBJECT, ezmax_api_definition__full_common_response_error_s_temporary_file_url__NOTFOUND_ROUTE, ezmax_api_definition__full_common_response_error_s_temporary_file_url__METHODNOTALLOWED, ezmax_api_definition__full_common_response_error_s_temporary_file_url__NOTACCEPTABLE_CONTENT, ezmax_api_definition__full_common_response_error_s_temporary_file_url__NOTACCEPTABLE_LANGUAGE, ezmax_api_definition__full_common_response_error_s_temporary_file_url__UNPROCESSABLEENTITY_ACTIVESESSION_ALREADY_CLONING, ezmax_api_definition__full_common_response_error_s_temporary_file_url__UNPROCESSABLEENTITY_CANNOTDELETE, ezmax_api_definition__full_common_response_error_s_temporary_file_url__UNPROCESSABLEENTITY_CANNOTMODIFY, ezmax_api_definition__full_common_response_error_s_temporary_file_url__UNPROCESSABLEENTITY_CHANGEPASSWORD_INVALID_CURRENT, ezmax_api_definition__full_common_response_error_s_temporary_file_url__UNPROCESSABLEENTITY_CHANGEPASSWORD_SAME, ezmax_api_definition__full_common_response_error_s_temporary_file_url__UNPROCESSABLEENTITY_DATA_MISSING, ezmax_api_definition__full_common_response_error_s_temporary_file_url__UNPROCESSABLEENTITY_DATA_UNIQUE, ezmax_api_definition__full_common_response_error_s_temporary_file_url__UNPROCESSABLEENTITY_DATA_VALIDATION, ezmax_api_definition__full_common_response_error_s_temporary_file_url__UNPROCESSABLEENTITY_DATA_OUTOFBOUND, ezmax_api_definition__full_common_response_error_s_temporary_file_url__UNPROCESSABLEENTITY_DOWNLOAD_ERROR, ezmax_api_definition__full_common_response_error_s_temporary_file_url__UNPROCESSABLEENTITY_EZSIGNFORM_VALIDATION, ezmax_api_definition__full_common_response_error_s_temporary_file_url__UNPROCESSABLEENTITY_EZSIGNSIGNERCONNECTED, ezmax_api_definition__full_common_response_error_s_temporary_file_url__UNPROCESSABLEENTITY_NOTHINGTODO, ezmax_api_definition__full_common_response_error_s_temporary_file_url__UNPROCESSABLEENTITY_NOTREADY, ezmax_api_definition__full_common_response_error_s_temporary_file_url__UNPROCESSABLEENTITY_PDF_FORM, ezmax_api_definition__full_common_response_error_s_temporary_file_url__UNPROCESSABLEENTITY_PDF_SIGNATURE, ezmax_api_definition__full_common_response_error_s_temporary_file_url__UNPROCESSABLEENTITY_PDF_FORM_AND_SIGNATURE, ezmax_api_definition__full_common_response_error_s_temporary_file_url__UNPROCESSABLEENTITY_PDF_INCOMPATIBLE, ezmax_api_definition__full_common_response_error_s_temporary_file_url__UNPROCESSABLEENTITY_PDF_PASSWORD, ezmax_api_definition__full_common_response_error_s_temporary_file_url__UNPROCESSABLEENTITY_PDF_WRONG_PASSWORD, ezmax_api_definition__full_common_response_error_s_temporary_file_url__UNPROCESSABLEENTITY_PDF_REPAIRABLE, ezmax_api_definition__full_common_response_error_s_temporary_file_url__UNPROCESSABLEENTITY_PDF_XFA, ezmax_api_definition__full_common_response_error_s_temporary_file_url__UNPROCESSABLEENTITY_TEMPLATE_MISMATCH, ezmax_api_definition__full_common_response_error_s_temporary_file_url__UNPROCESSABLEENTITY_UNMODIFIABLE_FIELD, ezmax_api_definition__full_common_response_error_s_temporary_file_url__UNPROCESSABLEENTITY_USER_STAGED, ezmax_api_definition__full_common_response_error_s_temporary_file_url__TOOMANYREQUESTS, ezmax_api_definition__full_common_response_error_s_temporary_file_url__TOOMANYREQUESTS_THIRDPARTY, ezmax_api_definition__full_common_response_error_s_temporary_file_url__ERROR_INTERNAL, ezmax_api_definition__full_common_response_error_s_temporary_file_url__ERROR_CONFIGURATION, ezmax_api_definition__full_common_response_error_s_temporary_file_url__ERROR_NOTIMPLEMENTED } ezmax_api_definition__full_common_response_error_s_temporary_file_url__e;

char* common_response_error_s_temporary_file_url_e_error_code_ToString(ezmax_api_definition__full_common_response_error_s_temporary_file_url__e e_error_code);

ezmax_api_definition__full_common_response_error_s_temporary_file_url__e common_response_error_s_temporary_file_url_e_error_code_FromString(char* e_error_code);



typedef struct common_response_error_s_temporary_file_url_t {
    char *s_error_message; // string
    field_e_error_code_t *e_error_code; // custom
    char *s_temporary_file_url; // string

} common_response_error_s_temporary_file_url_t;

common_response_error_s_temporary_file_url_t *common_response_error_s_temporary_file_url_create(
    char *s_error_message,
    field_e_error_code_t *e_error_code,
    char *s_temporary_file_url
);

void common_response_error_s_temporary_file_url_free(common_response_error_s_temporary_file_url_t *common_response_error_s_temporary_file_url);

common_response_error_s_temporary_file_url_t *common_response_error_s_temporary_file_url_parseFromJSON(cJSON *common_response_error_s_temporary_file_urlJSON);

cJSON *common_response_error_s_temporary_file_url_convertToJSON(common_response_error_s_temporary_file_url_t *common_response_error_s_temporary_file_url);

#endif /* _common_response_error_s_temporary_file_url_H_ */

