/*
 * communicationexternalrecipient_response_compound.h
 *
 * A Communicationexternalrecipient Object
 */

#ifndef _communicationexternalrecipient_response_compound_H_
#define _communicationexternalrecipient_response_compound_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct communicationexternalrecipient_response_compound_t communicationexternalrecipient_response_compound_t;

#include "field_e_communicationexternalrecipient_type.h"
#include "phone_response_compound.h"

// Enum  for communicationexternalrecipient_response_compound

typedef enum  { ezmax_api_definition__full_communicationexternalrecipient_response_compound__NULL = 0, ezmax_api_definition__full_communicationexternalrecipient_response_compound__To, ezmax_api_definition__full_communicationexternalrecipient_response_compound__Cc, ezmax_api_definition__full_communicationexternalrecipient_response_compound__Bcc } ezmax_api_definition__full_communicationexternalrecipient_response_compound__e;

char* communicationexternalrecipient_response_compound_e_communicationexternalrecipient_type_ToString(ezmax_api_definition__full_communicationexternalrecipient_response_compound__e e_communicationexternalrecipient_type);

ezmax_api_definition__full_communicationexternalrecipient_response_compound__e communicationexternalrecipient_response_compound_e_communicationexternalrecipient_type_FromString(char* e_communicationexternalrecipient_type);



typedef struct communicationexternalrecipient_response_compound_t {
    int pki_communicationexternalrecipient_id; //numeric
    char *s_email_address; // string
    struct phone_response_compound_t *obj_phone_sms; //model
    field_e_communicationexternalrecipient_type_t *e_communicationexternalrecipient_type; // custom
    char *s_communicationexternalrecipient_name; // string

} communicationexternalrecipient_response_compound_t;

communicationexternalrecipient_response_compound_t *communicationexternalrecipient_response_compound_create(
    int pki_communicationexternalrecipient_id,
    char *s_email_address,
    phone_response_compound_t *obj_phone_sms,
    field_e_communicationexternalrecipient_type_t *e_communicationexternalrecipient_type,
    char *s_communicationexternalrecipient_name
);

void communicationexternalrecipient_response_compound_free(communicationexternalrecipient_response_compound_t *communicationexternalrecipient_response_compound);

communicationexternalrecipient_response_compound_t *communicationexternalrecipient_response_compound_parseFromJSON(cJSON *communicationexternalrecipient_response_compoundJSON);

cJSON *communicationexternalrecipient_response_compound_convertToJSON(communicationexternalrecipient_response_compound_t *communicationexternalrecipient_response_compound);

#endif /* _communicationexternalrecipient_response_compound_H_ */

