/*
 * custom_creditcardtransactionresponse_response.h
 *
 * A custom Creditcardtransactionresponse Object
 */

#ifndef _custom_creditcardtransactionresponse_response_H_
#define _custom_creditcardtransactionresponse_response_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct custom_creditcardtransactionresponse_response_t custom_creditcardtransactionresponse_response_t;

#include "field_e_creditcardtransaction_avsresult.h"
#include "field_e_creditcardtransaction_cvdresult.h"

// Enum  for custom_creditcardtransactionresponse_response

typedef enum  { ezmax_api_definition__full_custom_creditcardtransactionresponse_response__NULL = 0, ezmax_api_definition__full_custom_creditcardtransactionresponse_response__Match, ezmax_api_definition__full_custom_creditcardtransactionresponse_response__NoMatch, ezmax_api_definition__full_custom_creditcardtransactionresponse_response__PartialMatch, ezmax_api_definition__full_custom_creditcardtransactionresponse_response__NotImplemented, ezmax_api_definition__full_custom_creditcardtransactionresponse_response__NotVerified } ezmax_api_definition__full_custom_creditcardtransactionresponse_response__e;

char* custom_creditcardtransactionresponse_response_e_creditcardtransaction_avsresult_ToString(ezmax_api_definition__full_custom_creditcardtransactionresponse_response__e e_creditcardtransaction_avsresult);

ezmax_api_definition__full_custom_creditcardtransactionresponse_response__e custom_creditcardtransactionresponse_response_e_creditcardtransaction_avsresult_FromString(char* e_creditcardtransaction_avsresult);

// Enum  for custom_creditcardtransactionresponse_response

typedef enum  { ezmax_api_definition__full_custom_creditcardtransactionresponse_response__NULL = 0, ezmax_api_definition__full_custom_creditcardtransactionresponse_response__Match, ezmax_api_definition__full_custom_creditcardtransactionresponse_response__NoMatch, ezmax_api_definition__full_custom_creditcardtransactionresponse_response__NotVerified } ezmax_api_definition__full_custom_creditcardtransactionresponse_response__e;

char* custom_creditcardtransactionresponse_response_e_creditcardtransaction_cvdresult_ToString(ezmax_api_definition__full_custom_creditcardtransactionresponse_response__e e_creditcardtransaction_cvdresult);

ezmax_api_definition__full_custom_creditcardtransactionresponse_response__e custom_creditcardtransactionresponse_response_e_creditcardtransaction_cvdresult_FromString(char* e_creditcardtransaction_cvdresult);



typedef struct custom_creditcardtransactionresponse_response_t {
    char *s_creditcardtransaction_is_ocode; // string
    char *s_creditcardtransaction_responsecode; // string
    char *s_creditcardtransaction_responseterminalmessage; // string
    field_e_creditcardtransaction_avsresult_t *e_creditcardtransaction_avsresult; // custom
    field_e_creditcardtransaction_cvdresult_t *e_creditcardtransaction_cvdresult; // custom

} custom_creditcardtransactionresponse_response_t;

custom_creditcardtransactionresponse_response_t *custom_creditcardtransactionresponse_response_create(
    char *s_creditcardtransaction_is_ocode,
    char *s_creditcardtransaction_responsecode,
    char *s_creditcardtransaction_responseterminalmessage,
    field_e_creditcardtransaction_avsresult_t *e_creditcardtransaction_avsresult,
    field_e_creditcardtransaction_cvdresult_t *e_creditcardtransaction_cvdresult
);

void custom_creditcardtransactionresponse_response_free(custom_creditcardtransactionresponse_response_t *custom_creditcardtransactionresponse_response);

custom_creditcardtransactionresponse_response_t *custom_creditcardtransactionresponse_response_parseFromJSON(cJSON *custom_creditcardtransactionresponse_responseJSON);

cJSON *custom_creditcardtransactionresponse_response_convertToJSON(custom_creditcardtransactionresponse_response_t *custom_creditcardtransactionresponse_response);

#endif /* _custom_creditcardtransactionresponse_response_H_ */

