/*
 * custom_notificationsubsectiongetnotificationtests_response_all_of.h
 *
 * 
 */

#ifndef _custom_notificationsubsectiongetnotificationtests_response_all_of_H_
#define _custom_notificationsubsectiongetnotificationtests_response_all_of_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct custom_notificationsubsectiongetnotificationtests_response_all_of_t custom_notificationsubsectiongetnotificationtests_response_all_of_t;

#include "custom_notificationtestgetnotificationtests_response.h"



typedef struct custom_notificationsubsectiongetnotificationtests_response_all_of_t {
    list_t *a_obj_notificationtest; //nonprimitive container

} custom_notificationsubsectiongetnotificationtests_response_all_of_t;

custom_notificationsubsectiongetnotificationtests_response_all_of_t *custom_notificationsubsectiongetnotificationtests_response_all_of_create(
    list_t *a_obj_notificationtest
);

void custom_notificationsubsectiongetnotificationtests_response_all_of_free(custom_notificationsubsectiongetnotificationtests_response_all_of_t *custom_notificationsubsectiongetnotificationtests_response_all_of);

custom_notificationsubsectiongetnotificationtests_response_all_of_t *custom_notificationsubsectiongetnotificationtests_response_all_of_parseFromJSON(cJSON *custom_notificationsubsectiongetnotificationtests_response_all_ofJSON);

cJSON *custom_notificationsubsectiongetnotificationtests_response_all_of_convertToJSON(custom_notificationsubsectiongetnotificationtests_response_all_of_t *custom_notificationsubsectiongetnotificationtests_response_all_of);

#endif /* _custom_notificationsubsectiongetnotificationtests_response_all_of_H_ */

