/*
 * custom_attachmentdocumenttype_response.h
 *
 * An Attachmentdocumenttype
 */

#ifndef _custom_attachmentdocumenttype_response_H_
#define _custom_attachmentdocumenttype_response_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct custom_attachmentdocumenttype_response_t custom_attachmentdocumenttype_response_t;

#include "custom_attachment_response.h"
#include "field_e_attachment_documenttype.h"

// Enum  for custom_attachmentdocumenttype_response

typedef enum  { ezmax_api_definition__full_custom_attachmentdocumenttype_response__NULL = 0, ezmax_api_definition__full_custom_attachmentdocumenttype_response__Adjustment, ezmax_api_definition__full_custom_attachmentdocumenttype_response__Agent, ezmax_api_definition__full_custom_attachmentdocumenttype_response__Bankaccount, ezmax_api_definition__full_custom_attachmentdocumenttype_response__Broker, ezmax_api_definition__full_custom_attachmentdocumenttype_response__Buyercontract, ezmax_api_definition__full_custom_attachmentdocumenttype_response__Commissionadvance, ezmax_api_definition__full_custom_attachmentdocumenttype_response__Communication, ezmax_api_definition__full_custom_attachmentdocumenttype_response__Customer, ezmax_api_definition__full_custom_attachmentdocumenttype_response__Customertemplate, ezmax_api_definition__full_custom_attachmentdocumenttype_response__Deposit, ezmax_api_definition__full_custom_attachmentdocumenttype_response__Deposittransitcheque, ezmax_api_definition__full_custom_attachmentdocumenttype_response__Disclosure, ezmax_api_definition__full_custom_attachmentdocumenttype_response__Electronicfundstransfer, ezmax_api_definition__full_custom_attachmentdocumenttype_response__Employee, ezmax_api_definition__full_custom_attachmentdocumenttype_response__Externalbroker, ezmax_api_definition__full_custom_attachmentdocumenttype_response__Ezcomadvanceserver, ezmax_api_definition__full_custom_attachmentdocumenttype_response__Ezcomcompany, ezmax_api_definition__full_custom_attachmentdocumenttype_response__Ezsigndocument, ezmax_api_definition__full_custom_attachmentdocumenttype_response__EzsigndocumentProof, ezmax_api_definition__full_custom_attachmentdocumenttype_response__EzsigndocumentProofdocument, ezmax_api_definition__full_custom_attachmentdocumenttype_response__Ezsigndocumentgroup, ezmax_api_definition__full_custom_attachmentdocumenttype_response__EzsigndocumentgroupProof, ezmax_api_definition__full_custom_attachmentdocumenttype_response__EzsigndocumentgroupProofdocument, ezmax_api_definition__full_custom_attachmentdocumenttype_response__EzsigndocumentAttachment, ezmax_api_definition__full_custom_attachmentdocumenttype_response__Folder, ezmax_api_definition__full_custom_attachmentdocumenttype_response__Franchiseagence, ezmax_api_definition__full_custom_attachmentdocumenttype_response__Franchisebroker, ezmax_api_definition__full_custom_attachmentdocumenttype_response__Franchisecomplaint, ezmax_api_definition__full_custom_attachmentdocumenttype_response__Franchisefranchise, ezmax_api_definition__full_custom_attachmentdocumenttype_response__Franchiseoffice, ezmax_api_definition__full_custom_attachmentdocumenttype_response__Ghacqcontract, ezmax_api_definition__full_custom_attachmentdocumenttype_response__Inscription, ezmax_api_definition__full_custom_attachmentdocumenttype_response__Inscriptionnotauthenticated, ezmax_api_definition__full_custom_attachmentdocumenttype_response__Inscriptiontemp, ezmax_api_definition__full_custom_attachmentdocumenttype_response__Invoice, ezmax_api_definition__full_custom_attachmentdocumenttype_response__Lead, ezmax_api_definition__full_custom_attachmentdocumenttype_response__Marketingfollow, ezmax_api_definition__full_custom_attachmentdocumenttype_response__Marketingprogram, ezmax_api_definition__full_custom_attachmentdocumenttype_response__Notary, ezmax_api_definition__full_custom_attachmentdocumenttype_response__Officetaxreport, ezmax_api_definition__full_custom_attachmentdocumenttype_response__Otherincome, ezmax_api_definition__full_custom_attachmentdocumenttype_response__Paymentpreparation, ezmax_api_definition__full_custom_attachmentdocumenttype_response__Purchase, ezmax_api_definition__full_custom_attachmentdocumenttype_response__Reconciliation, ezmax_api_definition__full_custom_attachmentdocumenttype_response__Rejectedoffertopurchase, ezmax_api_definition__full_custom_attachmentdocumenttype_response__Salary, ezmax_api_definition__full_custom_attachmentdocumenttype_response__Supplier, ezmax_api_definition__full_custom_attachmentdocumenttype_response___Template, ezmax_api_definition__full_custom_attachmentdocumenttype_response__Tranqcontract } ezmax_api_definition__full_custom_attachmentdocumenttype_response__e;

char* custom_attachmentdocumenttype_response_e_attachment_documenttype_ToString(ezmax_api_definition__full_custom_attachmentdocumenttype_response__e e_attachment_documenttype);

ezmax_api_definition__full_custom_attachmentdocumenttype_response__e custom_attachmentdocumenttype_response_e_attachment_documenttype_FromString(char* e_attachment_documenttype);



typedef struct custom_attachmentdocumenttype_response_t {
    field_e_attachment_documenttype_t *e_attachment_documenttype; // custom
    list_t *a_obj_attachment; //nonprimitive container

} custom_attachmentdocumenttype_response_t;

custom_attachmentdocumenttype_response_t *custom_attachmentdocumenttype_response_create(
    field_e_attachment_documenttype_t *e_attachment_documenttype,
    list_t *a_obj_attachment
);

void custom_attachmentdocumenttype_response_free(custom_attachmentdocumenttype_response_t *custom_attachmentdocumenttype_response);

custom_attachmentdocumenttype_response_t *custom_attachmentdocumenttype_response_parseFromJSON(cJSON *custom_attachmentdocumenttype_responseJSON);

cJSON *custom_attachmentdocumenttype_response_convertToJSON(custom_attachmentdocumenttype_response_t *custom_attachmentdocumenttype_response);

#endif /* _custom_attachmentdocumenttype_response_H_ */

