/*
 * custom_ezsignfoldersignerassociation_actionable_element_response_all_of.h
 *
 * 
 */

#ifndef _custom_ezsignfoldersignerassociation_actionable_element_response_all_of_H_
#define _custom_ezsignfoldersignerassociation_actionable_element_response_all_of_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct custom_ezsignfoldersignerassociation_actionable_element_response_all_of_t custom_ezsignfoldersignerassociation_actionable_element_response_all_of_t;




typedef struct custom_ezsignfoldersignerassociation_actionable_element_response_all_of_t {
    int b_ezsignfoldersignerassociation_hasactionableelements_current; //boolean
    int b_ezsignfoldersignerassociation_hasactionableelements_future; //boolean

} custom_ezsignfoldersignerassociation_actionable_element_response_all_of_t;

custom_ezsignfoldersignerassociation_actionable_element_response_all_of_t *custom_ezsignfoldersignerassociation_actionable_element_response_all_of_create(
    int b_ezsignfoldersignerassociation_hasactionableelements_current,
    int b_ezsignfoldersignerassociation_hasactionableelements_future
);

void custom_ezsignfoldersignerassociation_actionable_element_response_all_of_free(custom_ezsignfoldersignerassociation_actionable_element_response_all_of_t *custom_ezsignfoldersignerassociation_actionable_element_response_all_of);

custom_ezsignfoldersignerassociation_actionable_element_response_all_of_t *custom_ezsignfoldersignerassociation_actionable_element_response_all_of_parseFromJSON(cJSON *custom_ezsignfoldersignerassociation_actionable_element_response_all_ofJSON);

cJSON *custom_ezsignfoldersignerassociation_actionable_element_response_all_of_convertToJSON(custom_ezsignfoldersignerassociation_actionable_element_response_all_of_t *custom_ezsignfoldersignerassociation_actionable_element_response_all_of);

#endif /* _custom_ezsignfoldersignerassociation_actionable_element_response_all_of_H_ */

