/*
 * electronicfundstransfer_get_communicationsenders_v1_response_m_payload.h
 *
 * Response for GET /1/object/electronicfundstransfer/{pkiElectronicfundstransferID}/getCommunicationsenders
 */

#ifndef _electronicfundstransfer_get_communicationsenders_v1_response_m_payload_H_
#define _electronicfundstransfer_get_communicationsenders_v1_response_m_payload_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct electronicfundstransfer_get_communicationsenders_v1_response_m_payload_t electronicfundstransfer_get_communicationsenders_v1_response_m_payload_t;

#include "custom_communicationsender_response.h"



typedef struct electronicfundstransfer_get_communicationsenders_v1_response_m_payload_t {
    list_t *a_obj_communicationsenders; //nonprimitive container

} electronicfundstransfer_get_communicationsenders_v1_response_m_payload_t;

electronicfundstransfer_get_communicationsenders_v1_response_m_payload_t *electronicfundstransfer_get_communicationsenders_v1_response_m_payload_create(
    list_t *a_obj_communicationsenders
);

void electronicfundstransfer_get_communicationsenders_v1_response_m_payload_free(electronicfundstransfer_get_communicationsenders_v1_response_m_payload_t *electronicfundstransfer_get_communicationsenders_v1_response_m_payload);

electronicfundstransfer_get_communicationsenders_v1_response_m_payload_t *electronicfundstransfer_get_communicationsenders_v1_response_m_payload_parseFromJSON(cJSON *electronicfundstransfer_get_communicationsenders_v1_response_m_payloadJSON);

cJSON *electronicfundstransfer_get_communicationsenders_v1_response_m_payload_convertToJSON(electronicfundstransfer_get_communicationsenders_v1_response_m_payload_t *electronicfundstransfer_get_communicationsenders_v1_response_m_payload);

#endif /* _electronicfundstransfer_get_communicationsenders_v1_response_m_payload_H_ */

