/*
 * ezsigntemplatesignature_response_compound_v3.h
 *
 * A Ezsigntemplatesignature Object
 */

#ifndef _ezsigntemplatesignature_response_compound_v3_H_
#define _ezsigntemplatesignature_response_compound_v3_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct ezsigntemplatesignature_response_compound_v3_t ezsigntemplatesignature_response_compound_v3_t;

#include "enum_textvalidation.h"
#include "ezsigntemplateelementdependency_response.h"
#include "ezsigntemplatesignature_response.h"
#include "ezsigntemplatesignaturecustomdate_response_v2.h"
#include "field_e_ezsigntemplatesignature_attachmentnamesource.h"
#include "field_e_ezsigntemplatesignature_consultationtrigger.h"
#include "field_e_ezsigntemplatesignature_dependencyrequirement.h"
#include "field_e_ezsigntemplatesignature_font.h"
#include "field_e_ezsigntemplatesignature_positioning.h"
#include "field_e_ezsigntemplatesignature_positioningoccurence.h"
#include "field_e_ezsigntemplatesignature_tooltipposition.h"
#include "field_e_ezsigntemplatesignature_type.h"

// Enum  for ezsigntemplatesignature_response_compound_v3

typedef enum  { ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__NULL = 0, ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__PerCoordinates, ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__PerPositioningPattern } ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__e;

char* ezsigntemplatesignature_response_compound_v3_e_ezsigntemplatesignature_positioning_ToString(ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__e e_ezsigntemplatesignature_positioning);

ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__e ezsigntemplatesignature_response_compound_v3_e_ezsigntemplatesignature_positioning_FromString(char* e_ezsigntemplatesignature_positioning);

// Enum  for ezsigntemplatesignature_response_compound_v3

typedef enum  { ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__NULL = 0, ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__Acknowledgement, ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__City, ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__Handwritten, ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__Initials, ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__Name, ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__NameReason, ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__Attachments, ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__FieldText, ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__FieldTextarea, ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__Consultation, ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__Signature } ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__e;

char* ezsigntemplatesignature_response_compound_v3_e_ezsigntemplatesignature_type_ToString(ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__e e_ezsigntemplatesignature_type);

ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__e ezsigntemplatesignature_response_compound_v3_e_ezsigntemplatesignature_type_FromString(char* e_ezsigntemplatesignature_type);

// Enum  for ezsigntemplatesignature_response_compound_v3

typedef enum  { ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__NULL = 0, ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__Automatic, ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__Manual } ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__e;

char* ezsigntemplatesignature_response_compound_v3_e_ezsigntemplatesignature_consultationtrigger_ToString(ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__e e_ezsigntemplatesignature_consultationtrigger);

ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__e ezsigntemplatesignature_response_compound_v3_e_ezsigntemplatesignature_consultationtrigger_FromString(char* e_ezsigntemplatesignature_consultationtrigger);

// Enum  for ezsigntemplatesignature_response_compound_v3

typedef enum  { ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__NULL = 0, ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__TopLeft, ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__TopCenter, ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__TopRight, ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__MiddleLeft, ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__MiddleRight, ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__BottomLeft, ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__BottomCenter, ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__BottomRight } ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__e;

char* ezsigntemplatesignature_response_compound_v3_e_ezsigntemplatesignature_tooltipposition_ToString(ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__e e_ezsigntemplatesignature_tooltipposition);

ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__e ezsigntemplatesignature_response_compound_v3_e_ezsigntemplatesignature_tooltipposition_FromString(char* e_ezsigntemplatesignature_tooltipposition);

// Enum  for ezsigntemplatesignature_response_compound_v3

typedef enum  { ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__NULL = 0, ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__Normal, ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__Cursive } ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__e;

char* ezsigntemplatesignature_response_compound_v3_e_ezsigntemplatesignature_font_ToString(ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__e e_ezsigntemplatesignature_font);

ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__e ezsigntemplatesignature_response_compound_v3_e_ezsigntemplatesignature_font_FromString(char* e_ezsigntemplatesignature_font);

// Enum  for ezsigntemplatesignature_response_compound_v3

typedef enum  { ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__NULL = 0, ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__Description, ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__Customer, ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__DescriptionCustomer } ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__e;

char* ezsigntemplatesignature_response_compound_v3_e_ezsigntemplatesignature_attachmentnamesource_ToString(ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__e e_ezsigntemplatesignature_attachmentnamesource);

ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__e ezsigntemplatesignature_response_compound_v3_e_ezsigntemplatesignature_attachmentnamesource_FromString(char* e_ezsigntemplatesignature_attachmentnamesource);

// Enum  for ezsigntemplatesignature_response_compound_v3

typedef enum  { ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__NULL = 0, ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__None, ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__Date (YYYY_MM_DD), ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__Date (MM/DD/YYYY), ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__Date (MM/DD/YY), ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__Date (DD/MM/YYYY), ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__Date (DD/MM/YY), ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__Email, ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__Letters, ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__Numbers, ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__Zip, ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__Zip+4, ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__PostalCode, ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__Custom } ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__e;

char* ezsigntemplatesignature_response_compound_v3_e_ezsigntemplatesignature_textvalidation_ToString(ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__e e_ezsigntemplatesignature_textvalidation);

ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__e ezsigntemplatesignature_response_compound_v3_e_ezsigntemplatesignature_textvalidation_FromString(char* e_ezsigntemplatesignature_textvalidation);

// Enum  for ezsigntemplatesignature_response_compound_v3

typedef enum  { ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__NULL = 0, ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__AllOf, ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__AnyOf } ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__e;

char* ezsigntemplatesignature_response_compound_v3_e_ezsigntemplatesignature_dependencyrequirement_ToString(ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__e e_ezsigntemplatesignature_dependencyrequirement);

ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__e ezsigntemplatesignature_response_compound_v3_e_ezsigntemplatesignature_dependencyrequirement_FromString(char* e_ezsigntemplatesignature_dependencyrequirement);

// Enum  for ezsigntemplatesignature_response_compound_v3

typedef enum  { ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__NULL = 0, ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__All, ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__First, ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__Last } ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__e;

char* ezsigntemplatesignature_response_compound_v3_e_ezsigntemplatesignature_positioningoccurence_ToString(ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__e e_ezsigntemplatesignature_positioningoccurence);

ezmax_api_definition__full_ezsigntemplatesignature_response_compound_v3__e ezsigntemplatesignature_response_compound_v3_e_ezsigntemplatesignature_positioningoccurence_FromString(char* e_ezsigntemplatesignature_positioningoccurence);



typedef struct ezsigntemplatesignature_response_compound_v3_t {
    int pki_ezsigntemplatesignature_id; //numeric
    int fki_ezsigntemplatedocument_id; //numeric
    int fki_ezsigntemplatesigner_id; //numeric
    int fki_ezsigntemplatesigner_id_validation; //numeric
    int b_ezsigntemplatesignature_handwritten; //boolean
    int b_ezsigntemplatesignature_reason; //boolean
    field_e_ezsigntemplatesignature_positioning_t *e_ezsigntemplatesignature_positioning; // custom
    int i_ezsigntemplatedocumentpage_pagenumber; //numeric
    int i_ezsigntemplatesignature_x; //numeric
    int i_ezsigntemplatesignature_y; //numeric
    int i_ezsigntemplatesignature_width; //numeric
    int i_ezsigntemplatesignature_height; //numeric
    int i_ezsigntemplatesignature_step; //numeric
    field_e_ezsigntemplatesignature_type_t *e_ezsigntemplatesignature_type; // custom
    field_e_ezsigntemplatesignature_consultationtrigger_t *e_ezsigntemplatesignature_consultationtrigger; // custom
    char *t_ezsigntemplatesignature_tooltip; // string
    field_e_ezsigntemplatesignature_tooltipposition_t *e_ezsigntemplatesignature_tooltipposition; // custom
    field_e_ezsigntemplatesignature_font_t *e_ezsigntemplatesignature_font; // custom
    int i_ezsigntemplatesignature_validationstep; //numeric
    char *s_ezsigntemplatesignature_attachmentdescription; // string
    field_e_ezsigntemplatesignature_attachmentnamesource_t *e_ezsigntemplatesignature_attachmentnamesource; // custom
    int b_ezsigntemplatesignature_required; //boolean
    int i_ezsigntemplatesignature_maxlength; //numeric
    char *s_ezsigntemplatesignature_defaultvalue; // string
    char *s_ezsigntemplatesignature_regexp; // string
    enum_textvalidation_t *e_ezsigntemplatesignature_textvalidation; // custom
    char *s_ezsigntemplatesignature_textvalidationcustommessage; // string
    field_e_ezsigntemplatesignature_dependencyrequirement_t *e_ezsigntemplatesignature_dependencyrequirement; // custom
    char *s_ezsigntemplatesignature_positioningpattern; // string
    int i_ezsigntemplatesignature_positioningoffsetx; //numeric
    int i_ezsigntemplatesignature_positioningoffsety; //numeric
    field_e_ezsigntemplatesignature_positioningoccurence_t *e_ezsigntemplatesignature_positioningoccurence; // custom
    int b_ezsigntemplatesignature_customdate; //boolean
    list_t *a_obj_ezsigntemplatesignaturecustomdate; //nonprimitive container
    list_t *a_obj_ezsigntemplateelementdependency; //nonprimitive container

} ezsigntemplatesignature_response_compound_v3_t;

ezsigntemplatesignature_response_compound_v3_t *ezsigntemplatesignature_response_compound_v3_create(
    int pki_ezsigntemplatesignature_id,
    int fki_ezsigntemplatedocument_id,
    int fki_ezsigntemplatesigner_id,
    int fki_ezsigntemplatesigner_id_validation,
    int b_ezsigntemplatesignature_handwritten,
    int b_ezsigntemplatesignature_reason,
    field_e_ezsigntemplatesignature_positioning_t *e_ezsigntemplatesignature_positioning,
    int i_ezsigntemplatedocumentpage_pagenumber,
    int i_ezsigntemplatesignature_x,
    int i_ezsigntemplatesignature_y,
    int i_ezsigntemplatesignature_width,
    int i_ezsigntemplatesignature_height,
    int i_ezsigntemplatesignature_step,
    field_e_ezsigntemplatesignature_type_t *e_ezsigntemplatesignature_type,
    field_e_ezsigntemplatesignature_consultationtrigger_t *e_ezsigntemplatesignature_consultationtrigger,
    char *t_ezsigntemplatesignature_tooltip,
    field_e_ezsigntemplatesignature_tooltipposition_t *e_ezsigntemplatesignature_tooltipposition,
    field_e_ezsigntemplatesignature_font_t *e_ezsigntemplatesignature_font,
    int i_ezsigntemplatesignature_validationstep,
    char *s_ezsigntemplatesignature_attachmentdescription,
    field_e_ezsigntemplatesignature_attachmentnamesource_t *e_ezsigntemplatesignature_attachmentnamesource,
    int b_ezsigntemplatesignature_required,
    int i_ezsigntemplatesignature_maxlength,
    char *s_ezsigntemplatesignature_defaultvalue,
    char *s_ezsigntemplatesignature_regexp,
    enum_textvalidation_t *e_ezsigntemplatesignature_textvalidation,
    char *s_ezsigntemplatesignature_textvalidationcustommessage,
    field_e_ezsigntemplatesignature_dependencyrequirement_t *e_ezsigntemplatesignature_dependencyrequirement,
    char *s_ezsigntemplatesignature_positioningpattern,
    int i_ezsigntemplatesignature_positioningoffsetx,
    int i_ezsigntemplatesignature_positioningoffsety,
    field_e_ezsigntemplatesignature_positioningoccurence_t *e_ezsigntemplatesignature_positioningoccurence,
    int b_ezsigntemplatesignature_customdate,
    list_t *a_obj_ezsigntemplatesignaturecustomdate,
    list_t *a_obj_ezsigntemplateelementdependency
);

void ezsigntemplatesignature_response_compound_v3_free(ezsigntemplatesignature_response_compound_v3_t *ezsigntemplatesignature_response_compound_v3);

ezsigntemplatesignature_response_compound_v3_t *ezsigntemplatesignature_response_compound_v3_parseFromJSON(cJSON *ezsigntemplatesignature_response_compound_v3JSON);

cJSON *ezsigntemplatesignature_response_compound_v3_convertToJSON(ezsigntemplatesignature_response_compound_v3_t *ezsigntemplatesignature_response_compound_v3);

#endif /* _ezsigntemplatesignature_response_compound_v3_H_ */

