/*
 * ezsignformfieldgroup_get_object_v1_response_m_payload.h
 *
 * Payload for GET /1/object/ezsignformfieldgroup/{pkiEzsignformfieldgroupID}
 */

#ifndef _ezsignformfieldgroup_get_object_v1_response_m_payload_H_
#define _ezsignformfieldgroup_get_object_v1_response_m_payload_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct ezsignformfieldgroup_get_object_v1_response_m_payload_t ezsignformfieldgroup_get_object_v1_response_m_payload_t;

#include "custom_dropdown_element_response_compound.h"
#include "ezsignformfield_response_compound.h"
#include "ezsignformfieldgroup_response_compound.h"
#include "ezsignformfieldgroupsigner_response_compound.h"
#include "field_e_ezsignformfieldgroup_signerrequirement.h"
#include "field_e_ezsignformfieldgroup_tooltipposition.h"
#include "field_e_ezsignformfieldgroup_type.h"

// Enum  for ezsignformfieldgroup_get_object_v1_response_m_payload

typedef enum  { ezmax_api_definition__full_ezsignformfieldgroup_get_object_v1_response_m_payload__NULL = 0, ezmax_api_definition__full_ezsignformfieldgroup_get_object_v1_response_m_payload__Text, ezmax_api_definition__full_ezsignformfieldgroup_get_object_v1_response_m_payload__Textarea, ezmax_api_definition__full_ezsignformfieldgroup_get_object_v1_response_m_payload__Dropdown, ezmax_api_definition__full_ezsignformfieldgroup_get_object_v1_response_m_payload__Radio, ezmax_api_definition__full_ezsignformfieldgroup_get_object_v1_response_m_payload__Checkbox } ezmax_api_definition__full_ezsignformfieldgroup_get_object_v1_response_m_payload__e;

char* ezsignformfieldgroup_get_object_v1_response_m_payload_e_ezsignformfieldgroup_type_ToString(ezmax_api_definition__full_ezsignformfieldgroup_get_object_v1_response_m_payload__e e_ezsignformfieldgroup_type);

ezmax_api_definition__full_ezsignformfieldgroup_get_object_v1_response_m_payload__e ezsignformfieldgroup_get_object_v1_response_m_payload_e_ezsignformfieldgroup_type_FromString(char* e_ezsignformfieldgroup_type);

// Enum  for ezsignformfieldgroup_get_object_v1_response_m_payload

typedef enum  { ezmax_api_definition__full_ezsignformfieldgroup_get_object_v1_response_m_payload__NULL = 0, ezmax_api_definition__full_ezsignformfieldgroup_get_object_v1_response_m_payload__All, ezmax_api_definition__full_ezsignformfieldgroup_get_object_v1_response_m_payload__One } ezmax_api_definition__full_ezsignformfieldgroup_get_object_v1_response_m_payload__e;

char* ezsignformfieldgroup_get_object_v1_response_m_payload_e_ezsignformfieldgroup_signerrequirement_ToString(ezmax_api_definition__full_ezsignformfieldgroup_get_object_v1_response_m_payload__e e_ezsignformfieldgroup_signerrequirement);

ezmax_api_definition__full_ezsignformfieldgroup_get_object_v1_response_m_payload__e ezsignformfieldgroup_get_object_v1_response_m_payload_e_ezsignformfieldgroup_signerrequirement_FromString(char* e_ezsignformfieldgroup_signerrequirement);

// Enum  for ezsignformfieldgroup_get_object_v1_response_m_payload

typedef enum  { ezmax_api_definition__full_ezsignformfieldgroup_get_object_v1_response_m_payload__NULL = 0, ezmax_api_definition__full_ezsignformfieldgroup_get_object_v1_response_m_payload__TopLeft, ezmax_api_definition__full_ezsignformfieldgroup_get_object_v1_response_m_payload__TopCenter, ezmax_api_definition__full_ezsignformfieldgroup_get_object_v1_response_m_payload__TopRight, ezmax_api_definition__full_ezsignformfieldgroup_get_object_v1_response_m_payload__MiddleLeft, ezmax_api_definition__full_ezsignformfieldgroup_get_object_v1_response_m_payload__MiddleRight, ezmax_api_definition__full_ezsignformfieldgroup_get_object_v1_response_m_payload__BottomLeft, ezmax_api_definition__full_ezsignformfieldgroup_get_object_v1_response_m_payload__BottomCenter, ezmax_api_definition__full_ezsignformfieldgroup_get_object_v1_response_m_payload__BottomRight } ezmax_api_definition__full_ezsignformfieldgroup_get_object_v1_response_m_payload__e;

char* ezsignformfieldgroup_get_object_v1_response_m_payload_e_ezsignformfieldgroup_tooltipposition_ToString(ezmax_api_definition__full_ezsignformfieldgroup_get_object_v1_response_m_payload__e e_ezsignformfieldgroup_tooltipposition);

ezmax_api_definition__full_ezsignformfieldgroup_get_object_v1_response_m_payload__e ezsignformfieldgroup_get_object_v1_response_m_payload_e_ezsignformfieldgroup_tooltipposition_FromString(char* e_ezsignformfieldgroup_tooltipposition);



typedef struct ezsignformfieldgroup_get_object_v1_response_m_payload_t {
    int pki_ezsignformfieldgroup_id; //numeric
    int fki_ezsigndocument_id; //numeric
    field_e_ezsignformfieldgroup_type_t *e_ezsignformfieldgroup_type; // custom
    field_e_ezsignformfieldgroup_signerrequirement_t *e_ezsignformfieldgroup_signerrequirement; // custom
    char *s_ezsignformfieldgroup_label; // string
    int i_ezsignformfieldgroup_step; //numeric
    char *s_ezsignformfieldgroup_defaultvalue; // string
    int i_ezsignformfieldgroup_filledmin; //numeric
    int i_ezsignformfieldgroup_filledmax; //numeric
    int b_ezsignformfieldgroup_readonly; //boolean
    int i_ezsignformfieldgroup_maxlength; //numeric
    int b_ezsignformfieldgroup_encrypted; //boolean
    char *s_ezsignformfieldgroup_regexp; // string
    char *t_ezsignformfieldgroup_tooltip; // string
    field_e_ezsignformfieldgroup_tooltipposition_t *e_ezsignformfieldgroup_tooltipposition; // custom
    list_t *a_obj_ezsignformfield; //nonprimitive container
    list_t *a_obj_dropdown_element; //nonprimitive container
    list_t *a_obj_ezsignformfieldgroupsigner; //nonprimitive container

} ezsignformfieldgroup_get_object_v1_response_m_payload_t;

ezsignformfieldgroup_get_object_v1_response_m_payload_t *ezsignformfieldgroup_get_object_v1_response_m_payload_create(
    int pki_ezsignformfieldgroup_id,
    int fki_ezsigndocument_id,
    field_e_ezsignformfieldgroup_type_t *e_ezsignformfieldgroup_type,
    field_e_ezsignformfieldgroup_signerrequirement_t *e_ezsignformfieldgroup_signerrequirement,
    char *s_ezsignformfieldgroup_label,
    int i_ezsignformfieldgroup_step,
    char *s_ezsignformfieldgroup_defaultvalue,
    int i_ezsignformfieldgroup_filledmin,
    int i_ezsignformfieldgroup_filledmax,
    int b_ezsignformfieldgroup_readonly,
    int i_ezsignformfieldgroup_maxlength,
    int b_ezsignformfieldgroup_encrypted,
    char *s_ezsignformfieldgroup_regexp,
    char *t_ezsignformfieldgroup_tooltip,
    field_e_ezsignformfieldgroup_tooltipposition_t *e_ezsignformfieldgroup_tooltipposition,
    list_t *a_obj_ezsignformfield,
    list_t *a_obj_dropdown_element,
    list_t *a_obj_ezsignformfieldgroupsigner
);

void ezsignformfieldgroup_get_object_v1_response_m_payload_free(ezsignformfieldgroup_get_object_v1_response_m_payload_t *ezsignformfieldgroup_get_object_v1_response_m_payload);

ezsignformfieldgroup_get_object_v1_response_m_payload_t *ezsignformfieldgroup_get_object_v1_response_m_payload_parseFromJSON(cJSON *ezsignformfieldgroup_get_object_v1_response_m_payloadJSON);

cJSON *ezsignformfieldgroup_get_object_v1_response_m_payload_convertToJSON(ezsignformfieldgroup_get_object_v1_response_m_payload_t *ezsignformfieldgroup_get_object_v1_response_m_payload);

#endif /* _ezsignformfieldgroup_get_object_v1_response_m_payload_H_ */

