/*
 * ezsignfoldersignerassociation_get_in_person_login_url_v1_response_m_payload.h
 *
 * Payload for GET /1/object/ezsignfoldersignerassociation/getInPersonLoginUrl
 */

#ifndef _ezsignfoldersignerassociation_get_in_person_login_url_v1_response_m_payload_H_
#define _ezsignfoldersignerassociation_get_in_person_login_url_v1_response_m_payload_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct ezsignfoldersignerassociation_get_in_person_login_url_v1_response_m_payload_t ezsignfoldersignerassociation_get_in_person_login_url_v1_response_m_payload_t;




typedef struct ezsignfoldersignerassociation_get_in_person_login_url_v1_response_m_payload_t {
    char *s_login_url; // string

} ezsignfoldersignerassociation_get_in_person_login_url_v1_response_m_payload_t;

ezsignfoldersignerassociation_get_in_person_login_url_v1_response_m_payload_t *ezsignfoldersignerassociation_get_in_person_login_url_v1_response_m_payload_create(
    char *s_login_url
);

void ezsignfoldersignerassociation_get_in_person_login_url_v1_response_m_payload_free(ezsignfoldersignerassociation_get_in_person_login_url_v1_response_m_payload_t *ezsignfoldersignerassociation_get_in_person_login_url_v1_response_m_payload);

ezsignfoldersignerassociation_get_in_person_login_url_v1_response_m_payload_t *ezsignfoldersignerassociation_get_in_person_login_url_v1_response_m_payload_parseFromJSON(cJSON *ezsignfoldersignerassociation_get_in_person_login_url_v1_response_m_payloadJSON);

cJSON *ezsignfoldersignerassociation_get_in_person_login_url_v1_response_m_payload_convertToJSON(ezsignfoldersignerassociation_get_in_person_login_url_v1_response_m_payload_t *ezsignfoldersignerassociation_get_in_person_login_url_v1_response_m_payload);

#endif /* _ezsignfoldersignerassociation_get_in_person_login_url_v1_response_m_payload_H_ */

