/*
 * ezsigntemplatepackagemembership_create_object_v1_response_all_of.h
 *
 * 
 */

#ifndef _ezsigntemplatepackagemembership_create_object_v1_response_all_of_H_
#define _ezsigntemplatepackagemembership_create_object_v1_response_all_of_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct ezsigntemplatepackagemembership_create_object_v1_response_all_of_t ezsigntemplatepackagemembership_create_object_v1_response_all_of_t;

#include "ezsigntemplatepackagemembership_create_object_v1_response_m_payload.h"



typedef struct ezsigntemplatepackagemembership_create_object_v1_response_all_of_t {
    struct ezsigntemplatepackagemembership_create_object_v1_response_m_payload_t *m_payload; //model

} ezsigntemplatepackagemembership_create_object_v1_response_all_of_t;

ezsigntemplatepackagemembership_create_object_v1_response_all_of_t *ezsigntemplatepackagemembership_create_object_v1_response_all_of_create(
    ezsigntemplatepackagemembership_create_object_v1_response_m_payload_t *m_payload
);

void ezsigntemplatepackagemembership_create_object_v1_response_all_of_free(ezsigntemplatepackagemembership_create_object_v1_response_all_of_t *ezsigntemplatepackagemembership_create_object_v1_response_all_of);

ezsigntemplatepackagemembership_create_object_v1_response_all_of_t *ezsigntemplatepackagemembership_create_object_v1_response_all_of_parseFromJSON(cJSON *ezsigntemplatepackagemembership_create_object_v1_response_all_ofJSON);

cJSON *ezsigntemplatepackagemembership_create_object_v1_response_all_of_convertToJSON(ezsigntemplatepackagemembership_create_object_v1_response_all_of_t *ezsigntemplatepackagemembership_create_object_v1_response_all_of);

#endif /* _ezsigntemplatepackagemembership_create_object_v1_response_all_of_H_ */

