/*
 * ezsigntemplatepackagesignermembership_create_object_v1_response_all_of.h
 *
 * 
 */

#ifndef _ezsigntemplatepackagesignermembership_create_object_v1_response_all_of_H_
#define _ezsigntemplatepackagesignermembership_create_object_v1_response_all_of_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct ezsigntemplatepackagesignermembership_create_object_v1_response_all_of_t ezsigntemplatepackagesignermembership_create_object_v1_response_all_of_t;

#include "ezsigntemplatepackagesignermembership_create_object_v1_response_m_payload.h"



typedef struct ezsigntemplatepackagesignermembership_create_object_v1_response_all_of_t {
    struct ezsigntemplatepackagesignermembership_create_object_v1_response_m_payload_t *m_payload; //model

} ezsigntemplatepackagesignermembership_create_object_v1_response_all_of_t;

ezsigntemplatepackagesignermembership_create_object_v1_response_all_of_t *ezsigntemplatepackagesignermembership_create_object_v1_response_all_of_create(
    ezsigntemplatepackagesignermembership_create_object_v1_response_m_payload_t *m_payload
);

void ezsigntemplatepackagesignermembership_create_object_v1_response_all_of_free(ezsigntemplatepackagesignermembership_create_object_v1_response_all_of_t *ezsigntemplatepackagesignermembership_create_object_v1_response_all_of);

ezsigntemplatepackagesignermembership_create_object_v1_response_all_of_t *ezsigntemplatepackagesignermembership_create_object_v1_response_all_of_parseFromJSON(cJSON *ezsigntemplatepackagesignermembership_create_object_v1_response_all_ofJSON);

cJSON *ezsigntemplatepackagesignermembership_create_object_v1_response_all_of_convertToJSON(ezsigntemplatepackagesignermembership_create_object_v1_response_all_of_t *ezsigntemplatepackagesignermembership_create_object_v1_response_all_of);

#endif /* _ezsigntemplatepackagesignermembership_create_object_v1_response_all_of_H_ */

