/*
 * ezsignsignergroup_edit_ezsignsignergroupmemberships_v1_response_m_payload.h
 *
 * Response for PUT /1/object/ezsignsignergroup/{pkiEzsignsignergroupID}/editEzsignsignergroupmemberships
 */

#ifndef _ezsignsignergroup_edit_ezsignsignergroupmemberships_v1_response_m_payload_H_
#define _ezsignsignergroup_edit_ezsignsignergroupmemberships_v1_response_m_payload_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct ezsignsignergroup_edit_ezsignsignergroupmemberships_v1_response_m_payload_t ezsignsignergroup_edit_ezsignsignergroupmemberships_v1_response_m_payload_t;




typedef struct ezsignsignergroup_edit_ezsignsignergroupmemberships_v1_response_m_payload_t {
    list_t *a_pki_ezsignsignergroupmembership_id; //primitive container

} ezsignsignergroup_edit_ezsignsignergroupmemberships_v1_response_m_payload_t;

ezsignsignergroup_edit_ezsignsignergroupmemberships_v1_response_m_payload_t *ezsignsignergroup_edit_ezsignsignergroupmemberships_v1_response_m_payload_create(
    list_t *a_pki_ezsignsignergroupmembership_id
);

void ezsignsignergroup_edit_ezsignsignergroupmemberships_v1_response_m_payload_free(ezsignsignergroup_edit_ezsignsignergroupmemberships_v1_response_m_payload_t *ezsignsignergroup_edit_ezsignsignergroupmemberships_v1_response_m_payload);

ezsignsignergroup_edit_ezsignsignergroupmemberships_v1_response_m_payload_t *ezsignsignergroup_edit_ezsignsignergroupmemberships_v1_response_m_payload_parseFromJSON(cJSON *ezsignsignergroup_edit_ezsignsignergroupmemberships_v1_response_m_payloadJSON);

cJSON *ezsignsignergroup_edit_ezsignsignergroupmemberships_v1_response_m_payload_convertToJSON(ezsignsignergroup_edit_ezsignsignergroupmemberships_v1_response_m_payload_t *ezsignsignergroup_edit_ezsignsignergroupmemberships_v1_response_m_payload);

#endif /* _ezsignsignergroup_edit_ezsignsignergroupmemberships_v1_response_m_payload_H_ */

