/*
 * ezsignbulksendtransmission_get_ezsignsignatures_automatic_v1_response_all_of.h
 *
 * 
 */

#ifndef _ezsignbulksendtransmission_get_ezsignsignatures_automatic_v1_response_all_of_H_
#define _ezsignbulksendtransmission_get_ezsignsignatures_automatic_v1_response_all_of_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct ezsignbulksendtransmission_get_ezsignsignatures_automatic_v1_response_all_of_t ezsignbulksendtransmission_get_ezsignsignatures_automatic_v1_response_all_of_t;

#include "ezsignbulksendtransmission_get_ezsignsignatures_automatic_v1_response_m_payload.h"



typedef struct ezsignbulksendtransmission_get_ezsignsignatures_automatic_v1_response_all_of_t {
    struct ezsignbulksendtransmission_get_ezsignsignatures_automatic_v1_response_m_payload_t *m_payload; //model

} ezsignbulksendtransmission_get_ezsignsignatures_automatic_v1_response_all_of_t;

ezsignbulksendtransmission_get_ezsignsignatures_automatic_v1_response_all_of_t *ezsignbulksendtransmission_get_ezsignsignatures_automatic_v1_response_all_of_create(
    ezsignbulksendtransmission_get_ezsignsignatures_automatic_v1_response_m_payload_t *m_payload
);

void ezsignbulksendtransmission_get_ezsignsignatures_automatic_v1_response_all_of_free(ezsignbulksendtransmission_get_ezsignsignatures_automatic_v1_response_all_of_t *ezsignbulksendtransmission_get_ezsignsignatures_automatic_v1_response_all_of);

ezsignbulksendtransmission_get_ezsignsignatures_automatic_v1_response_all_of_t *ezsignbulksendtransmission_get_ezsignsignatures_automatic_v1_response_all_of_parseFromJSON(cJSON *ezsignbulksendtransmission_get_ezsignsignatures_automatic_v1_response_all_ofJSON);

cJSON *ezsignbulksendtransmission_get_ezsignsignatures_automatic_v1_response_all_of_convertToJSON(ezsignbulksendtransmission_get_ezsignsignatures_automatic_v1_response_all_of_t *ezsignbulksendtransmission_get_ezsignsignatures_automatic_v1_response_all_of);

#endif /* _ezsignbulksendtransmission_get_ezsignsignatures_automatic_v1_response_all_of_H_ */

