/*
 * ezsigntemplateformfieldgroup_get_object_v1_response_m_payload.h
 *
 * Payload for GET /1/object/ezsigntemplateformfieldgroup/{pkiEzsigntemplateformfieldgroupID}
 */

#ifndef _ezsigntemplateformfieldgroup_get_object_v1_response_m_payload_H_
#define _ezsigntemplateformfieldgroup_get_object_v1_response_m_payload_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct ezsigntemplateformfieldgroup_get_object_v1_response_m_payload_t ezsigntemplateformfieldgroup_get_object_v1_response_m_payload_t;

#include "custom_dropdown_element_response_compound.h"
#include "ezsigntemplateformfield_response_compound.h"
#include "ezsigntemplateformfieldgroupsigner_response_compound.h"
#include "field_e_ezsigntemplateformfieldgroup_signerrequirement.h"
#include "field_e_ezsigntemplateformfieldgroup_tooltipposition.h"
#include "field_e_ezsigntemplateformfieldgroup_type.h"

// Enum  for ezsigntemplateformfieldgroup_get_object_v1_response_m_payload

typedef enum  { ezmax_api_definition__full_ezsigntemplateformfieldgroup_get_object_v1_response_m_payload__NULL = 0, ezmax_api_definition__full_ezsigntemplateformfieldgroup_get_object_v1_response_m_payload__Text, ezmax_api_definition__full_ezsigntemplateformfieldgroup_get_object_v1_response_m_payload__Textarea, ezmax_api_definition__full_ezsigntemplateformfieldgroup_get_object_v1_response_m_payload__Dropdown, ezmax_api_definition__full_ezsigntemplateformfieldgroup_get_object_v1_response_m_payload__Radio, ezmax_api_definition__full_ezsigntemplateformfieldgroup_get_object_v1_response_m_payload__Checkbox } ezmax_api_definition__full_ezsigntemplateformfieldgroup_get_object_v1_response_m_payload__e;

char* ezsigntemplateformfieldgroup_get_object_v1_response_m_payload_e_ezsigntemplateformfieldgroup_type_ToString(ezmax_api_definition__full_ezsigntemplateformfieldgroup_get_object_v1_response_m_payload__e e_ezsigntemplateformfieldgroup_type);

ezmax_api_definition__full_ezsigntemplateformfieldgroup_get_object_v1_response_m_payload__e ezsigntemplateformfieldgroup_get_object_v1_response_m_payload_e_ezsigntemplateformfieldgroup_type_FromString(char* e_ezsigntemplateformfieldgroup_type);

// Enum  for ezsigntemplateformfieldgroup_get_object_v1_response_m_payload

typedef enum  { ezmax_api_definition__full_ezsigntemplateformfieldgroup_get_object_v1_response_m_payload__NULL = 0, ezmax_api_definition__full_ezsigntemplateformfieldgroup_get_object_v1_response_m_payload__All, ezmax_api_definition__full_ezsigntemplateformfieldgroup_get_object_v1_response_m_payload__One } ezmax_api_definition__full_ezsigntemplateformfieldgroup_get_object_v1_response_m_payload__e;

char* ezsigntemplateformfieldgroup_get_object_v1_response_m_payload_e_ezsigntemplateformfieldgroup_signerrequirement_ToString(ezmax_api_definition__full_ezsigntemplateformfieldgroup_get_object_v1_response_m_payload__e e_ezsigntemplateformfieldgroup_signerrequirement);

ezmax_api_definition__full_ezsigntemplateformfieldgroup_get_object_v1_response_m_payload__e ezsigntemplateformfieldgroup_get_object_v1_response_m_payload_e_ezsigntemplateformfieldgroup_signerrequirement_FromString(char* e_ezsigntemplateformfieldgroup_signerrequirement);

// Enum  for ezsigntemplateformfieldgroup_get_object_v1_response_m_payload

typedef enum  { ezmax_api_definition__full_ezsigntemplateformfieldgroup_get_object_v1_response_m_payload__NULL = 0, ezmax_api_definition__full_ezsigntemplateformfieldgroup_get_object_v1_response_m_payload__TopLeft, ezmax_api_definition__full_ezsigntemplateformfieldgroup_get_object_v1_response_m_payload__TopCenter, ezmax_api_definition__full_ezsigntemplateformfieldgroup_get_object_v1_response_m_payload__TopRight, ezmax_api_definition__full_ezsigntemplateformfieldgroup_get_object_v1_response_m_payload__MiddleLeft, ezmax_api_definition__full_ezsigntemplateformfieldgroup_get_object_v1_response_m_payload__MiddleRight, ezmax_api_definition__full_ezsigntemplateformfieldgroup_get_object_v1_response_m_payload__BottomLeft, ezmax_api_definition__full_ezsigntemplateformfieldgroup_get_object_v1_response_m_payload__BottomCenter, ezmax_api_definition__full_ezsigntemplateformfieldgroup_get_object_v1_response_m_payload__BottomRight } ezmax_api_definition__full_ezsigntemplateformfieldgroup_get_object_v1_response_m_payload__e;

char* ezsigntemplateformfieldgroup_get_object_v1_response_m_payload_e_ezsigntemplateformfieldgroup_tooltipposition_ToString(ezmax_api_definition__full_ezsigntemplateformfieldgroup_get_object_v1_response_m_payload__e e_ezsigntemplateformfieldgroup_tooltipposition);

ezmax_api_definition__full_ezsigntemplateformfieldgroup_get_object_v1_response_m_payload__e ezsigntemplateformfieldgroup_get_object_v1_response_m_payload_e_ezsigntemplateformfieldgroup_tooltipposition_FromString(char* e_ezsigntemplateformfieldgroup_tooltipposition);



typedef struct ezsigntemplateformfieldgroup_get_object_v1_response_m_payload_t {
    int pki_ezsigntemplateformfieldgroup_id; //numeric
    int fki_ezsigntemplatedocument_id; //numeric
    field_e_ezsigntemplateformfieldgroup_type_t *e_ezsigntemplateformfieldgroup_type; // custom
    field_e_ezsigntemplateformfieldgroup_signerrequirement_t *e_ezsigntemplateformfieldgroup_signerrequirement; // custom
    char *s_ezsigntemplateformfieldgroup_label; // string
    int i_ezsigntemplateformfieldgroup_step; //numeric
    char *s_ezsigntemplateformfieldgroup_defaultvalue; // string
    int i_ezsigntemplateformfieldgroup_filledmin; //numeric
    int i_ezsigntemplateformfieldgroup_filledmax; //numeric
    int b_ezsigntemplateformfieldgroup_readonly; //boolean
    int i_ezsigntemplateformfieldgroup_maxlength; //numeric
    int b_ezsigntemplateformfieldgroup_encrypted; //boolean
    char *s_ezsigntemplateformfieldgroup_regexp; // string
    char *t_ezsigntemplateformfieldgroup_tooltip; // string
    field_e_ezsigntemplateformfieldgroup_tooltipposition_t *e_ezsigntemplateformfieldgroup_tooltipposition; // custom
    list_t *a_obj_ezsigntemplateformfieldgroupsigner; //nonprimitive container
    list_t *a_obj_dropdown_element; //nonprimitive container
    list_t *a_obj_ezsigntemplateformfield; //nonprimitive container

} ezsigntemplateformfieldgroup_get_object_v1_response_m_payload_t;

ezsigntemplateformfieldgroup_get_object_v1_response_m_payload_t *ezsigntemplateformfieldgroup_get_object_v1_response_m_payload_create(
    int pki_ezsigntemplateformfieldgroup_id,
    int fki_ezsigntemplatedocument_id,
    field_e_ezsigntemplateformfieldgroup_type_t *e_ezsigntemplateformfieldgroup_type,
    field_e_ezsigntemplateformfieldgroup_signerrequirement_t *e_ezsigntemplateformfieldgroup_signerrequirement,
    char *s_ezsigntemplateformfieldgroup_label,
    int i_ezsigntemplateformfieldgroup_step,
    char *s_ezsigntemplateformfieldgroup_defaultvalue,
    int i_ezsigntemplateformfieldgroup_filledmin,
    int i_ezsigntemplateformfieldgroup_filledmax,
    int b_ezsigntemplateformfieldgroup_readonly,
    int i_ezsigntemplateformfieldgroup_maxlength,
    int b_ezsigntemplateformfieldgroup_encrypted,
    char *s_ezsigntemplateformfieldgroup_regexp,
    char *t_ezsigntemplateformfieldgroup_tooltip,
    field_e_ezsigntemplateformfieldgroup_tooltipposition_t *e_ezsigntemplateformfieldgroup_tooltipposition,
    list_t *a_obj_ezsigntemplateformfieldgroupsigner,
    list_t *a_obj_dropdown_element,
    list_t *a_obj_ezsigntemplateformfield
);

void ezsigntemplateformfieldgroup_get_object_v1_response_m_payload_free(ezsigntemplateformfieldgroup_get_object_v1_response_m_payload_t *ezsigntemplateformfieldgroup_get_object_v1_response_m_payload);

ezsigntemplateformfieldgroup_get_object_v1_response_m_payload_t *ezsigntemplateformfieldgroup_get_object_v1_response_m_payload_parseFromJSON(cJSON *ezsigntemplateformfieldgroup_get_object_v1_response_m_payloadJSON);

cJSON *ezsigntemplateformfieldgroup_get_object_v1_response_m_payload_convertToJSON(ezsigntemplateformfieldgroup_get_object_v1_response_m_payload_t *ezsigntemplateformfieldgroup_get_object_v1_response_m_payload);

#endif /* _ezsigntemplateformfieldgroup_get_object_v1_response_m_payload_H_ */

