/*
 * ezsignfoldersignerassociation_create_object_v1_response_all_of.h
 *
 * 
 */

#ifndef _ezsignfoldersignerassociation_create_object_v1_response_all_of_H_
#define _ezsignfoldersignerassociation_create_object_v1_response_all_of_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct ezsignfoldersignerassociation_create_object_v1_response_all_of_t ezsignfoldersignerassociation_create_object_v1_response_all_of_t;

#include "ezsignfoldersignerassociation_create_object_v1_response_m_payload.h"



typedef struct ezsignfoldersignerassociation_create_object_v1_response_all_of_t {
    struct ezsignfoldersignerassociation_create_object_v1_response_m_payload_t *m_payload; //model

} ezsignfoldersignerassociation_create_object_v1_response_all_of_t;

ezsignfoldersignerassociation_create_object_v1_response_all_of_t *ezsignfoldersignerassociation_create_object_v1_response_all_of_create(
    ezsignfoldersignerassociation_create_object_v1_response_m_payload_t *m_payload
);

void ezsignfoldersignerassociation_create_object_v1_response_all_of_free(ezsignfoldersignerassociation_create_object_v1_response_all_of_t *ezsignfoldersignerassociation_create_object_v1_response_all_of);

ezsignfoldersignerassociation_create_object_v1_response_all_of_t *ezsignfoldersignerassociation_create_object_v1_response_all_of_parseFromJSON(cJSON *ezsignfoldersignerassociation_create_object_v1_response_all_ofJSON);

cJSON *ezsignfoldersignerassociation_create_object_v1_response_all_of_convertToJSON(ezsignfoldersignerassociation_create_object_v1_response_all_of_t *ezsignfoldersignerassociation_create_object_v1_response_all_of);

#endif /* _ezsignfoldersignerassociation_create_object_v1_response_all_of_H_ */

