/*
 * ezsigntemplatepackagesignermembership_create_object_v1_response_m_payload.h
 *
 * Payload for POST /1/object/ezsigntemplatepackagesignermembership
 */

#ifndef _ezsigntemplatepackagesignermembership_create_object_v1_response_m_payload_H_
#define _ezsigntemplatepackagesignermembership_create_object_v1_response_m_payload_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct ezsigntemplatepackagesignermembership_create_object_v1_response_m_payload_t ezsigntemplatepackagesignermembership_create_object_v1_response_m_payload_t;




typedef struct ezsigntemplatepackagesignermembership_create_object_v1_response_m_payload_t {
    list_t *a_pki_ezsigntemplatepackagesignermembership_id; //primitive container

    int _library_owned; // Is the library responsible for freeing this object?
} ezsigntemplatepackagesignermembership_create_object_v1_response_m_payload_t;

__attribute__((deprecated)) ezsigntemplatepackagesignermembership_create_object_v1_response_m_payload_t *ezsigntemplatepackagesignermembership_create_object_v1_response_m_payload_create(
    list_t *a_pki_ezsigntemplatepackagesignermembership_id
);

void ezsigntemplatepackagesignermembership_create_object_v1_response_m_payload_free(ezsigntemplatepackagesignermembership_create_object_v1_response_m_payload_t *ezsigntemplatepackagesignermembership_create_object_v1_response_m_payload);

ezsigntemplatepackagesignermembership_create_object_v1_response_m_payload_t *ezsigntemplatepackagesignermembership_create_object_v1_response_m_payload_parseFromJSON(cJSON *ezsigntemplatepackagesignermembership_create_object_v1_response_m_payloadJSON);

cJSON *ezsigntemplatepackagesignermembership_create_object_v1_response_m_payload_convertToJSON(ezsigntemplatepackagesignermembership_create_object_v1_response_m_payload_t *ezsigntemplatepackagesignermembership_create_object_v1_response_m_payload);

#endif /* _ezsigntemplatepackagesignermembership_create_object_v1_response_m_payload_H_ */

