/*
 * ezsigntemplateformfieldgroup_get_object_v2_response_all_of.h
 *
 * 
 */

#ifndef _ezsigntemplateformfieldgroup_get_object_v2_response_all_of_H_
#define _ezsigntemplateformfieldgroup_get_object_v2_response_all_of_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct ezsigntemplateformfieldgroup_get_object_v2_response_all_of_t ezsigntemplateformfieldgroup_get_object_v2_response_all_of_t;

#include "ezsigntemplateformfieldgroup_get_object_v2_response_m_payload.h"



typedef struct ezsigntemplateformfieldgroup_get_object_v2_response_all_of_t {
    struct ezsigntemplateformfieldgroup_get_object_v2_response_m_payload_t *m_payload; //model

} ezsigntemplateformfieldgroup_get_object_v2_response_all_of_t;

ezsigntemplateformfieldgroup_get_object_v2_response_all_of_t *ezsigntemplateformfieldgroup_get_object_v2_response_all_of_create(
    ezsigntemplateformfieldgroup_get_object_v2_response_m_payload_t *m_payload
);

void ezsigntemplateformfieldgroup_get_object_v2_response_all_of_free(ezsigntemplateformfieldgroup_get_object_v2_response_all_of_t *ezsigntemplateformfieldgroup_get_object_v2_response_all_of);

ezsigntemplateformfieldgroup_get_object_v2_response_all_of_t *ezsigntemplateformfieldgroup_get_object_v2_response_all_of_parseFromJSON(cJSON *ezsigntemplateformfieldgroup_get_object_v2_response_all_ofJSON);

cJSON *ezsigntemplateformfieldgroup_get_object_v2_response_all_of_convertToJSON(ezsigntemplateformfieldgroup_get_object_v2_response_all_of_t *ezsigntemplateformfieldgroup_get_object_v2_response_all_of);

#endif /* _ezsigntemplateformfieldgroup_get_object_v2_response_all_of_H_ */

