/*
 * ezsignbulksendsignermapping_get_object_v2_response_all_of.h
 *
 * 
 */

#ifndef _ezsignbulksendsignermapping_get_object_v2_response_all_of_H_
#define _ezsignbulksendsignermapping_get_object_v2_response_all_of_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct ezsignbulksendsignermapping_get_object_v2_response_all_of_t ezsignbulksendsignermapping_get_object_v2_response_all_of_t;

#include "ezsignbulksendsignermapping_get_object_v2_response_m_payload.h"



typedef struct ezsignbulksendsignermapping_get_object_v2_response_all_of_t {
    struct ezsignbulksendsignermapping_get_object_v2_response_m_payload_t *m_payload; //model

} ezsignbulksendsignermapping_get_object_v2_response_all_of_t;

ezsignbulksendsignermapping_get_object_v2_response_all_of_t *ezsignbulksendsignermapping_get_object_v2_response_all_of_create(
    ezsignbulksendsignermapping_get_object_v2_response_m_payload_t *m_payload
);

void ezsignbulksendsignermapping_get_object_v2_response_all_of_free(ezsignbulksendsignermapping_get_object_v2_response_all_of_t *ezsignbulksendsignermapping_get_object_v2_response_all_of);

ezsignbulksendsignermapping_get_object_v2_response_all_of_t *ezsignbulksendsignermapping_get_object_v2_response_all_of_parseFromJSON(cJSON *ezsignbulksendsignermapping_get_object_v2_response_all_ofJSON);

cJSON *ezsignbulksendsignermapping_get_object_v2_response_all_of_convertToJSON(ezsignbulksendsignermapping_get_object_v2_response_all_of_t *ezsignbulksendsignermapping_get_object_v2_response_all_of);

#endif /* _ezsignbulksendsignermapping_get_object_v2_response_all_of_H_ */

