/*
 * ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v1_response_all_of.h
 *
 * 
 */

#ifndef _ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v1_response_all_of_H_
#define _ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v1_response_all_of_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v1_response_all_of_t ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v1_response_all_of_t;

#include "ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v1_response_m_payload.h"



typedef struct ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v1_response_all_of_t {
    struct ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v1_response_m_payload_t *m_payload; //model

} ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v1_response_all_of_t;

ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v1_response_all_of_t *ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v1_response_all_of_create(
    ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v1_response_m_payload_t *m_payload
);

void ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v1_response_all_of_free(ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v1_response_all_of_t *ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v1_response_all_of);

ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v1_response_all_of_t *ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v1_response_all_of_parseFromJSON(cJSON *ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v1_response_all_ofJSON);

cJSON *ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v1_response_all_of_convertToJSON(ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v1_response_all_of_t *ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v1_response_all_of);

#endif /* _ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v1_response_all_of_H_ */

