/*
 * ezsigntemplatepackagesignermembership_get_object_v1_response_m_payload.h
 *
 * Payload for GET /1/object/ezsigntemplatepackagesignermembership/{pkiEzsigntemplatepackagesignermembershipID}
 */

#ifndef _ezsigntemplatepackagesignermembership_get_object_v1_response_m_payload_H_
#define _ezsigntemplatepackagesignermembership_get_object_v1_response_m_payload_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct ezsigntemplatepackagesignermembership_get_object_v1_response_m_payload_t ezsigntemplatepackagesignermembership_get_object_v1_response_m_payload_t;




typedef struct ezsigntemplatepackagesignermembership_get_object_v1_response_m_payload_t {
    int pki_ezsigntemplatepackagesignermembership_id; //numeric
    int fki_ezsigntemplatepackagemembership_id; //numeric
    int fki_ezsigntemplatepackagesigner_id; //numeric
    int fki_ezsigntemplatesigner_id; //numeric
    int i_ezsigntemplatepackagesignermembership_copy; //numeric

} ezsigntemplatepackagesignermembership_get_object_v1_response_m_payload_t;

ezsigntemplatepackagesignermembership_get_object_v1_response_m_payload_t *ezsigntemplatepackagesignermembership_get_object_v1_response_m_payload_create(
    int pki_ezsigntemplatepackagesignermembership_id,
    int fki_ezsigntemplatepackagemembership_id,
    int fki_ezsigntemplatepackagesigner_id,
    int fki_ezsigntemplatesigner_id,
    int i_ezsigntemplatepackagesignermembership_copy
);

void ezsigntemplatepackagesignermembership_get_object_v1_response_m_payload_free(ezsigntemplatepackagesignermembership_get_object_v1_response_m_payload_t *ezsigntemplatepackagesignermembership_get_object_v1_response_m_payload);

ezsigntemplatepackagesignermembership_get_object_v1_response_m_payload_t *ezsigntemplatepackagesignermembership_get_object_v1_response_m_payload_parseFromJSON(cJSON *ezsigntemplatepackagesignermembership_get_object_v1_response_m_payloadJSON);

cJSON *ezsigntemplatepackagesignermembership_get_object_v1_response_m_payload_convertToJSON(ezsigntemplatepackagesignermembership_get_object_v1_response_m_payload_t *ezsigntemplatepackagesignermembership_get_object_v1_response_m_payload);

#endif /* _ezsigntemplatepackagesignermembership_get_object_v1_response_m_payload_H_ */

