/*
 * ezsignfolder_import_ezsignfoldersignerassociations_v1_response_m_payload.h
 *
 * Payload for POST /1/object/ezsignfolder/{pkiEzsignfolder}/importEzsignfoldersignerassociations
 */

#ifndef _ezsignfolder_import_ezsignfoldersignerassociations_v1_response_m_payload_H_
#define _ezsignfolder_import_ezsignfoldersignerassociations_v1_response_m_payload_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct ezsignfolder_import_ezsignfoldersignerassociations_v1_response_m_payload_t ezsignfolder_import_ezsignfoldersignerassociations_v1_response_m_payload_t;




typedef struct ezsignfolder_import_ezsignfoldersignerassociations_v1_response_m_payload_t {
    list_t *a_pki_ezsignfoldersignerassociation_id; //primitive container

} ezsignfolder_import_ezsignfoldersignerassociations_v1_response_m_payload_t;

ezsignfolder_import_ezsignfoldersignerassociations_v1_response_m_payload_t *ezsignfolder_import_ezsignfoldersignerassociations_v1_response_m_payload_create(
    list_t *a_pki_ezsignfoldersignerassociation_id
);

void ezsignfolder_import_ezsignfoldersignerassociations_v1_response_m_payload_free(ezsignfolder_import_ezsignfoldersignerassociations_v1_response_m_payload_t *ezsignfolder_import_ezsignfoldersignerassociations_v1_response_m_payload);

ezsignfolder_import_ezsignfoldersignerassociations_v1_response_m_payload_t *ezsignfolder_import_ezsignfoldersignerassociations_v1_response_m_payload_parseFromJSON(cJSON *ezsignfolder_import_ezsignfoldersignerassociations_v1_response_m_payloadJSON);

cJSON *ezsignfolder_import_ezsignfoldersignerassociations_v1_response_m_payload_convertToJSON(ezsignfolder_import_ezsignfoldersignerassociations_v1_response_m_payload_t *ezsignfolder_import_ezsignfoldersignerassociations_v1_response_m_payload);

#endif /* _ezsignfolder_import_ezsignfoldersignerassociations_v1_response_m_payload_H_ */

