/*
 * ezsigntemplatepackagesigner_create_object_v1_response_all_of.h
 *
 * 
 */

#ifndef _ezsigntemplatepackagesigner_create_object_v1_response_all_of_H_
#define _ezsigntemplatepackagesigner_create_object_v1_response_all_of_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct ezsigntemplatepackagesigner_create_object_v1_response_all_of_t ezsigntemplatepackagesigner_create_object_v1_response_all_of_t;

#include "ezsigntemplatepackagesigner_create_object_v1_response_m_payload.h"



typedef struct ezsigntemplatepackagesigner_create_object_v1_response_all_of_t {
    struct ezsigntemplatepackagesigner_create_object_v1_response_m_payload_t *m_payload; //model

} ezsigntemplatepackagesigner_create_object_v1_response_all_of_t;

ezsigntemplatepackagesigner_create_object_v1_response_all_of_t *ezsigntemplatepackagesigner_create_object_v1_response_all_of_create(
    ezsigntemplatepackagesigner_create_object_v1_response_m_payload_t *m_payload
);

void ezsigntemplatepackagesigner_create_object_v1_response_all_of_free(ezsigntemplatepackagesigner_create_object_v1_response_all_of_t *ezsigntemplatepackagesigner_create_object_v1_response_all_of);

ezsigntemplatepackagesigner_create_object_v1_response_all_of_t *ezsigntemplatepackagesigner_create_object_v1_response_all_of_parseFromJSON(cJSON *ezsigntemplatepackagesigner_create_object_v1_response_all_ofJSON);

cJSON *ezsigntemplatepackagesigner_create_object_v1_response_all_of_convertToJSON(ezsigntemplatepackagesigner_create_object_v1_response_all_of_t *ezsigntemplatepackagesigner_create_object_v1_response_all_of);

#endif /* _ezsigntemplatepackagesigner_create_object_v1_response_all_of_H_ */

