/*
 * ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload.h
 *
 * Payload for GET /2/object/ezsigntemplatedocumentpagerecognition/{pkiEzsigntemplatedocumentpagerecognitionID}
 */

#ifndef _ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload_H_
#define _ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload_t ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload_t;

#include "ezsigntemplatedocumentpagerecognition_response_compound.h"



typedef struct ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload_t {
    struct ezsigntemplatedocumentpagerecognition_response_compound_t *obj_ezsigntemplatedocumentpagerecognition; //model

    int _library_owned; // Is the library responsible for freeing this object?
} ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload_t;

__attribute__((deprecated)) ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload_t *ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload_create(
    ezsigntemplatedocumentpagerecognition_response_compound_t *obj_ezsigntemplatedocumentpagerecognition
);

void ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload_free(ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload_t *ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload);

ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload_t *ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload_parseFromJSON(cJSON *ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payloadJSON);

cJSON *ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload_convertToJSON(ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload_t *ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload);

#endif /* _ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload_H_ */

