/*
 * ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v2_request.h
 *
 * Request for PUT /2/object/ezsigntemplatepackage/{pkiEzsigntemplatepackageID}/editEzsigntemplatepackagesigners
 */

#ifndef _ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v2_request_H_
#define _ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v2_request_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v2_request_t ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v2_request_t;

#include "ezsigntemplatepackagesigner_request_compound_v2.h"



typedef struct ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v2_request_t {
    list_t *a_obj_ezsigntemplatepackagesigner; //nonprimitive container

    int _library_owned; // Is the library responsible for freeing this object?
} ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v2_request_t;

__attribute__((deprecated)) ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v2_request_t *ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v2_request_create(
    list_t *a_obj_ezsigntemplatepackagesigner
);

void ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v2_request_free(ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v2_request_t *ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v2_request);

ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v2_request_t *ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v2_request_parseFromJSON(cJSON *ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v2_requestJSON);

cJSON *ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v2_request_convertToJSON(ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v2_request_t *ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v2_request);

#endif /* _ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v2_request_H_ */

