/*
 * ezsigntemplatesignature_request_compound_v2.h
 *
 * A Ezsigntemplatesignature Object and children
 */

#ifndef _ezsigntemplatesignature_request_compound_v2_H_
#define _ezsigntemplatesignature_request_compound_v2_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct ezsigntemplatesignature_request_compound_v2_t ezsigntemplatesignature_request_compound_v2_t;

#include "enum_textvalidation.h"
#include "ezsigntemplateelementdependency_request.h"
#include "ezsigntemplatesignaturecustomdate_request_v2.h"
#include "field_e_ezsigntemplatesignature_attachmentnamesource.h"
#include "field_e_ezsigntemplatesignature_consultationtrigger.h"
#include "field_e_ezsigntemplatesignature_dependencyrequirement.h"
#include "field_e_ezsigntemplatesignature_font.h"
#include "field_e_ezsigntemplatesignature_positioning.h"
#include "field_e_ezsigntemplatesignature_positioningoccurence.h"
#include "field_e_ezsigntemplatesignature_tooltipposition.h"
#include "field_e_ezsigntemplatesignature_type.h"

// Enum  for ezsigntemplatesignature_request_compound_v2

typedef enum  { ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__NULL = 0, ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__PerCoordinates, ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__PerPositioningPattern } ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__e;

char* ezsigntemplatesignature_request_compound_v2_e_ezsigntemplatesignature_positioning_ToString(ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__e e_ezsigntemplatesignature_positioning);

ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__e ezsigntemplatesignature_request_compound_v2_e_ezsigntemplatesignature_positioning_FromString(char* e_ezsigntemplatesignature_positioning);

// Enum  for ezsigntemplatesignature_request_compound_v2

typedef enum  { ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__NULL = 0, ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__Acknowledgement, ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__City, ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__Handwritten, ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__Initials, ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__Name, ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__NameReason, ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__Attachments, ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__FieldText, ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__FieldTextarea, ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__Consultation, ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__Signature } ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__e;

char* ezsigntemplatesignature_request_compound_v2_e_ezsigntemplatesignature_type_ToString(ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__e e_ezsigntemplatesignature_type);

ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__e ezsigntemplatesignature_request_compound_v2_e_ezsigntemplatesignature_type_FromString(char* e_ezsigntemplatesignature_type);

// Enum  for ezsigntemplatesignature_request_compound_v2

typedef enum  { ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__NULL = 0, ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__Automatic, ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__Manual } ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__e;

char* ezsigntemplatesignature_request_compound_v2_e_ezsigntemplatesignature_consultationtrigger_ToString(ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__e e_ezsigntemplatesignature_consultationtrigger);

ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__e ezsigntemplatesignature_request_compound_v2_e_ezsigntemplatesignature_consultationtrigger_FromString(char* e_ezsigntemplatesignature_consultationtrigger);

// Enum  for ezsigntemplatesignature_request_compound_v2

typedef enum  { ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__NULL = 0, ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__TopLeft, ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__TopCenter, ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__TopRight, ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__MiddleLeft, ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__MiddleRight, ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__BottomLeft, ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__BottomCenter, ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__BottomRight } ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__e;

char* ezsigntemplatesignature_request_compound_v2_e_ezsigntemplatesignature_tooltipposition_ToString(ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__e e_ezsigntemplatesignature_tooltipposition);

ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__e ezsigntemplatesignature_request_compound_v2_e_ezsigntemplatesignature_tooltipposition_FromString(char* e_ezsigntemplatesignature_tooltipposition);

// Enum  for ezsigntemplatesignature_request_compound_v2

typedef enum  { ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__NULL = 0, ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__Normal, ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__Cursive } ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__e;

char* ezsigntemplatesignature_request_compound_v2_e_ezsigntemplatesignature_font_ToString(ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__e e_ezsigntemplatesignature_font);

ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__e ezsigntemplatesignature_request_compound_v2_e_ezsigntemplatesignature_font_FromString(char* e_ezsigntemplatesignature_font);

// Enum  for ezsigntemplatesignature_request_compound_v2

typedef enum  { ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__NULL = 0, ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__Description, ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__Customer, ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__DescriptionCustomer } ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__e;

char* ezsigntemplatesignature_request_compound_v2_e_ezsigntemplatesignature_attachmentnamesource_ToString(ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__e e_ezsigntemplatesignature_attachmentnamesource);

ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__e ezsigntemplatesignature_request_compound_v2_e_ezsigntemplatesignature_attachmentnamesource_FromString(char* e_ezsigntemplatesignature_attachmentnamesource);

// Enum  for ezsigntemplatesignature_request_compound_v2

typedef enum  { ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__NULL = 0, ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__None, ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__Date (YYYY_MM_DD), ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__Date (MM/DD/YYYY), ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__Date (MM/DD/YY), ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__Date (DD/MM/YYYY), ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__Date (DD/MM/YY), ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__Email, ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__Letters, ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__Numbers, ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__Zip, ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__Zip+4, ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__PostalCode, ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__Custom } ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__e;

char* ezsigntemplatesignature_request_compound_v2_e_ezsigntemplatesignature_textvalidation_ToString(ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__e e_ezsigntemplatesignature_textvalidation);

ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__e ezsigntemplatesignature_request_compound_v2_e_ezsigntemplatesignature_textvalidation_FromString(char* e_ezsigntemplatesignature_textvalidation);

// Enum  for ezsigntemplatesignature_request_compound_v2

typedef enum  { ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__NULL = 0, ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__AllOf, ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__AnyOf } ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__e;

char* ezsigntemplatesignature_request_compound_v2_e_ezsigntemplatesignature_dependencyrequirement_ToString(ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__e e_ezsigntemplatesignature_dependencyrequirement);

ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__e ezsigntemplatesignature_request_compound_v2_e_ezsigntemplatesignature_dependencyrequirement_FromString(char* e_ezsigntemplatesignature_dependencyrequirement);

// Enum  for ezsigntemplatesignature_request_compound_v2

typedef enum  { ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__NULL = 0, ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__All, ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__First, ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__Last } ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__e;

char* ezsigntemplatesignature_request_compound_v2_e_ezsigntemplatesignature_positioningoccurence_ToString(ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__e e_ezsigntemplatesignature_positioningoccurence);

ezmax_api_definition__full_ezsigntemplatesignature_request_compound_v2__e ezsigntemplatesignature_request_compound_v2_e_ezsigntemplatesignature_positioningoccurence_FromString(char* e_ezsigntemplatesignature_positioningoccurence);



typedef struct ezsigntemplatesignature_request_compound_v2_t {
    int pki_ezsigntemplatesignature_id; //numeric
    int fki_ezsigntemplatedocument_id; //numeric
    int fki_ezsigntemplatesigner_id; //numeric
    int fki_ezsigntemplatesigner_id_validation; //numeric
    int b_ezsigntemplatesignature_handwritten; //boolean
    int b_ezsigntemplatesignature_reason; //boolean
    field_e_ezsigntemplatesignature_positioning_t *e_ezsigntemplatesignature_positioning; // custom
    int i_ezsigntemplatedocumentpage_pagenumber; //numeric
    int i_ezsigntemplatesignature_x; //numeric
    int i_ezsigntemplatesignature_y; //numeric
    int i_ezsigntemplatesignature_width; //numeric
    int i_ezsigntemplatesignature_height; //numeric
    int i_ezsigntemplatesignature_step; //numeric
    field_e_ezsigntemplatesignature_type_t *e_ezsigntemplatesignature_type; // custom
    field_e_ezsigntemplatesignature_consultationtrigger_t *e_ezsigntemplatesignature_consultationtrigger; // custom
    char *t_ezsigntemplatesignature_tooltip; // string
    field_e_ezsigntemplatesignature_tooltipposition_t *e_ezsigntemplatesignature_tooltipposition; // custom
    field_e_ezsigntemplatesignature_font_t *e_ezsigntemplatesignature_font; // custom
    int b_ezsigntemplatesignature_required; //boolean
    field_e_ezsigntemplatesignature_attachmentnamesource_t *e_ezsigntemplatesignature_attachmentnamesource; // custom
    char *s_ezsigntemplatesignature_attachmentdescription; // string
    int i_ezsigntemplatesignature_validationstep; //numeric
    int i_ezsigntemplatesignature_maxlength; //numeric
    char *s_ezsigntemplatesignature_defaultvalue; // string
    char *s_ezsigntemplatesignature_regexp; // string
    enum_textvalidation_t *e_ezsigntemplatesignature_textvalidation; // custom
    char *s_ezsigntemplatesignature_textvalidationcustommessage; // string
    field_e_ezsigntemplatesignature_dependencyrequirement_t *e_ezsigntemplatesignature_dependencyrequirement; // custom
    char *s_ezsigntemplatesignature_positioningpattern; // string
    int i_ezsigntemplatesignature_positioningoffsetx; //numeric
    int i_ezsigntemplatesignature_positioningoffsety; //numeric
    field_e_ezsigntemplatesignature_positioningoccurence_t *e_ezsigntemplatesignature_positioningoccurence; // custom
    int b_ezsigntemplatesignature_customdate; //boolean
    list_t *a_obj_ezsigntemplatesignaturecustomdate; //nonprimitive container
    list_t *a_obj_ezsigntemplateelementdependency; //nonprimitive container

} ezsigntemplatesignature_request_compound_v2_t;

ezsigntemplatesignature_request_compound_v2_t *ezsigntemplatesignature_request_compound_v2_create(
    int pki_ezsigntemplatesignature_id,
    int fki_ezsigntemplatedocument_id,
    int fki_ezsigntemplatesigner_id,
    int fki_ezsigntemplatesigner_id_validation,
    int b_ezsigntemplatesignature_handwritten,
    int b_ezsigntemplatesignature_reason,
    field_e_ezsigntemplatesignature_positioning_t *e_ezsigntemplatesignature_positioning,
    int i_ezsigntemplatedocumentpage_pagenumber,
    int i_ezsigntemplatesignature_x,
    int i_ezsigntemplatesignature_y,
    int i_ezsigntemplatesignature_width,
    int i_ezsigntemplatesignature_height,
    int i_ezsigntemplatesignature_step,
    field_e_ezsigntemplatesignature_type_t *e_ezsigntemplatesignature_type,
    field_e_ezsigntemplatesignature_consultationtrigger_t *e_ezsigntemplatesignature_consultationtrigger,
    char *t_ezsigntemplatesignature_tooltip,
    field_e_ezsigntemplatesignature_tooltipposition_t *e_ezsigntemplatesignature_tooltipposition,
    field_e_ezsigntemplatesignature_font_t *e_ezsigntemplatesignature_font,
    int b_ezsigntemplatesignature_required,
    field_e_ezsigntemplatesignature_attachmentnamesource_t *e_ezsigntemplatesignature_attachmentnamesource,
    char *s_ezsigntemplatesignature_attachmentdescription,
    int i_ezsigntemplatesignature_validationstep,
    int i_ezsigntemplatesignature_maxlength,
    char *s_ezsigntemplatesignature_defaultvalue,
    char *s_ezsigntemplatesignature_regexp,
    enum_textvalidation_t *e_ezsigntemplatesignature_textvalidation,
    char *s_ezsigntemplatesignature_textvalidationcustommessage,
    field_e_ezsigntemplatesignature_dependencyrequirement_t *e_ezsigntemplatesignature_dependencyrequirement,
    char *s_ezsigntemplatesignature_positioningpattern,
    int i_ezsigntemplatesignature_positioningoffsetx,
    int i_ezsigntemplatesignature_positioningoffsety,
    field_e_ezsigntemplatesignature_positioningoccurence_t *e_ezsigntemplatesignature_positioningoccurence,
    int b_ezsigntemplatesignature_customdate,
    list_t *a_obj_ezsigntemplatesignaturecustomdate,
    list_t *a_obj_ezsigntemplateelementdependency
);

void ezsigntemplatesignature_request_compound_v2_free(ezsigntemplatesignature_request_compound_v2_t *ezsigntemplatesignature_request_compound_v2);

ezsigntemplatesignature_request_compound_v2_t *ezsigntemplatesignature_request_compound_v2_parseFromJSON(cJSON *ezsigntemplatesignature_request_compound_v2JSON);

cJSON *ezsigntemplatesignature_request_compound_v2_convertToJSON(ezsigntemplatesignature_request_compound_v2_t *ezsigntemplatesignature_request_compound_v2);

#endif /* _ezsigntemplatesignature_request_compound_v2_H_ */

