/*
 * ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v1_request.h
 *
 * Request for PUT /1/object/ezsigntemplatepackage/{pkiEzsigntemplatepackageID}/editEzsigntemplatepackagesigners
 */

#ifndef _ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v1_request_H_
#define _ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v1_request_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v1_request_t ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v1_request_t;

#include "ezsigntemplatepackagesigner_request_compound.h"



typedef struct ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v1_request_t {
    list_t *a_obj_ezsigntemplatepackagesigner; //nonprimitive container

} ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v1_request_t;

ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v1_request_t *ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v1_request_create(
    list_t *a_obj_ezsigntemplatepackagesigner
);

void ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v1_request_free(ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v1_request_t *ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v1_request);

ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v1_request_t *ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v1_request_parseFromJSON(cJSON *ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v1_requestJSON);

cJSON *ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v1_request_convertToJSON(ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v1_request_t *ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v1_request);

#endif /* _ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v1_request_H_ */

