/*
 * ezsigntemplateformfieldgroup_create_object_v1_response_m_payload.h
 *
 * Payload for POST /1/object/ezsigntemplateformfieldgroup
 */

#ifndef _ezsigntemplateformfieldgroup_create_object_v1_response_m_payload_H_
#define _ezsigntemplateformfieldgroup_create_object_v1_response_m_payload_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct ezsigntemplateformfieldgroup_create_object_v1_response_m_payload_t ezsigntemplateformfieldgroup_create_object_v1_response_m_payload_t;




typedef struct ezsigntemplateformfieldgroup_create_object_v1_response_m_payload_t {
    list_t *a_pki_ezsigntemplateformfieldgroup_id; //primitive container

    int _library_owned; // Is the library responsible for freeing this object?
} ezsigntemplateformfieldgroup_create_object_v1_response_m_payload_t;

__attribute__((deprecated)) ezsigntemplateformfieldgroup_create_object_v1_response_m_payload_t *ezsigntemplateformfieldgroup_create_object_v1_response_m_payload_create(
    list_t *a_pki_ezsigntemplateformfieldgroup_id
);

void ezsigntemplateformfieldgroup_create_object_v1_response_m_payload_free(ezsigntemplateformfieldgroup_create_object_v1_response_m_payload_t *ezsigntemplateformfieldgroup_create_object_v1_response_m_payload);

ezsigntemplateformfieldgroup_create_object_v1_response_m_payload_t *ezsigntemplateformfieldgroup_create_object_v1_response_m_payload_parseFromJSON(cJSON *ezsigntemplateformfieldgroup_create_object_v1_response_m_payloadJSON);

cJSON *ezsigntemplateformfieldgroup_create_object_v1_response_m_payload_convertToJSON(ezsigntemplateformfieldgroup_create_object_v1_response_m_payload_t *ezsigntemplateformfieldgroup_create_object_v1_response_m_payload);

#endif /* _ezsigntemplateformfieldgroup_create_object_v1_response_m_payload_H_ */

