/*
 * ezsigntemplatedocument_get_ezsigntemplatesignatures_v1_response_m_payload.h
 *
 * Payload for GET /1/object/ezsigntemplatedocument/{pkiEzsigntemplatedocument}/getEzsigntemplatesignatures
 */

#ifndef _ezsigntemplatedocument_get_ezsigntemplatesignatures_v1_response_m_payload_H_
#define _ezsigntemplatedocument_get_ezsigntemplatesignatures_v1_response_m_payload_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct ezsigntemplatedocument_get_ezsigntemplatesignatures_v1_response_m_payload_t ezsigntemplatedocument_get_ezsigntemplatesignatures_v1_response_m_payload_t;

#include "ezsigntemplatesignature_response_compound.h"



typedef struct ezsigntemplatedocument_get_ezsigntemplatesignatures_v1_response_m_payload_t {
    list_t *a_obj_ezsigntemplatesignature; //nonprimitive container

} ezsigntemplatedocument_get_ezsigntemplatesignatures_v1_response_m_payload_t;

ezsigntemplatedocument_get_ezsigntemplatesignatures_v1_response_m_payload_t *ezsigntemplatedocument_get_ezsigntemplatesignatures_v1_response_m_payload_create(
    list_t *a_obj_ezsigntemplatesignature
);

void ezsigntemplatedocument_get_ezsigntemplatesignatures_v1_response_m_payload_free(ezsigntemplatedocument_get_ezsigntemplatesignatures_v1_response_m_payload_t *ezsigntemplatedocument_get_ezsigntemplatesignatures_v1_response_m_payload);

ezsigntemplatedocument_get_ezsigntemplatesignatures_v1_response_m_payload_t *ezsigntemplatedocument_get_ezsigntemplatesignatures_v1_response_m_payload_parseFromJSON(cJSON *ezsigntemplatedocument_get_ezsigntemplatesignatures_v1_response_m_payloadJSON);

cJSON *ezsigntemplatedocument_get_ezsigntemplatesignatures_v1_response_m_payload_convertToJSON(ezsigntemplatedocument_get_ezsigntemplatesignatures_v1_response_m_payload_t *ezsigntemplatedocument_get_ezsigntemplatesignatures_v1_response_m_payload);

#endif /* _ezsigntemplatedocument_get_ezsigntemplatesignatures_v1_response_m_payload_H_ */

