/*
 * ezsignbulksenddocumentmapping_create_object_v1_response_m_payload.h
 *
 * Payload for POST /1/object/ezsignbulksenddocumentmapping
 */

#ifndef _ezsignbulksenddocumentmapping_create_object_v1_response_m_payload_H_
#define _ezsignbulksenddocumentmapping_create_object_v1_response_m_payload_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct ezsignbulksenddocumentmapping_create_object_v1_response_m_payload_t ezsignbulksenddocumentmapping_create_object_v1_response_m_payload_t;




typedef struct ezsignbulksenddocumentmapping_create_object_v1_response_m_payload_t {
    list_t *a_pki_ezsignbulksenddocumentmapping_id; //primitive container

} ezsignbulksenddocumentmapping_create_object_v1_response_m_payload_t;

ezsignbulksenddocumentmapping_create_object_v1_response_m_payload_t *ezsignbulksenddocumentmapping_create_object_v1_response_m_payload_create(
    list_t *a_pki_ezsignbulksenddocumentmapping_id
);

void ezsignbulksenddocumentmapping_create_object_v1_response_m_payload_free(ezsignbulksenddocumentmapping_create_object_v1_response_m_payload_t *ezsignbulksenddocumentmapping_create_object_v1_response_m_payload);

ezsignbulksenddocumentmapping_create_object_v1_response_m_payload_t *ezsignbulksenddocumentmapping_create_object_v1_response_m_payload_parseFromJSON(cJSON *ezsignbulksenddocumentmapping_create_object_v1_response_m_payloadJSON);

cJSON *ezsignbulksenddocumentmapping_create_object_v1_response_m_payload_convertToJSON(ezsignbulksenddocumentmapping_create_object_v1_response_m_payload_t *ezsignbulksenddocumentmapping_create_object_v1_response_m_payload);

#endif /* _ezsignbulksenddocumentmapping_create_object_v1_response_m_payload_H_ */

