/*
 * ezsigntemplateformfieldgroup_request_compound.h
 *
 * A Ezsigntemplateformfieldgroup Object and children
 */

#ifndef _ezsigntemplateformfieldgroup_request_compound_H_
#define _ezsigntemplateformfieldgroup_request_compound_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct ezsigntemplateformfieldgroup_request_compound_t ezsigntemplateformfieldgroup_request_compound_t;

#include "custom_dropdown_element_request.h"
#include "enum_textvalidation.h"
#include "ezsigntemplateformfield_request_compound.h"
#include "ezsigntemplateformfieldgroup_request.h"
#include "ezsigntemplateformfieldgroupsigner_request.h"
#include "field_e_ezsigntemplateformfieldgroup_signerrequirement.h"
#include "field_e_ezsigntemplateformfieldgroup_tooltipposition.h"
#include "field_e_ezsigntemplateformfieldgroup_type.h"

// Enum  for ezsigntemplateformfieldgroup_request_compound

typedef enum  { ezmax_api_definition__full_ezsigntemplateformfieldgroup_request_compound__NULL = 0, ezmax_api_definition__full_ezsigntemplateformfieldgroup_request_compound__Text, ezmax_api_definition__full_ezsigntemplateformfieldgroup_request_compound__Textarea, ezmax_api_definition__full_ezsigntemplateformfieldgroup_request_compound__Dropdown, ezmax_api_definition__full_ezsigntemplateformfieldgroup_request_compound__Radio, ezmax_api_definition__full_ezsigntemplateformfieldgroup_request_compound__Checkbox, ezmax_api_definition__full_ezsigntemplateformfieldgroup_request_compound__Number, ezmax_api_definition__full_ezsigntemplateformfieldgroup_request_compound__Date } ezmax_api_definition__full_ezsigntemplateformfieldgroup_request_compound__e;

char* ezsigntemplateformfieldgroup_request_compound_e_ezsigntemplateformfieldgroup_type_ToString(ezmax_api_definition__full_ezsigntemplateformfieldgroup_request_compound__e e_ezsigntemplateformfieldgroup_type);

ezmax_api_definition__full_ezsigntemplateformfieldgroup_request_compound__e ezsigntemplateformfieldgroup_request_compound_e_ezsigntemplateformfieldgroup_type_FromString(char* e_ezsigntemplateformfieldgroup_type);

// Enum  for ezsigntemplateformfieldgroup_request_compound

typedef enum  { ezmax_api_definition__full_ezsigntemplateformfieldgroup_request_compound__NULL = 0, ezmax_api_definition__full_ezsigntemplateformfieldgroup_request_compound__All, ezmax_api_definition__full_ezsigntemplateformfieldgroup_request_compound__One } ezmax_api_definition__full_ezsigntemplateformfieldgroup_request_compound__e;

char* ezsigntemplateformfieldgroup_request_compound_e_ezsigntemplateformfieldgroup_signerrequirement_ToString(ezmax_api_definition__full_ezsigntemplateformfieldgroup_request_compound__e e_ezsigntemplateformfieldgroup_signerrequirement);

ezmax_api_definition__full_ezsigntemplateformfieldgroup_request_compound__e ezsigntemplateformfieldgroup_request_compound_e_ezsigntemplateformfieldgroup_signerrequirement_FromString(char* e_ezsigntemplateformfieldgroup_signerrequirement);

// Enum  for ezsigntemplateformfieldgroup_request_compound

typedef enum  { ezmax_api_definition__full_ezsigntemplateformfieldgroup_request_compound__NULL = 0, ezmax_api_definition__full_ezsigntemplateformfieldgroup_request_compound__None, ezmax_api_definition__full_ezsigntemplateformfieldgroup_request_compound__Date (YYYY_MM_DD), ezmax_api_definition__full_ezsigntemplateformfieldgroup_request_compound__Date (MM/DD/YYYY), ezmax_api_definition__full_ezsigntemplateformfieldgroup_request_compound__Date (MM/DD/YY), ezmax_api_definition__full_ezsigntemplateformfieldgroup_request_compound__Date (DD/MM/YYYY), ezmax_api_definition__full_ezsigntemplateformfieldgroup_request_compound__Date (DD/MM/YY), ezmax_api_definition__full_ezsigntemplateformfieldgroup_request_compound__Email, ezmax_api_definition__full_ezsigntemplateformfieldgroup_request_compound__Letters, ezmax_api_definition__full_ezsigntemplateformfieldgroup_request_compound__Numbers, ezmax_api_definition__full_ezsigntemplateformfieldgroup_request_compound__Zip, ezmax_api_definition__full_ezsigntemplateformfieldgroup_request_compound__Zip+4, ezmax_api_definition__full_ezsigntemplateformfieldgroup_request_compound__PostalCode, ezmax_api_definition__full_ezsigntemplateformfieldgroup_request_compound__Custom } ezmax_api_definition__full_ezsigntemplateformfieldgroup_request_compound__e;

char* ezsigntemplateformfieldgroup_request_compound_e_ezsigntemplateformfieldgroup_textvalidation_ToString(ezmax_api_definition__full_ezsigntemplateformfieldgroup_request_compound__e e_ezsigntemplateformfieldgroup_textvalidation);

ezmax_api_definition__full_ezsigntemplateformfieldgroup_request_compound__e ezsigntemplateformfieldgroup_request_compound_e_ezsigntemplateformfieldgroup_textvalidation_FromString(char* e_ezsigntemplateformfieldgroup_textvalidation);

// Enum  for ezsigntemplateformfieldgroup_request_compound

typedef enum  { ezmax_api_definition__full_ezsigntemplateformfieldgroup_request_compound__NULL = 0, ezmax_api_definition__full_ezsigntemplateformfieldgroup_request_compound__TopLeft, ezmax_api_definition__full_ezsigntemplateformfieldgroup_request_compound__TopCenter, ezmax_api_definition__full_ezsigntemplateformfieldgroup_request_compound__TopRight, ezmax_api_definition__full_ezsigntemplateformfieldgroup_request_compound__MiddleLeft, ezmax_api_definition__full_ezsigntemplateformfieldgroup_request_compound__MiddleRight, ezmax_api_definition__full_ezsigntemplateformfieldgroup_request_compound__BottomLeft, ezmax_api_definition__full_ezsigntemplateformfieldgroup_request_compound__BottomCenter, ezmax_api_definition__full_ezsigntemplateformfieldgroup_request_compound__BottomRight } ezmax_api_definition__full_ezsigntemplateformfieldgroup_request_compound__e;

char* ezsigntemplateformfieldgroup_request_compound_e_ezsigntemplateformfieldgroup_tooltipposition_ToString(ezmax_api_definition__full_ezsigntemplateformfieldgroup_request_compound__e e_ezsigntemplateformfieldgroup_tooltipposition);

ezmax_api_definition__full_ezsigntemplateformfieldgroup_request_compound__e ezsigntemplateformfieldgroup_request_compound_e_ezsigntemplateformfieldgroup_tooltipposition_FromString(char* e_ezsigntemplateformfieldgroup_tooltipposition);



typedef struct ezsigntemplateformfieldgroup_request_compound_t {
    int pki_ezsigntemplateformfieldgroup_id; //numeric
    int fki_ezsigntemplatedocument_id; //numeric
    field_e_ezsigntemplateformfieldgroup_type_t *e_ezsigntemplateformfieldgroup_type; // custom
    field_e_ezsigntemplateformfieldgroup_signerrequirement_t *e_ezsigntemplateformfieldgroup_signerrequirement; // custom
    char *s_ezsigntemplateformfieldgroup_label; // string
    int i_ezsigntemplateformfieldgroup_step; //numeric
    char *s_ezsigntemplateformfieldgroup_defaultvalue; // string
    int i_ezsigntemplateformfieldgroup_filledmin; //numeric
    int i_ezsigntemplateformfieldgroup_filledmax; //numeric
    int b_ezsigntemplateformfieldgroup_readonly; //boolean
    int i_ezsigntemplateformfieldgroup_maxlength; //numeric
    int b_ezsigntemplateformfieldgroup_encrypted; //boolean
    char *s_ezsigntemplateformfieldgroup_regexp; // string
    char *s_ezsigntemplateformfieldgroup_textvalidationcustommessage; // string
    enum_textvalidation_t *e_ezsigntemplateformfieldgroup_textvalidation; // custom
    char *t_ezsigntemplateformfieldgroup_tooltip; // string
    field_e_ezsigntemplateformfieldgroup_tooltipposition_t *e_ezsigntemplateformfieldgroup_tooltipposition; // custom
    list_t *a_obj_ezsigntemplateformfieldgroupsigner; //nonprimitive container
    list_t *a_obj_dropdown_element; //nonprimitive container
    list_t *a_obj_ezsigntemplateformfield; //nonprimitive container

} ezsigntemplateformfieldgroup_request_compound_t;

ezsigntemplateformfieldgroup_request_compound_t *ezsigntemplateformfieldgroup_request_compound_create(
    int pki_ezsigntemplateformfieldgroup_id,
    int fki_ezsigntemplatedocument_id,
    field_e_ezsigntemplateformfieldgroup_type_t *e_ezsigntemplateformfieldgroup_type,
    field_e_ezsigntemplateformfieldgroup_signerrequirement_t *e_ezsigntemplateformfieldgroup_signerrequirement,
    char *s_ezsigntemplateformfieldgroup_label,
    int i_ezsigntemplateformfieldgroup_step,
    char *s_ezsigntemplateformfieldgroup_defaultvalue,
    int i_ezsigntemplateformfieldgroup_filledmin,
    int i_ezsigntemplateformfieldgroup_filledmax,
    int b_ezsigntemplateformfieldgroup_readonly,
    int i_ezsigntemplateformfieldgroup_maxlength,
    int b_ezsigntemplateformfieldgroup_encrypted,
    char *s_ezsigntemplateformfieldgroup_regexp,
    char *s_ezsigntemplateformfieldgroup_textvalidationcustommessage,
    enum_textvalidation_t *e_ezsigntemplateformfieldgroup_textvalidation,
    char *t_ezsigntemplateformfieldgroup_tooltip,
    field_e_ezsigntemplateformfieldgroup_tooltipposition_t *e_ezsigntemplateformfieldgroup_tooltipposition,
    list_t *a_obj_ezsigntemplateformfieldgroupsigner,
    list_t *a_obj_dropdown_element,
    list_t *a_obj_ezsigntemplateformfield
);

void ezsigntemplateformfieldgroup_request_compound_free(ezsigntemplateformfieldgroup_request_compound_t *ezsigntemplateformfieldgroup_request_compound);

ezsigntemplateformfieldgroup_request_compound_t *ezsigntemplateformfieldgroup_request_compound_parseFromJSON(cJSON *ezsigntemplateformfieldgroup_request_compoundJSON);

cJSON *ezsigntemplateformfieldgroup_request_compound_convertToJSON(ezsigntemplateformfieldgroup_request_compound_t *ezsigntemplateformfieldgroup_request_compound);

#endif /* _ezsigntemplateformfieldgroup_request_compound_H_ */

