/*
 * ezsigntemplatepackage_autocomplete_element_response.h
 *
 * A Ezsigntemplatepackage AutocompleteElement Response
 */

#ifndef _ezsigntemplatepackage_autocomplete_element_response_H_
#define _ezsigntemplatepackage_autocomplete_element_response_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct ezsigntemplatepackage_autocomplete_element_response_t ezsigntemplatepackage_autocomplete_element_response_t;

#include "field_e_ezsignfoldertype_privacylevel.h"

// Enum  for ezsigntemplatepackage_autocomplete_element_response

typedef enum  { ezmax_api_definition__full_ezsigntemplatepackage_autocomplete_element_response__NULL = 0, ezmax_api_definition__full_ezsigntemplatepackage_autocomplete_element_response__User, ezmax_api_definition__full_ezsigntemplatepackage_autocomplete_element_response__Usergroup } ezmax_api_definition__full_ezsigntemplatepackage_autocomplete_element_response__e;

char* ezsigntemplatepackage_autocomplete_element_response_e_ezsignfoldertype_privacylevel_ToString(ezmax_api_definition__full_ezsigntemplatepackage_autocomplete_element_response__e e_ezsignfoldertype_privacylevel);

ezmax_api_definition__full_ezsigntemplatepackage_autocomplete_element_response__e ezsigntemplatepackage_autocomplete_element_response_e_ezsignfoldertype_privacylevel_FromString(char* e_ezsignfoldertype_privacylevel);



typedef struct ezsigntemplatepackage_autocomplete_element_response_t {
    field_e_ezsignfoldertype_privacylevel_t *e_ezsignfoldertype_privacylevel; // custom
    char *s_ezsigntemplatepackage_description; // string
    int pki_ezsigntemplatepackage_id; //numeric
    int b_ezsigntemplatepackage_isactive; //boolean
    int b_disabled; //boolean

} ezsigntemplatepackage_autocomplete_element_response_t;

ezsigntemplatepackage_autocomplete_element_response_t *ezsigntemplatepackage_autocomplete_element_response_create(
    field_e_ezsignfoldertype_privacylevel_t *e_ezsignfoldertype_privacylevel,
    char *s_ezsigntemplatepackage_description,
    int pki_ezsigntemplatepackage_id,
    int b_ezsigntemplatepackage_isactive,
    int b_disabled
);

void ezsigntemplatepackage_autocomplete_element_response_free(ezsigntemplatepackage_autocomplete_element_response_t *ezsigntemplatepackage_autocomplete_element_response);

ezsigntemplatepackage_autocomplete_element_response_t *ezsigntemplatepackage_autocomplete_element_response_parseFromJSON(cJSON *ezsigntemplatepackage_autocomplete_element_responseJSON);

cJSON *ezsigntemplatepackage_autocomplete_element_response_convertToJSON(ezsigntemplatepackage_autocomplete_element_response_t *ezsigntemplatepackage_autocomplete_element_response);

#endif /* _ezsigntemplatepackage_autocomplete_element_response_H_ */

