/*
 * ezsignfoldersignerassociation_get_object_v2_response_all_of.h
 *
 * 
 */

#ifndef _ezsignfoldersignerassociation_get_object_v2_response_all_of_H_
#define _ezsignfoldersignerassociation_get_object_v2_response_all_of_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct ezsignfoldersignerassociation_get_object_v2_response_all_of_t ezsignfoldersignerassociation_get_object_v2_response_all_of_t;

#include "ezsignfoldersignerassociation_get_object_v2_response_m_payload.h"



typedef struct ezsignfoldersignerassociation_get_object_v2_response_all_of_t {
    struct ezsignfoldersignerassociation_get_object_v2_response_m_payload_t *m_payload; //model

} ezsignfoldersignerassociation_get_object_v2_response_all_of_t;

ezsignfoldersignerassociation_get_object_v2_response_all_of_t *ezsignfoldersignerassociation_get_object_v2_response_all_of_create(
    ezsignfoldersignerassociation_get_object_v2_response_m_payload_t *m_payload
);

void ezsignfoldersignerassociation_get_object_v2_response_all_of_free(ezsignfoldersignerassociation_get_object_v2_response_all_of_t *ezsignfoldersignerassociation_get_object_v2_response_all_of);

ezsignfoldersignerassociation_get_object_v2_response_all_of_t *ezsignfoldersignerassociation_get_object_v2_response_all_of_parseFromJSON(cJSON *ezsignfoldersignerassociation_get_object_v2_response_all_ofJSON);

cJSON *ezsignfoldersignerassociation_get_object_v2_response_all_of_convertToJSON(ezsignfoldersignerassociation_get_object_v2_response_all_of_t *ezsignfoldersignerassociation_get_object_v2_response_all_of);

#endif /* _ezsignfoldersignerassociation_get_object_v2_response_all_of_H_ */

