/*
 * ezsigntemplatedocument_get_words_positions_v1_response_all_of.h
 *
 * 
 */

#ifndef _ezsigntemplatedocument_get_words_positions_v1_response_all_of_H_
#define _ezsigntemplatedocument_get_words_positions_v1_response_all_of_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct ezsigntemplatedocument_get_words_positions_v1_response_all_of_t ezsigntemplatedocument_get_words_positions_v1_response_all_of_t;

#include "custom_word_position_word_response.h"



typedef struct ezsigntemplatedocument_get_words_positions_v1_response_all_of_t {
    list_t *m_payload; //nonprimitive container

} ezsigntemplatedocument_get_words_positions_v1_response_all_of_t;

ezsigntemplatedocument_get_words_positions_v1_response_all_of_t *ezsigntemplatedocument_get_words_positions_v1_response_all_of_create(
    list_t *m_payload
);

void ezsigntemplatedocument_get_words_positions_v1_response_all_of_free(ezsigntemplatedocument_get_words_positions_v1_response_all_of_t *ezsigntemplatedocument_get_words_positions_v1_response_all_of);

ezsigntemplatedocument_get_words_positions_v1_response_all_of_t *ezsigntemplatedocument_get_words_positions_v1_response_all_of_parseFromJSON(cJSON *ezsigntemplatedocument_get_words_positions_v1_response_all_ofJSON);

cJSON *ezsigntemplatedocument_get_words_positions_v1_response_all_of_convertToJSON(ezsigntemplatedocument_get_words_positions_v1_response_all_of_t *ezsigntemplatedocument_get_words_positions_v1_response_all_of);

#endif /* _ezsigntemplatedocument_get_words_positions_v1_response_all_of_H_ */

