/*
 * ezsigntsarequirement_get_autocomplete_v2_response_all_of.h
 *
 * 
 */

#ifndef _ezsigntsarequirement_get_autocomplete_v2_response_all_of_H_
#define _ezsigntsarequirement_get_autocomplete_v2_response_all_of_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct ezsigntsarequirement_get_autocomplete_v2_response_all_of_t ezsigntsarequirement_get_autocomplete_v2_response_all_of_t;

#include "ezsigntsarequirement_get_autocomplete_v2_response_m_payload.h"



typedef struct ezsigntsarequirement_get_autocomplete_v2_response_all_of_t {
    struct ezsigntsarequirement_get_autocomplete_v2_response_m_payload_t *m_payload; //model

} ezsigntsarequirement_get_autocomplete_v2_response_all_of_t;

ezsigntsarequirement_get_autocomplete_v2_response_all_of_t *ezsigntsarequirement_get_autocomplete_v2_response_all_of_create(
    ezsigntsarequirement_get_autocomplete_v2_response_m_payload_t *m_payload
);

void ezsigntsarequirement_get_autocomplete_v2_response_all_of_free(ezsigntsarequirement_get_autocomplete_v2_response_all_of_t *ezsigntsarequirement_get_autocomplete_v2_response_all_of);

ezsigntsarequirement_get_autocomplete_v2_response_all_of_t *ezsigntsarequirement_get_autocomplete_v2_response_all_of_parseFromJSON(cJSON *ezsigntsarequirement_get_autocomplete_v2_response_all_ofJSON);

cJSON *ezsigntsarequirement_get_autocomplete_v2_response_all_of_convertToJSON(ezsigntsarequirement_get_autocomplete_v2_response_all_of_t *ezsigntsarequirement_get_autocomplete_v2_response_all_of);

#endif /* _ezsigntsarequirement_get_autocomplete_v2_response_all_of_H_ */

