/*
 * field_e_inscription_remunerationinscriptorsellertype.h
 *
 * The remunerationinscriptorsellertype of the Inscription
 */

#ifndef _field_e_inscription_remunerationinscriptorsellertype_H_
#define _field_e_inscription_remunerationinscriptorsellertype_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct field_e_inscription_remunerationinscriptorsellertype_t field_e_inscription_remunerationinscriptorsellertype_t;


// Enum  for field_e_inscription_remunerationinscriptorsellertype

typedef enum { ezmax_api_definition__full_field_e_inscription_remunerationinscriptorsellertype__NULL = 0, ezmax_api_definition__full_field_e_inscription_remunerationinscriptorsellertype__Percentage, ezmax_api_definition__full_field_e_inscription_remunerationinscriptorsellertype__Dollars } ezmax_api_definition__full_field_e_inscription_remunerationinscriptorsellertype__e;

char* field_e_inscription_remunerationinscriptorsellertype_field_e_inscription_remunerationinscriptorsellertype_ToString(ezmax_api_definition__full_field_e_inscription_remunerationinscriptorsellertype__e field_e_inscription_remunerationinscriptorsellertype);

ezmax_api_definition__full_field_e_inscription_remunerationinscriptorsellertype__e field_e_inscription_remunerationinscriptorsellertype_field_e_inscription_remunerationinscriptorsellertype_FromString(char* field_e_inscription_remunerationinscriptorsellertype);

cJSON *field_e_inscription_remunerationinscriptorsellertype_convertToJSON(ezmax_api_definition__full_field_e_inscription_remunerationinscriptorsellertype__e field_e_inscription_remunerationinscriptorsellertype);

ezmax_api_definition__full_field_e_inscription_remunerationinscriptorsellertype__e field_e_inscription_remunerationinscriptorsellertype_parseFromJSON(cJSON *field_e_inscription_remunerationinscriptorsellertypeJSON);

#endif /* _field_e_inscription_remunerationinscriptorsellertype_H_ */

