/*
 * field_e_ezsigntemplateglobalannotation_horizontalalignment.h
 *
 * The horizontalalignment of the Ezsigntemplateglobalannotation
 */

#ifndef _field_e_ezsigntemplateglobalannotation_horizontalalignment_H_
#define _field_e_ezsigntemplateglobalannotation_horizontalalignment_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct field_e_ezsigntemplateglobalannotation_horizontalalignment_t field_e_ezsigntemplateglobalannotation_horizontalalignment_t;


// Enum  for field_e_ezsigntemplateglobalannotation_horizontalalignment

typedef enum { ezmax_api_definition__full_field_e_ezsigntemplateglobalannotation_horizontalalignment__NULL = 0, ezmax_api_definition__full_field_e_ezsigntemplateglobalannotation_horizontalalignment__Center, ezmax_api_definition__full_field_e_ezsigntemplateglobalannotation_horizontalalignment__Left, ezmax_api_definition__full_field_e_ezsigntemplateglobalannotation_horizontalalignment__Right } ezmax_api_definition__full_field_e_ezsigntemplateglobalannotation_horizontalalignment__e;

char* field_e_ezsigntemplateglobalannotation_horizontalalignment_field_e_ezsigntemplateglobalannotation_horizontalalignment_ToString(ezmax_api_definition__full_field_e_ezsigntemplateglobalannotation_horizontalalignment__e field_e_ezsigntemplateglobalannotation_horizontalalignment);

ezmax_api_definition__full_field_e_ezsigntemplateglobalannotation_horizontalalignment__e field_e_ezsigntemplateglobalannotation_horizontalalignment_field_e_ezsigntemplateglobalannotation_horizontalalignment_FromString(char* field_e_ezsigntemplateglobalannotation_horizontalalignment);

cJSON *field_e_ezsigntemplateglobalannotation_horizontalalignment_convertToJSON(ezmax_api_definition__full_field_e_ezsigntemplateglobalannotation_horizontalalignment__e field_e_ezsigntemplateglobalannotation_horizontalalignment);

ezmax_api_definition__full_field_e_ezsigntemplateglobalannotation_horizontalalignment__e field_e_ezsigntemplateglobalannotation_horizontalalignment_parseFromJSON(cJSON *field_e_ezsigntemplateglobalannotation_horizontalalignmentJSON);

#endif /* _field_e_ezsigntemplateglobalannotation_horizontalalignment_H_ */

