/*
 * field_e_error_code.h
 *
 * The error code. See documentation for valid values
 */

#ifndef _field_e_error_code_H_
#define _field_e_error_code_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct field_e_error_code_t field_e_error_code_t;


// Enum  for field_e_error_code

typedef enum { ezmax_api_definition__full_field_e_error_code__NULL = 0, ezmax_api_definition__full_field_e_error_code__BADREQUEST, ezmax_api_definition__full_field_e_error_code__BADREQUEST_CLOCKSKEW, ezmax_api_definition__full_field_e_error_code__UNAUTHORIZED_BADAUTH, ezmax_api_definition__full_field_e_error_code__UNAUTHORIZED_BADMFA, ezmax_api_definition__full_field_e_error_code__UNAUTHORIZED_EXPIRED, ezmax_api_definition__full_field_e_error_code__UNAUTHORIZED_REQUEST, ezmax_api_definition__full_field_e_error_code__FORBIDDEN, ezmax_api_definition__full_field_e_error_code__FORBIDDEN_CONFIGURATION, ezmax_api_definition__full_field_e_error_code__FORBIDDEN_MODULE, ezmax_api_definition__full_field_e_error_code__FORBIDDEN_NOACCESS, ezmax_api_definition__full_field_e_error_code__FORBIDDEN_PERMISSION, ezmax_api_definition__full_field_e_error_code__FORBIDDEN_SUBSCRIPTION, ezmax_api_definition__full_field_e_error_code__FORBIDDEN_USERTYPE, ezmax_api_definition__full_field_e_error_code__FORBIDDEN_USER_ORIGIN_EXTERNAL, ezmax_api_definition__full_field_e_error_code__NOTFOUND, ezmax_api_definition__full_field_e_error_code__NOTFOUND_OBJECT, ezmax_api_definition__full_field_e_error_code__NOTFOUND_ROUTE, ezmax_api_definition__full_field_e_error_code__METHODNOTALLOWED, ezmax_api_definition__full_field_e_error_code__NOTACCEPTABLE_CONTENT, ezmax_api_definition__full_field_e_error_code__NOTACCEPTABLE_LANGUAGE, ezmax_api_definition__full_field_e_error_code__UNPROCESSABLEENTITY_ACTIVESESSION_ALREADY_CLONING, ezmax_api_definition__full_field_e_error_code__UNPROCESSABLEENTITY_CANNOTDELETE, ezmax_api_definition__full_field_e_error_code__UNPROCESSABLEENTITY_CANNOTMODIFY, ezmax_api_definition__full_field_e_error_code__UNPROCESSABLEENTITY_CHANGEPASSWORD_INVALID_CURRENT, ezmax_api_definition__full_field_e_error_code__UNPROCESSABLEENTITY_CHANGEPASSWORD_SAME, ezmax_api_definition__full_field_e_error_code__UNPROCESSABLEENTITY_DATA_MISSING, ezmax_api_definition__full_field_e_error_code__UNPROCESSABLEENTITY_DATA_UNIQUE, ezmax_api_definition__full_field_e_error_code__UNPROCESSABLEENTITY_DATA_VALIDATION, ezmax_api_definition__full_field_e_error_code__UNPROCESSABLEENTITY_DATA_OUTOFBOUND, ezmax_api_definition__full_field_e_error_code__UNPROCESSABLEENTITY_DOWNLOAD_ERROR, ezmax_api_definition__full_field_e_error_code__UNPROCESSABLEENTITY_EZSIGNFORM_VALIDATION, ezmax_api_definition__full_field_e_error_code__UNPROCESSABLEENTITY_EZSIGNSIGNERCONNECTED, ezmax_api_definition__full_field_e_error_code__UNPROCESSABLEENTITY_NOTHINGTODO, ezmax_api_definition__full_field_e_error_code__UNPROCESSABLEENTITY_NOTREADY, ezmax_api_definition__full_field_e_error_code__UNPROCESSABLEENTITY_PDF_FORM, ezmax_api_definition__full_field_e_error_code__UNPROCESSABLEENTITY_PDF_SIGNATURE, ezmax_api_definition__full_field_e_error_code__UNPROCESSABLEENTITY_PDF_FORM_AND_SIGNATURE, ezmax_api_definition__full_field_e_error_code__UNPROCESSABLEENTITY_PDF_INCOMPATIBLE, ezmax_api_definition__full_field_e_error_code__UNPROCESSABLEENTITY_PDF_PASSWORD, ezmax_api_definition__full_field_e_error_code__UNPROCESSABLEENTITY_PDF_WRONG_PASSWORD, ezmax_api_definition__full_field_e_error_code__UNPROCESSABLEENTITY_PDF_REPAIRABLE, ezmax_api_definition__full_field_e_error_code__UNPROCESSABLEENTITY_PDF_XFA, ezmax_api_definition__full_field_e_error_code__UNPROCESSABLEENTITY_TEMPLATE_MISMATCH, ezmax_api_definition__full_field_e_error_code__UNPROCESSABLEENTITY_UNMODIFIABLE_FIELD, ezmax_api_definition__full_field_e_error_code__UNPROCESSABLEENTITY_USER_STAGED, ezmax_api_definition__full_field_e_error_code__TOOMANYREQUESTS, ezmax_api_definition__full_field_e_error_code__TOOMANYREQUESTS_THIRDPARTY, ezmax_api_definition__full_field_e_error_code__ERROR_INTERNAL, ezmax_api_definition__full_field_e_error_code__ERROR_CONFIGURATION, ezmax_api_definition__full_field_e_error_code__ERROR_NOTIMPLEMENTED } ezmax_api_definition__full_field_e_error_code__e;

char* field_e_error_code_field_e_error_code_ToString(ezmax_api_definition__full_field_e_error_code__e field_e_error_code);

ezmax_api_definition__full_field_e_error_code__e field_e_error_code_field_e_error_code_FromString(char* field_e_error_code);

//cJSON *field_e_error_code_field_e_error_code_convertToJSON(ezmax_api_definition__full_field_e_error_code__e field_e_error_code);

//ezmax_api_definition__full_field_e_error_code__e field_e_error_code_field_e_error_code_parseFromJSON(cJSON *field_e_error_codeJSON);

#endif /* _field_e_error_code_H_ */

