/*
 * field_e_ezsignfoldertype_signaturedatedisplay.h
 *
 * How we display the date in signatures
 */

#ifndef _field_e_ezsignfoldertype_signaturedatedisplay_H_
#define _field_e_ezsignfoldertype_signaturedatedisplay_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct field_e_ezsignfoldertype_signaturedatedisplay_t field_e_ezsignfoldertype_signaturedatedisplay_t;


// Enum  for field_e_ezsignfoldertype_signaturedatedisplay

typedef enum { ezmax_api_definition__full_field_e_ezsignfoldertype_signaturedatedisplay__NULL = 0, ezmax_api_definition__full_field_e_ezsignfoldertype_signaturedatedisplay___Default, ezmax_api_definition__full_field_e_ezsignfoldertype_signaturedatedisplay__Hidden, ezmax_api_definition__full_field_e_ezsignfoldertype_signaturedatedisplay__Custom } ezmax_api_definition__full_field_e_ezsignfoldertype_signaturedatedisplay__e;

char* field_e_ezsignfoldertype_signaturedatedisplay_field_e_ezsignfoldertype_signaturedatedisplay_ToString(ezmax_api_definition__full_field_e_ezsignfoldertype_signaturedatedisplay__e field_e_ezsignfoldertype_signaturedatedisplay);

ezmax_api_definition__full_field_e_ezsignfoldertype_signaturedatedisplay__e field_e_ezsignfoldertype_signaturedatedisplay_field_e_ezsignfoldertype_signaturedatedisplay_FromString(char* field_e_ezsignfoldertype_signaturedatedisplay);

cJSON *field_e_ezsignfoldertype_signaturedatedisplay_convertToJSON(ezmax_api_definition__full_field_e_ezsignfoldertype_signaturedatedisplay__e field_e_ezsignfoldertype_signaturedatedisplay);

ezmax_api_definition__full_field_e_ezsignfoldertype_signaturedatedisplay__e field_e_ezsignfoldertype_signaturedatedisplay_parseFromJSON(cJSON *field_e_ezsignfoldertype_signaturedatedisplayJSON);

#endif /* _field_e_ezsignfoldertype_signaturedatedisplay_H_ */

