/*
 * field_e_ezsigntemplatesignature_positioningoccurence.h
 *
 * The occurence of the pattern to add the Ezsigntemplatesignature  This will be required if **eEzsigntemplatesignaturePositioning** is set to **PerCoordinates**
 */

#ifndef _field_e_ezsigntemplatesignature_positioningoccurence_H_
#define _field_e_ezsigntemplatesignature_positioningoccurence_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct field_e_ezsigntemplatesignature_positioningoccurence_t field_e_ezsigntemplatesignature_positioningoccurence_t;


// Enum  for field_e_ezsigntemplatesignature_positioningoccurence

typedef enum { ezmax_api_definition__full_field_e_ezsigntemplatesignature_positioningoccurence__NULL = 0, ezmax_api_definition__full_field_e_ezsigntemplatesignature_positioningoccurence__All, ezmax_api_definition__full_field_e_ezsigntemplatesignature_positioningoccurence__First, ezmax_api_definition__full_field_e_ezsigntemplatesignature_positioningoccurence__Last } ezmax_api_definition__full_field_e_ezsigntemplatesignature_positioningoccurence__e;

char* field_e_ezsigntemplatesignature_positioningoccurence_field_e_ezsigntemplatesignature_positioningoccurence_ToString(ezmax_api_definition__full_field_e_ezsigntemplatesignature_positioningoccurence__e field_e_ezsigntemplatesignature_positioningoccurence);

ezmax_api_definition__full_field_e_ezsigntemplatesignature_positioningoccurence__e field_e_ezsigntemplatesignature_positioningoccurence_field_e_ezsigntemplatesignature_positioningoccurence_FromString(char* field_e_ezsigntemplatesignature_positioningoccurence);

//cJSON *field_e_ezsigntemplatesignature_positioningoccurence_field_e_ezsigntemplatesignature_positioningoccurence_convertToJSON(ezmax_api_definition__full_field_e_ezsigntemplatesignature_positioningoccurence__e field_e_ezsigntemplatesignature_positioningoccurence);

//ezmax_api_definition__full_field_e_ezsigntemplatesignature_positioningoccurence__e field_e_ezsigntemplatesignature_positioningoccurence_field_e_ezsigntemplatesignature_positioningoccurence_parseFromJSON(cJSON *field_e_ezsigntemplatesignature_positioningoccurenceJSON);

#endif /* _field_e_ezsigntemplatesignature_positioningoccurence_H_ */

