/*
 * field_e_colleague_realestateinprogess.h
 *
 * The permission of the cloning user for Realestate
 */

#ifndef _field_e_colleague_realestateinprogess_H_
#define _field_e_colleague_realestateinprogess_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct field_e_colleague_realestateinprogess_t field_e_colleague_realestateinprogess_t;


// Enum  for field_e_colleague_realestateinprogess

typedef enum { ezmax_api_definition__full_field_e_colleague_realestateinprogess__NULL = 0, ezmax_api_definition__full_field_e_colleague_realestateinprogess__No, ezmax_api_definition__full_field_e_colleague_realestateinprogess__Read, ezmax_api_definition__full_field_e_colleague_realestateinprogess__Modify, ezmax_api_definition__full_field_e_colleague_realestateinprogess__Create } ezmax_api_definition__full_field_e_colleague_realestateinprogess__e;

char* field_e_colleague_realestateinprogess_field_e_colleague_realestateinprogess_ToString(ezmax_api_definition__full_field_e_colleague_realestateinprogess__e field_e_colleague_realestateinprogess);

ezmax_api_definition__full_field_e_colleague_realestateinprogess__e field_e_colleague_realestateinprogess_field_e_colleague_realestateinprogess_FromString(char* field_e_colleague_realestateinprogess);

cJSON *field_e_colleague_realestateinprogess_convertToJSON(ezmax_api_definition__full_field_e_colleague_realestateinprogess__e field_e_colleague_realestateinprogess);

ezmax_api_definition__full_field_e_colleague_realestateinprogess__e field_e_colleague_realestateinprogess_parseFromJSON(cJSON *field_e_colleague_realestateinprogessJSON);

#endif /* _field_e_colleague_realestateinprogess_H_ */

