/*
 * field_e_ezsigntemplatedocumentpagerecognition_section.h
 *
 * The section of the Ezsigntemplatedocumentpagerecognition
 */

#ifndef _field_e_ezsigntemplatedocumentpagerecognition_section_H_
#define _field_e_ezsigntemplatedocumentpagerecognition_section_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct field_e_ezsigntemplatedocumentpagerecognition_section_t field_e_ezsigntemplatedocumentpagerecognition_section_t;


// Enum  for field_e_ezsigntemplatedocumentpagerecognition_section

typedef enum { ezmax_api_definition__full_field_e_ezsigntemplatedocumentpagerecognition_section__NULL = 0, ezmax_api_definition__full_field_e_ezsigntemplatedocumentpagerecognition_section__FirstLine, ezmax_api_definition__full_field_e_ezsigntemplatedocumentpagerecognition_section__LastLine, ezmax_api_definition__full_field_e_ezsigntemplatedocumentpagerecognition_section__Page, ezmax_api_definition__full_field_e_ezsigntemplatedocumentpagerecognition_section__Region } ezmax_api_definition__full_field_e_ezsigntemplatedocumentpagerecognition_section__e;

char* field_e_ezsigntemplatedocumentpagerecognition_section_field_e_ezsigntemplatedocumentpagerecognition_section_ToString(ezmax_api_definition__full_field_e_ezsigntemplatedocumentpagerecognition_section__e field_e_ezsigntemplatedocumentpagerecognition_section);

ezmax_api_definition__full_field_e_ezsigntemplatedocumentpagerecognition_section__e field_e_ezsigntemplatedocumentpagerecognition_section_field_e_ezsigntemplatedocumentpagerecognition_section_FromString(char* field_e_ezsigntemplatedocumentpagerecognition_section);

//cJSON *field_e_ezsigntemplatedocumentpagerecognition_section_field_e_ezsigntemplatedocumentpagerecognition_section_convertToJSON(ezmax_api_definition__full_field_e_ezsigntemplatedocumentpagerecognition_section__e field_e_ezsigntemplatedocumentpagerecognition_section);

//ezmax_api_definition__full_field_e_ezsigntemplatedocumentpagerecognition_section__e field_e_ezsigntemplatedocumentpagerecognition_section_field_e_ezsigntemplatedocumentpagerecognition_section_parseFromJSON(cJSON *field_e_ezsigntemplatedocumentpagerecognition_sectionJSON);

#endif /* _field_e_ezsigntemplatedocumentpagerecognition_section_H_ */

