/*
 * field_e_ezsigntemplateformfield_dependencyrequirement.h
 *
 * The Dependency requirement of the Ezsigntemplateformfield
 */

#ifndef _field_e_ezsigntemplateformfield_dependencyrequirement_H_
#define _field_e_ezsigntemplateformfield_dependencyrequirement_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct field_e_ezsigntemplateformfield_dependencyrequirement_t field_e_ezsigntemplateformfield_dependencyrequirement_t;


// Enum  for field_e_ezsigntemplateformfield_dependencyrequirement

typedef enum { ezmax_api_definition__full_field_e_ezsigntemplateformfield_dependencyrequirement__NULL = 0, ezmax_api_definition__full_field_e_ezsigntemplateformfield_dependencyrequirement__AllOf, ezmax_api_definition__full_field_e_ezsigntemplateformfield_dependencyrequirement__AnyOf } ezmax_api_definition__full_field_e_ezsigntemplateformfield_dependencyrequirement__e;

char* field_e_ezsigntemplateformfield_dependencyrequirement_field_e_ezsigntemplateformfield_dependencyrequirement_ToString(ezmax_api_definition__full_field_e_ezsigntemplateformfield_dependencyrequirement__e field_e_ezsigntemplateformfield_dependencyrequirement);

ezmax_api_definition__full_field_e_ezsigntemplateformfield_dependencyrequirement__e field_e_ezsigntemplateformfield_dependencyrequirement_field_e_ezsigntemplateformfield_dependencyrequirement_FromString(char* field_e_ezsigntemplateformfield_dependencyrequirement);

//cJSON *field_e_ezsigntemplateformfield_dependencyrequirement_field_e_ezsigntemplateformfield_dependencyrequirement_convertToJSON(ezmax_api_definition__full_field_e_ezsigntemplateformfield_dependencyrequirement__e field_e_ezsigntemplateformfield_dependencyrequirement);

//ezmax_api_definition__full_field_e_ezsigntemplateformfield_dependencyrequirement__e field_e_ezsigntemplateformfield_dependencyrequirement_field_e_ezsigntemplateformfield_dependencyrequirement_parseFromJSON(cJSON *field_e_ezsigntemplateformfield_dependencyrequirementJSON);

#endif /* _field_e_ezsigntemplateformfield_dependencyrequirement_H_ */

