/*
 * field_e_ezsignfoldertype_disposal.h
 *
 * The type of disposal
 */

#ifndef _field_e_ezsignfoldertype_disposal_H_
#define _field_e_ezsignfoldertype_disposal_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct field_e_ezsignfoldertype_disposal_t field_e_ezsignfoldertype_disposal_t;


// Enum  for field_e_ezsignfoldertype_disposal

typedef enum { ezmax_api_definition__full_field_e_ezsignfoldertype_disposal__NULL = 0, ezmax_api_definition__full_field_e_ezsignfoldertype_disposal__No, ezmax_api_definition__full_field_e_ezsignfoldertype_disposal__Manual, ezmax_api_definition__full_field_e_ezsignfoldertype_disposal__Automatic } ezmax_api_definition__full_field_e_ezsignfoldertype_disposal__e;

char* field_e_ezsignfoldertype_disposal_field_e_ezsignfoldertype_disposal_ToString(ezmax_api_definition__full_field_e_ezsignfoldertype_disposal__e field_e_ezsignfoldertype_disposal);

ezmax_api_definition__full_field_e_ezsignfoldertype_disposal__e field_e_ezsignfoldertype_disposal_field_e_ezsignfoldertype_disposal_FromString(char* field_e_ezsignfoldertype_disposal);

cJSON *field_e_ezsignfoldertype_disposal_convertToJSON(ezmax_api_definition__full_field_e_ezsignfoldertype_disposal__e field_e_ezsignfoldertype_disposal);

ezmax_api_definition__full_field_e_ezsignfoldertype_disposal__e field_e_ezsignfoldertype_disposal_parseFromJSON(cJSON *field_e_ezsignfoldertype_disposalJSON);

#endif /* _field_e_ezsignfoldertype_disposal_H_ */

