/*
 * field_e_attachmentlog_type.h
 *
 * The Type for the Attachmentlog
 */

#ifndef _field_e_attachmentlog_type_H_
#define _field_e_attachmentlog_type_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct field_e_attachmentlog_type_t field_e_attachmentlog_type_t;


// Enum  for field_e_attachmentlog_type

typedef enum { ezmax_api_definition__full_field_e_attachmentlog_type__NULL = 0, ezmax_api_definition__full_field_e_attachmentlog_type__AutoValidation, ezmax_api_definition__full_field_e_attachmentlog_type__CopyFrom, ezmax_api_definition__full_field_e_attachmentlog_type__CopyTo, ezmax_api_definition__full_field_e_attachmentlog_type__CopyToEzsign, ezmax_api_definition__full_field_e_attachmentlog_type__CreateByEzsign, ezmax_api_definition__full_field_e_attachmentlog_type__Download, ezmax_api_definition__full_field_e_attachmentlog_type__Deleted, ezmax_api_definition__full_field_e_attachmentlog_type__Destroyed, ezmax_api_definition__full_field_e_attachmentlog_type__Email, ezmax_api_definition__full_field_e_attachmentlog_type__EmailCC, ezmax_api_definition__full_field_e_attachmentlog_type__EmailCCI, ezmax_api_definition__full_field_e_attachmentlog_type__Fax, ezmax_api_definition__full_field_e_attachmentlog_type__ImportedFromExternalSystem, ezmax_api_definition__full_field_e_attachmentlog_type__ImportedFromEZA, ezmax_api_definition__full_field_e_attachmentlog_type__ImportedFromFaltour, ezmax_api_definition__full_field_e_attachmentlog_type__ImportedFromLonewolf, ezmax_api_definition__full_field_e_attachmentlog_type__ImportedFromProspects, ezmax_api_definition__full_field_e_attachmentlog_type__Move, ezmax_api_definition__full_field_e_attachmentlog_type__OpenFromEmail, ezmax_api_definition__full_field_e_attachmentlog_type__Purged, ezmax_api_definition__full_field_e_attachmentlog_type__Reject, ezmax_api_definition__full_field_e_attachmentlog_type__Rename, ezmax_api_definition__full_field_e_attachmentlog_type__Restore, ezmax_api_definition__full_field_e_attachmentlog_type__Scanned, ezmax_api_definition__full_field_e_attachmentlog_type__SendToGED, ezmax_api_definition__full_field_e_attachmentlog_type__UnvalidatedBy, ezmax_api_definition__full_field_e_attachmentlog_type__Upload, ezmax_api_definition__full_field_e_attachmentlog_type__ValidatedBy, ezmax_api_definition__full_field_e_attachmentlog_type__VetinfoUpload } ezmax_api_definition__full_field_e_attachmentlog_type__e;

char* field_e_attachmentlog_type_field_e_attachmentlog_type_ToString(ezmax_api_definition__full_field_e_attachmentlog_type__e field_e_attachmentlog_type);

ezmax_api_definition__full_field_e_attachmentlog_type__e field_e_attachmentlog_type_field_e_attachmentlog_type_FromString(char* field_e_attachmentlog_type);

//cJSON *field_e_attachmentlog_type_field_e_attachmentlog_type_convertToJSON(ezmax_api_definition__full_field_e_attachmentlog_type__e field_e_attachmentlog_type);

//ezmax_api_definition__full_field_e_attachmentlog_type__e field_e_attachmentlog_type_field_e_attachmentlog_type_parseFromJSON(cJSON *field_e_attachmentlog_typeJSON);

#endif /* _field_e_attachmentlog_type_H_ */

