/*
 * field_e_ezsigntemplateannotation_verticalalignment.h
 *
 * The verticalalignment of the Ezsigntemplateannotation
 */

#ifndef _field_e_ezsigntemplateannotation_verticalalignment_H_
#define _field_e_ezsigntemplateannotation_verticalalignment_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct field_e_ezsigntemplateannotation_verticalalignment_t field_e_ezsigntemplateannotation_verticalalignment_t;


// Enum  for field_e_ezsigntemplateannotation_verticalalignment

typedef enum { ezmax_api_definition__full_field_e_ezsigntemplateannotation_verticalalignment__NULL = 0, ezmax_api_definition__full_field_e_ezsigntemplateannotation_verticalalignment__Bottom, ezmax_api_definition__full_field_e_ezsigntemplateannotation_verticalalignment__Middle, ezmax_api_definition__full_field_e_ezsigntemplateannotation_verticalalignment__Top } ezmax_api_definition__full_field_e_ezsigntemplateannotation_verticalalignment__e;

char* field_e_ezsigntemplateannotation_verticalalignment_field_e_ezsigntemplateannotation_verticalalignment_ToString(ezmax_api_definition__full_field_e_ezsigntemplateannotation_verticalalignment__e field_e_ezsigntemplateannotation_verticalalignment);

ezmax_api_definition__full_field_e_ezsigntemplateannotation_verticalalignment__e field_e_ezsigntemplateannotation_verticalalignment_field_e_ezsigntemplateannotation_verticalalignment_FromString(char* field_e_ezsigntemplateannotation_verticalalignment);

cJSON *field_e_ezsigntemplateannotation_verticalalignment_convertToJSON(ezmax_api_definition__full_field_e_ezsigntemplateannotation_verticalalignment__e field_e_ezsigntemplateannotation_verticalalignment);

ezmax_api_definition__full_field_e_ezsigntemplateannotation_verticalalignment__e field_e_ezsigntemplateannotation_verticalalignment_parseFromJSON(cJSON *field_e_ezsigntemplateannotation_verticalalignmentJSON);

#endif /* _field_e_ezsigntemplateannotation_verticalalignment_H_ */

