/*
 * field_e_ezsigntemplateglobaldocument_acceptationtype.h
 *
 * The acceptationtype of the Ezsigntemplateglobaldocument.
 */

#ifndef _field_e_ezsigntemplateglobaldocument_acceptationtype_H_
#define _field_e_ezsigntemplateglobaldocument_acceptationtype_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct field_e_ezsigntemplateglobaldocument_acceptationtype_t field_e_ezsigntemplateglobaldocument_acceptationtype_t;


// Enum  for field_e_ezsigntemplateglobaldocument_acceptationtype

typedef enum { ezmax_api_definition__full_field_e_ezsigntemplateglobaldocument_acceptationtype__NULL = 0, ezmax_api_definition__full_field_e_ezsigntemplateglobaldocument_acceptationtype__Blank, ezmax_api_definition__full_field_e_ezsigntemplateglobaldocument_acceptationtype__Acception, ezmax_api_definition__full_field_e_ezsigntemplateglobaldocument_acceptationtype__AcceptionCPCheckbox, ezmax_api_definition__full_field_e_ezsigntemplateglobaldocument_acceptationtype__AcceptionCPCheckboxEnhancement } ezmax_api_definition__full_field_e_ezsigntemplateglobaldocument_acceptationtype__e;

char* field_e_ezsigntemplateglobaldocument_acceptationtype_field_e_ezsigntemplateglobaldocument_acceptationtype_ToString(ezmax_api_definition__full_field_e_ezsigntemplateglobaldocument_acceptationtype__e field_e_ezsigntemplateglobaldocument_acceptationtype);

ezmax_api_definition__full_field_e_ezsigntemplateglobaldocument_acceptationtype__e field_e_ezsigntemplateglobaldocument_acceptationtype_field_e_ezsigntemplateglobaldocument_acceptationtype_FromString(char* field_e_ezsigntemplateglobaldocument_acceptationtype);

cJSON *field_e_ezsigntemplateglobaldocument_acceptationtype_convertToJSON(ezmax_api_definition__full_field_e_ezsigntemplateglobaldocument_acceptationtype__e field_e_ezsigntemplateglobaldocument_acceptationtype);

ezmax_api_definition__full_field_e_ezsigntemplateglobaldocument_acceptationtype__e field_e_ezsigntemplateglobaldocument_acceptationtype_parseFromJSON(cJSON *field_e_ezsigntemplateglobaldocument_acceptationtypeJSON);

#endif /* _field_e_ezsigntemplateglobaldocument_acceptationtype_H_ */

