/*
 * field_e_ezsignformfieldgroup_signerrequirement.h
 *
 * The Signer requirement of the Ezsignformfieldgroup. **All** means anyone can fill it, **One** means a specific person must fill it.
 */

#ifndef _field_e_ezsignformfieldgroup_signerrequirement_H_
#define _field_e_ezsignformfieldgroup_signerrequirement_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct field_e_ezsignformfieldgroup_signerrequirement_t field_e_ezsignformfieldgroup_signerrequirement_t;


// Enum  for field_e_ezsignformfieldgroup_signerrequirement

typedef enum { ezmax_api_definition_field_e_ezsignformfieldgroup_signerrequirement__NULL = 0, ezmax_api_definition_field_e_ezsignformfieldgroup_signerrequirement__All, ezmax_api_definition_field_e_ezsignformfieldgroup_signerrequirement__One } ezmax_api_definition_field_e_ezsignformfieldgroup_signerrequirement__e;

char* field_e_ezsignformfieldgroup_signerrequirement_field_e_ezsignformfieldgroup_signerrequirement_ToString(ezmax_api_definition_field_e_ezsignformfieldgroup_signerrequirement__e field_e_ezsignformfieldgroup_signerrequirement);

ezmax_api_definition_field_e_ezsignformfieldgroup_signerrequirement__e field_e_ezsignformfieldgroup_signerrequirement_field_e_ezsignformfieldgroup_signerrequirement_FromString(char* field_e_ezsignformfieldgroup_signerrequirement);

//cJSON *field_e_ezsignformfieldgroup_signerrequirement_field_e_ezsignformfieldgroup_signerrequirement_convertToJSON(ezmax_api_definition_field_e_ezsignformfieldgroup_signerrequirement__e field_e_ezsignformfieldgroup_signerrequirement);

//ezmax_api_definition_field_e_ezsignformfieldgroup_signerrequirement__e field_e_ezsignformfieldgroup_signerrequirement_field_e_ezsignformfieldgroup_signerrequirement_parseFromJSON(cJSON *field_e_ezsignformfieldgroup_signerrequirementJSON);

#endif /* _field_e_ezsignformfieldgroup_signerrequirement_H_ */

