/*
 * field_e_authenticationexternal_type.h
 *
 * The type of the Authenticationexternal
 */

#ifndef _field_e_authenticationexternal_type_H_
#define _field_e_authenticationexternal_type_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct field_e_authenticationexternal_type_t field_e_authenticationexternal_type_t;


// Enum  for field_e_authenticationexternal_type

typedef enum { ezmax_api_definition__full_field_e_authenticationexternal_type__NULL = 0, ezmax_api_definition__full_field_e_authenticationexternal_type__Salesforce, ezmax_api_definition__full_field_e_authenticationexternal_type__SalesforceSandbox } ezmax_api_definition__full_field_e_authenticationexternal_type__e;

char* field_e_authenticationexternal_type_field_e_authenticationexternal_type_ToString(ezmax_api_definition__full_field_e_authenticationexternal_type__e field_e_authenticationexternal_type);

ezmax_api_definition__full_field_e_authenticationexternal_type__e field_e_authenticationexternal_type_field_e_authenticationexternal_type_FromString(char* field_e_authenticationexternal_type);

//cJSON *field_e_authenticationexternal_type_field_e_authenticationexternal_type_convertToJSON(ezmax_api_definition__full_field_e_authenticationexternal_type__e field_e_authenticationexternal_type);

//ezmax_api_definition__full_field_e_authenticationexternal_type__e field_e_authenticationexternal_type_field_e_authenticationexternal_type_parseFromJSON(cJSON *field_e_authenticationexternal_typeJSON);

#endif /* _field_e_authenticationexternal_type_H_ */

