/*
 * field_e_contactinformations_type.h
 *
 * The type of the Contactinformations
 */

#ifndef _field_e_contactinformations_type_H_
#define _field_e_contactinformations_type_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct field_e_contactinformations_type_t field_e_contactinformations_type_t;


// Enum  for field_e_contactinformations_type

typedef enum { ezmax_api_definition__full_field_e_contactinformations_type__NULL = 0, ezmax_api_definition__full_field_e_contactinformations_type__BankAccount, ezmax_api_definition__full_field_e_contactinformations_type__ContactObject, ezmax_api_definition__full_field_e_contactinformations_type__CreditCard, ezmax_api_definition__full_field_e_contactinformations_type__Customer, ezmax_api_definition__full_field_e_contactinformations_type__ExternalBroker, ezmax_api_definition__full_field_e_contactinformations_type__ExternalBrokerFirm, ezmax_api_definition__full_field_e_contactinformations_type__EzcomCompany, ezmax_api_definition__full_field_e_contactinformations_type__FinancialInstitution, ezmax_api_definition__full_field_e_contactinformations_type__FranchiseCompany, ezmax_api_definition__full_field_e_contactinformations_type__FranchiseOffice, ezmax_api_definition__full_field_e_contactinformations_type__Supplier } ezmax_api_definition__full_field_e_contactinformations_type__e;

char* field_e_contactinformations_type_field_e_contactinformations_type_ToString(ezmax_api_definition__full_field_e_contactinformations_type__e field_e_contactinformations_type);

ezmax_api_definition__full_field_e_contactinformations_type__e field_e_contactinformations_type_field_e_contactinformations_type_FromString(char* field_e_contactinformations_type);

//cJSON *field_e_contactinformations_type_field_e_contactinformations_type_convertToJSON(ezmax_api_definition__full_field_e_contactinformations_type__e field_e_contactinformations_type);

//ezmax_api_definition__full_field_e_contactinformations_type__e field_e_contactinformations_type_field_e_contactinformations_type_parseFromJSON(cJSON *field_e_contactinformations_typeJSON);

#endif /* _field_e_contactinformations_type_H_ */

