/*
 * field_et_inscriptionnotauthenticated_mortgagetype.h
 *
 * The mortgagetype of the Inscriptionnotauthenticated
 */

#ifndef _field_et_inscriptionnotauthenticated_mortgagetype_H_
#define _field_et_inscriptionnotauthenticated_mortgagetype_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct field_et_inscriptionnotauthenticated_mortgagetype_t field_et_inscriptionnotauthenticated_mortgagetype_t;


// Enum  for field_et_inscriptionnotauthenticated_mortgagetype

typedef enum { ezmax_api_definition__full_field_et_inscriptionnotauthenticated_mortgagetype__NULL = 0, ezmax_api_definition__full_field_et_inscriptionnotauthenticated_mortgagetype__, ezmax_api_definition__full_field_et_inscriptionnotauthenticated_mortgagetype__Cash, ezmax_api_definition__full_field_et_inscriptionnotauthenticated_mortgagetype__Assumption, ezmax_api_definition__full_field_et_inscriptionnotauthenticated_mortgagetype__WithoutAgent, ezmax_api_definition__full_field_et_inscriptionnotauthenticated_mortgagetype__Institution, ezmax_api_definition__full_field_et_inscriptionnotauthenticated_mortgagetype__Agent, ezmax_api_definition__full_field_et_inscriptionnotauthenticated_mortgagetype__Broker } ezmax_api_definition__full_field_et_inscriptionnotauthenticated_mortgagetype__e;

char* field_et_inscriptionnotauthenticated_mortgagetype_field_et_inscriptionnotauthenticated_mortgagetype_ToString(ezmax_api_definition__full_field_et_inscriptionnotauthenticated_mortgagetype__e field_et_inscriptionnotauthenticated_mortgagetype);

ezmax_api_definition__full_field_et_inscriptionnotauthenticated_mortgagetype__e field_et_inscriptionnotauthenticated_mortgagetype_field_et_inscriptionnotauthenticated_mortgagetype_FromString(char* field_et_inscriptionnotauthenticated_mortgagetype);

cJSON *field_et_inscriptionnotauthenticated_mortgagetype_convertToJSON(ezmax_api_definition__full_field_et_inscriptionnotauthenticated_mortgagetype__e field_et_inscriptionnotauthenticated_mortgagetype);

ezmax_api_definition__full_field_et_inscriptionnotauthenticated_mortgagetype__e field_et_inscriptionnotauthenticated_mortgagetype_parseFromJSON(cJSON *field_et_inscriptionnotauthenticated_mortgagetypeJSON);

#endif /* _field_et_inscriptionnotauthenticated_mortgagetype_H_ */

