/*
 * field_e_systemconfiguration_language2.h
 *
 * The type of the english for the client
 */

#ifndef _field_e_systemconfiguration_language2_H_
#define _field_e_systemconfiguration_language2_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct field_e_systemconfiguration_language2_t field_e_systemconfiguration_language2_t;


// Enum  for field_e_systemconfiguration_language2

typedef enum { ezmax_api_definition__full_field_e_systemconfiguration_language2__NULL = 0, ezmax_api_definition__full_field_e_systemconfiguration_language2__en_CA, ezmax_api_definition__full_field_e_systemconfiguration_language2__en_QC, ezmax_api_definition__full_field_e_systemconfiguration_language2__en_US } ezmax_api_definition__full_field_e_systemconfiguration_language2__e;

char* field_e_systemconfiguration_language2_field_e_systemconfiguration_language2_ToString(ezmax_api_definition__full_field_e_systemconfiguration_language2__e field_e_systemconfiguration_language2);

ezmax_api_definition__full_field_e_systemconfiguration_language2__e field_e_systemconfiguration_language2_field_e_systemconfiguration_language2_FromString(char* field_e_systemconfiguration_language2);

cJSON *field_e_systemconfiguration_language2_convertToJSON(ezmax_api_definition__full_field_e_systemconfiguration_language2__e field_e_systemconfiguration_language2);

ezmax_api_definition__full_field_e_systemconfiguration_language2__e field_e_systemconfiguration_language2_parseFromJSON(cJSON *field_e_systemconfiguration_language2JSON);

#endif /* _field_e_systemconfiguration_language2_H_ */

