/*
 * field_e_ezsigntemplateformfieldgroup_type.h
 *
 * The Type of Ezsigntemplateformfieldgroup
 */

#ifndef _field_e_ezsigntemplateformfieldgroup_type_H_
#define _field_e_ezsigntemplateformfieldgroup_type_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct field_e_ezsigntemplateformfieldgroup_type_t field_e_ezsigntemplateformfieldgroup_type_t;


// Enum  for field_e_ezsigntemplateformfieldgroup_type

typedef enum { ezmax_api_definition__full_field_e_ezsigntemplateformfieldgroup_type__NULL = 0, ezmax_api_definition__full_field_e_ezsigntemplateformfieldgroup_type__Text, ezmax_api_definition__full_field_e_ezsigntemplateformfieldgroup_type__Textarea, ezmax_api_definition__full_field_e_ezsigntemplateformfieldgroup_type__Dropdown, ezmax_api_definition__full_field_e_ezsigntemplateformfieldgroup_type__Radio, ezmax_api_definition__full_field_e_ezsigntemplateformfieldgroup_type__Checkbox } ezmax_api_definition__full_field_e_ezsigntemplateformfieldgroup_type__e;

char* field_e_ezsigntemplateformfieldgroup_type_field_e_ezsigntemplateformfieldgroup_type_ToString(ezmax_api_definition__full_field_e_ezsigntemplateformfieldgroup_type__e field_e_ezsigntemplateformfieldgroup_type);

ezmax_api_definition__full_field_e_ezsigntemplateformfieldgroup_type__e field_e_ezsigntemplateformfieldgroup_type_field_e_ezsigntemplateformfieldgroup_type_FromString(char* field_e_ezsigntemplateformfieldgroup_type);

//cJSON *field_e_ezsigntemplateformfieldgroup_type_field_e_ezsigntemplateformfieldgroup_type_convertToJSON(ezmax_api_definition__full_field_e_ezsigntemplateformfieldgroup_type__e field_e_ezsigntemplateformfieldgroup_type);

//ezmax_api_definition__full_field_e_ezsigntemplateformfieldgroup_type__e field_e_ezsigntemplateformfieldgroup_type_field_e_ezsigntemplateformfieldgroup_type_parseFromJSON(cJSON *field_e_ezsigntemplateformfieldgroup_typeJSON);

#endif /* _field_e_ezsigntemplateformfieldgroup_type_H_ */

