/*
 * field_e_ezsigntemplatepublic_limittype.h
 *
 * The limittype of the Ezsigntemplatepublic
 */

#ifndef _field_e_ezsigntemplatepublic_limittype_H_
#define _field_e_ezsigntemplatepublic_limittype_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct field_e_ezsigntemplatepublic_limittype_t field_e_ezsigntemplatepublic_limittype_t;


// Enum  for field_e_ezsigntemplatepublic_limittype

typedef enum { ezmax_api_definition__full_field_e_ezsigntemplatepublic_limittype__NULL = 0, ezmax_api_definition__full_field_e_ezsigntemplatepublic_limittype__Hour, ezmax_api_definition__full_field_e_ezsigntemplatepublic_limittype__Day, ezmax_api_definition__full_field_e_ezsigntemplatepublic_limittype__Month, ezmax_api_definition__full_field_e_ezsigntemplatepublic_limittype__Total } ezmax_api_definition__full_field_e_ezsigntemplatepublic_limittype__e;

char* field_e_ezsigntemplatepublic_limittype_field_e_ezsigntemplatepublic_limittype_ToString(ezmax_api_definition__full_field_e_ezsigntemplatepublic_limittype__e field_e_ezsigntemplatepublic_limittype);

ezmax_api_definition__full_field_e_ezsigntemplatepublic_limittype__e field_e_ezsigntemplatepublic_limittype_field_e_ezsigntemplatepublic_limittype_FromString(char* field_e_ezsigntemplatepublic_limittype);

//cJSON *field_e_ezsigntemplatepublic_limittype_field_e_ezsigntemplatepublic_limittype_convertToJSON(ezmax_api_definition__full_field_e_ezsigntemplatepublic_limittype__e field_e_ezsigntemplatepublic_limittype);

//ezmax_api_definition__full_field_e_ezsigntemplatepublic_limittype__e field_e_ezsigntemplatepublic_limittype_field_e_ezsigntemplatepublic_limittype_parseFromJSON(cJSON *field_e_ezsigntemplatepublic_limittypeJSON);

#endif /* _field_e_ezsigntemplatepublic_limittype_H_ */

