/*
 * field_e_ezsigntemplateelementdependency_validation.h
 *
 * The validation type of the Ezsigntemplateelementdependency
 */

#ifndef _field_e_ezsigntemplateelementdependency_validation_H_
#define _field_e_ezsigntemplateelementdependency_validation_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct field_e_ezsigntemplateelementdependency_validation_t field_e_ezsigntemplateelementdependency_validation_t;


// Enum  for field_e_ezsigntemplateelementdependency_validation

typedef enum { ezmax_api_definition__full_field_e_ezsigntemplateelementdependency_validation__NULL = 0, ezmax_api_definition__full_field_e_ezsigntemplateelementdependency_validation__Value, ezmax_api_definition__full_field_e_ezsigntemplateelementdependency_validation__Selected, ezmax_api_definition__full_field_e_ezsigntemplateelementdependency_validation__Filled } ezmax_api_definition__full_field_e_ezsigntemplateelementdependency_validation__e;

char* field_e_ezsigntemplateelementdependency_validation_field_e_ezsigntemplateelementdependency_validation_ToString(ezmax_api_definition__full_field_e_ezsigntemplateelementdependency_validation__e field_e_ezsigntemplateelementdependency_validation);

ezmax_api_definition__full_field_e_ezsigntemplateelementdependency_validation__e field_e_ezsigntemplateelementdependency_validation_field_e_ezsigntemplateelementdependency_validation_FromString(char* field_e_ezsigntemplateelementdependency_validation);

//cJSON *field_e_ezsigntemplateelementdependency_validation_field_e_ezsigntemplateelementdependency_validation_convertToJSON(ezmax_api_definition__full_field_e_ezsigntemplateelementdependency_validation__e field_e_ezsigntemplateelementdependency_validation);

//ezmax_api_definition__full_field_e_ezsigntemplateelementdependency_validation__e field_e_ezsigntemplateelementdependency_validation_field_e_ezsigntemplateelementdependency_validation_parseFromJSON(cJSON *field_e_ezsigntemplateelementdependency_validationJSON);

#endif /* _field_e_ezsigntemplateelementdependency_validation_H_ */

