/*
 * field_e_contact_type.h
 *
 * The type of the Contact
 */

#ifndef _field_e_contact_type_H_
#define _field_e_contact_type_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct field_e_contact_type_t field_e_contact_type_t;


// Enum  for field_e_contact_type

typedef enum { ezmax_api_definition__full_field_e_contact_type__NULL = 0, ezmax_api_definition__full_field_e_contact_type__Agent, ezmax_api_definition__full_field_e_contact_type__Assistant, ezmax_api_definition__full_field_e_contact_type__BankAccount, ezmax_api_definition__full_field_e_contact_type__Borrower, ezmax_api_definition__full_field_e_contact_type__Buyer, ezmax_api_definition__full_field_e_contact_type__Company, ezmax_api_definition__full_field_e_contact_type__ContractCreator, ezmax_api_definition__full_field_e_contact_type__Creditcardmerchant, ezmax_api_definition__full_field_e_contact_type__Customer, ezmax_api_definition__full_field_e_contact_type__Depositreceipt, ezmax_api_definition__full_field_e_contact_type__Employee, ezmax_api_definition__full_field_e_contact_type__ExternalBroker, ezmax_api_definition__full_field_e_contact_type__EzsignSigner, ezmax_api_definition__full_field_e_contact_type__EzsignUser, ezmax_api_definition__full_field_e_contact_type__EzcomAgent, ezmax_api_definition__full_field_e_contact_type__EzcomApprover, ezmax_api_definition__full_field_e_contact_type__FinancialInstitution, ezmax_api_definition__full_field_e_contact_type__FranchiseBroker, ezmax_api_definition__full_field_e_contact_type__Franchisefranchisecontact, ezmax_api_definition__full_field_e_contact_type__Franchisefranchisesignatory, ezmax_api_definition__full_field_e_contact_type__FranchiseOfficeBroker, ezmax_api_definition__full_field_e_contact_type__FranchiseCompany, ezmax_api_definition__full_field_e_contact_type__FranchiseOwner, ezmax_api_definition__full_field_e_contact_type__Lead, ezmax_api_definition__full_field_e_contact_type__MarketingCampaignSample, ezmax_api_definition__full_field_e_contact_type__Notary, ezmax_api_definition__full_field_e_contact_type__Payer, ezmax_api_definition__full_field_e_contact_type__Petowner, ezmax_api_definition__full_field_e_contact_type__PrivateTo, ezmax_api_definition__full_field_e_contact_type__RewardMember, ezmax_api_definition__full_field_e_contact_type__RewardRepresentative, ezmax_api_definition__full_field_e_contact_type__Seller, ezmax_api_definition__full_field_e_contact_type__Shared, ezmax_api_definition__full_field_e_contact_type__Supplier, ezmax_api_definition__full_field_e_contact_type__Survey, ezmax_api_definition__full_field_e_contact_type__Inspector } ezmax_api_definition__full_field_e_contact_type__e;

char* field_e_contact_type_field_e_contact_type_ToString(ezmax_api_definition__full_field_e_contact_type__e field_e_contact_type);

ezmax_api_definition__full_field_e_contact_type__e field_e_contact_type_field_e_contact_type_FromString(char* field_e_contact_type);

//cJSON *field_e_contact_type_field_e_contact_type_convertToJSON(ezmax_api_definition__full_field_e_contact_type__e field_e_contact_type);

//ezmax_api_definition__full_field_e_contact_type__e field_e_contact_type_field_e_contact_type_parseFromJSON(cJSON *field_e_contact_typeJSON);

#endif /* _field_e_contact_type_H_ */

