/*
 * field_e_communicationrecipient_objecttype.h
 *
 * The object type for the Communicationrecipient
 */

#ifndef _field_e_communicationrecipient_objecttype_H_
#define _field_e_communicationrecipient_objecttype_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct field_e_communicationrecipient_objecttype_t field_e_communicationrecipient_objecttype_t;


// Enum  for field_e_communicationrecipient_objecttype

typedef enum { ezmax_api_definition__full_field_e_communicationrecipient_objecttype__NULL = 0, ezmax_api_definition__full_field_e_communicationrecipient_objecttype__Agent, ezmax_api_definition__full_field_e_communicationrecipient_objecttype__Agentincorporation, ezmax_api_definition__full_field_e_communicationrecipient_objecttype__Assistant, ezmax_api_definition__full_field_e_communicationrecipient_objecttype__Broker, ezmax_api_definition__full_field_e_communicationrecipient_objecttype__Contact, ezmax_api_definition__full_field_e_communicationrecipient_objecttype__Customer, ezmax_api_definition__full_field_e_communicationrecipient_objecttype__Employee, ezmax_api_definition__full_field_e_communicationrecipient_objecttype__Externalbroker, ezmax_api_definition__full_field_e_communicationrecipient_objecttype__Ezcomagent, ezmax_api_definition__full_field_e_communicationrecipient_objecttype__Ezcomcompany, ezmax_api_definition__full_field_e_communicationrecipient_objecttype__Ezsignsigner, ezmax_api_definition__full_field_e_communicationrecipient_objecttype__Franchiseoffice, ezmax_api_definition__full_field_e_communicationrecipient_objecttype__Notary, ezmax_api_definition__full_field_e_communicationrecipient_objecttype__Rewardmember, ezmax_api_definition__full_field_e_communicationrecipient_objecttype__Supplier, ezmax_api_definition__full_field_e_communicationrecipient_objecttype__User } ezmax_api_definition__full_field_e_communicationrecipient_objecttype__e;

char* field_e_communicationrecipient_objecttype_field_e_communicationrecipient_objecttype_ToString(ezmax_api_definition__full_field_e_communicationrecipient_objecttype__e field_e_communicationrecipient_objecttype);

ezmax_api_definition__full_field_e_communicationrecipient_objecttype__e field_e_communicationrecipient_objecttype_field_e_communicationrecipient_objecttype_FromString(char* field_e_communicationrecipient_objecttype);

//cJSON *field_e_communicationrecipient_objecttype_field_e_communicationrecipient_objecttype_convertToJSON(ezmax_api_definition__full_field_e_communicationrecipient_objecttype__e field_e_communicationrecipient_objecttype);

//ezmax_api_definition__full_field_e_communicationrecipient_objecttype__e field_e_communicationrecipient_objecttype_field_e_communicationrecipient_objecttype_parseFromJSON(cJSON *field_e_communicationrecipient_objecttypeJSON);

#endif /* _field_e_communicationrecipient_objecttype_H_ */

