/*
 * field_e_systemconfiguration_newexternaluseraction.h
 *
 * The action we do when a new external user connects itself
 */

#ifndef _field_e_systemconfiguration_newexternaluseraction_H_
#define _field_e_systemconfiguration_newexternaluseraction_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct field_e_systemconfiguration_newexternaluseraction_t field_e_systemconfiguration_newexternaluseraction_t;


// Enum  for field_e_systemconfiguration_newexternaluseraction

typedef enum { ezmax_api_definition__full_field_e_systemconfiguration_newexternaluseraction__NULL = 0, ezmax_api_definition__full_field_e_systemconfiguration_newexternaluseraction__Stage, ezmax_api_definition__full_field_e_systemconfiguration_newexternaluseraction__AutoCreate } ezmax_api_definition__full_field_e_systemconfiguration_newexternaluseraction__e;

char* field_e_systemconfiguration_newexternaluseraction_field_e_systemconfiguration_newexternaluseraction_ToString(ezmax_api_definition__full_field_e_systemconfiguration_newexternaluseraction__e field_e_systemconfiguration_newexternaluseraction);

ezmax_api_definition__full_field_e_systemconfiguration_newexternaluseraction__e field_e_systemconfiguration_newexternaluseraction_field_e_systemconfiguration_newexternaluseraction_FromString(char* field_e_systemconfiguration_newexternaluseraction);

//cJSON *field_e_systemconfiguration_newexternaluseraction_field_e_systemconfiguration_newexternaluseraction_convertToJSON(ezmax_api_definition__full_field_e_systemconfiguration_newexternaluseraction__e field_e_systemconfiguration_newexternaluseraction);

//ezmax_api_definition__full_field_e_systemconfiguration_newexternaluseraction__e field_e_systemconfiguration_newexternaluseraction_field_e_systemconfiguration_newexternaluseraction_parseFromJSON(cJSON *field_e_systemconfiguration_newexternaluseractionJSON);

#endif /* _field_e_systemconfiguration_newexternaluseraction_H_ */

