/*
 * field_e_webhook_realestateevent.h
 *
 * The realestateevent of the Webhook
 */

#ifndef _field_e_webhook_realestateevent_H_
#define _field_e_webhook_realestateevent_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct field_e_webhook_realestateevent_t field_e_webhook_realestateevent_t;


// Enum  for field_e_webhook_realestateevent

typedef enum { ezmax_api_definition__full_field_e_webhook_realestateevent__NULL = 0, ezmax_api_definition__full_field_e_webhook_realestateevent__InscriptionCreated, ezmax_api_definition__full_field_e_webhook_realestateevent__InscriptionModified, ezmax_api_definition__full_field_e_webhook_realestateevent__InscriptionnotauthenticatedCreated, ezmax_api_definition__full_field_e_webhook_realestateevent__InscriptionnotauthenticatedModified } ezmax_api_definition__full_field_e_webhook_realestateevent__e;

char* field_e_webhook_realestateevent_field_e_webhook_realestateevent_ToString(ezmax_api_definition__full_field_e_webhook_realestateevent__e field_e_webhook_realestateevent);

ezmax_api_definition__full_field_e_webhook_realestateevent__e field_e_webhook_realestateevent_field_e_webhook_realestateevent_FromString(char* field_e_webhook_realestateevent);

cJSON *field_e_webhook_realestateevent_convertToJSON(ezmax_api_definition__full_field_e_webhook_realestateevent__e field_e_webhook_realestateevent);

ezmax_api_definition__full_field_e_webhook_realestateevent__e field_e_webhook_realestateevent_parseFromJSON(cJSON *field_e_webhook_realestateeventJSON);

#endif /* _field_e_webhook_realestateevent_H_ */

