/*
 * field_e_ezsigntemplatesignature_signaturepadrequired.h
 *
 * Whether the signature pad is required or not.
 */

#ifndef _field_e_ezsigntemplatesignature_signaturepadrequired_H_
#define _field_e_ezsigntemplatesignature_signaturepadrequired_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct field_e_ezsigntemplatesignature_signaturepadrequired_t field_e_ezsigntemplatesignature_signaturepadrequired_t;


// Enum  for field_e_ezsigntemplatesignature_signaturepadrequired

typedef enum { ezmax_api_definition__full_field_e_ezsigntemplatesignature_signaturepadrequired__NULL = 0, ezmax_api_definition__full_field_e_ezsigntemplatesignature_signaturepadrequired__No, ezmax_api_definition__full_field_e_ezsigntemplatesignature_signaturepadrequired__BestEffort, ezmax_api_definition__full_field_e_ezsigntemplatesignature_signaturepadrequired__Mandatory } ezmax_api_definition__full_field_e_ezsigntemplatesignature_signaturepadrequired__e;

char* field_e_ezsigntemplatesignature_signaturepadrequired_field_e_ezsigntemplatesignature_signaturepadrequired_ToString(ezmax_api_definition__full_field_e_ezsigntemplatesignature_signaturepadrequired__e field_e_ezsigntemplatesignature_signaturepadrequired);

ezmax_api_definition__full_field_e_ezsigntemplatesignature_signaturepadrequired__e field_e_ezsigntemplatesignature_signaturepadrequired_field_e_ezsigntemplatesignature_signaturepadrequired_FromString(char* field_e_ezsigntemplatesignature_signaturepadrequired);

cJSON *field_e_ezsigntemplatesignature_signaturepadrequired_convertToJSON(ezmax_api_definition__full_field_e_ezsigntemplatesignature_signaturepadrequired__e field_e_ezsigntemplatesignature_signaturepadrequired);

ezmax_api_definition__full_field_e_ezsigntemplatesignature_signaturepadrequired__e field_e_ezsigntemplatesignature_signaturepadrequired_parseFromJSON(cJSON *field_e_ezsigntemplatesignature_signaturepadrequiredJSON);

#endif /* _field_e_ezsigntemplatesignature_signaturepadrequired_H_ */

