/*
 * field_e_ezsignsignaturepaymentdetail_taxable.h
 *
 * Whether the Ezsignsignaturepaymentdetail is taxable or not
 */

#ifndef _field_e_ezsignsignaturepaymentdetail_taxable_H_
#define _field_e_ezsignsignaturepaymentdetail_taxable_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct field_e_ezsignsignaturepaymentdetail_taxable_t field_e_ezsignsignaturepaymentdetail_taxable_t;


// Enum  for field_e_ezsignsignaturepaymentdetail_taxable

typedef enum { ezmax_api_definition__full_field_e_ezsignsignaturepaymentdetail_taxable__NULL = 0, ezmax_api_definition__full_field_e_ezsignsignaturepaymentdetail_taxable__Yes, ezmax_api_definition__full_field_e_ezsignsignaturepaymentdetail_taxable__No, ezmax_api_definition__full_field_e_ezsignsignaturepaymentdetail_taxable__Included } ezmax_api_definition__full_field_e_ezsignsignaturepaymentdetail_taxable__e;

char* field_e_ezsignsignaturepaymentdetail_taxable_field_e_ezsignsignaturepaymentdetail_taxable_ToString(ezmax_api_definition__full_field_e_ezsignsignaturepaymentdetail_taxable__e field_e_ezsignsignaturepaymentdetail_taxable);

ezmax_api_definition__full_field_e_ezsignsignaturepaymentdetail_taxable__e field_e_ezsignsignaturepaymentdetail_taxable_field_e_ezsignsignaturepaymentdetail_taxable_FromString(char* field_e_ezsignsignaturepaymentdetail_taxable);

cJSON *field_e_ezsignsignaturepaymentdetail_taxable_convertToJSON(ezmax_api_definition__full_field_e_ezsignsignaturepaymentdetail_taxable__e field_e_ezsignsignaturepaymentdetail_taxable);

ezmax_api_definition__full_field_e_ezsignsignaturepaymentdetail_taxable__e field_e_ezsignsignaturepaymentdetail_taxable_parseFromJSON(cJSON *field_e_ezsignsignaturepaymentdetail_taxableJSON);

#endif /* _field_e_ezsignsignaturepaymentdetail_taxable_H_ */

