/*
 * field_e_communication_emailimportance.h
 *
 * The importance of Email for the Communication
 */

#ifndef _field_e_communication_emailimportance_H_
#define _field_e_communication_emailimportance_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct field_e_communication_emailimportance_t field_e_communication_emailimportance_t;


// Enum  for field_e_communication_emailimportance

typedef enum { ezmax_api_definition__full_field_e_communication_emailimportance__NULL = 0, ezmax_api_definition__full_field_e_communication_emailimportance__High, ezmax_api_definition__full_field_e_communication_emailimportance__Normal, ezmax_api_definition__full_field_e_communication_emailimportance__Low } ezmax_api_definition__full_field_e_communication_emailimportance__e;

char* field_e_communication_emailimportance_field_e_communication_emailimportance_ToString(ezmax_api_definition__full_field_e_communication_emailimportance__e field_e_communication_emailimportance);

ezmax_api_definition__full_field_e_communication_emailimportance__e field_e_communication_emailimportance_field_e_communication_emailimportance_FromString(char* field_e_communication_emailimportance);

//cJSON *field_e_communication_emailimportance_field_e_communication_emailimportance_convertToJSON(ezmax_api_definition__full_field_e_communication_emailimportance__e field_e_communication_emailimportance);

//ezmax_api_definition__full_field_e_communication_emailimportance__e field_e_communication_emailimportance_field_e_communication_emailimportance_parseFromJSON(cJSON *field_e_communication_emailimportanceJSON);

#endif /* _field_e_communication_emailimportance_H_ */

