/*
 * field_e_ezsigntemplatedocumentpagerecognition_operator.h
 *
 * The operator of the Ezsigntemplatedocumentpagerecognition
 */

#ifndef _field_e_ezsigntemplatedocumentpagerecognition_operator_H_
#define _field_e_ezsigntemplatedocumentpagerecognition_operator_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct field_e_ezsigntemplatedocumentpagerecognition_operator_t field_e_ezsigntemplatedocumentpagerecognition_operator_t;


// Enum  for field_e_ezsigntemplatedocumentpagerecognition_operator

typedef enum { ezmax_api_definition__full_field_e_ezsigntemplatedocumentpagerecognition_operator__NULL = 0, ezmax_api_definition__full_field_e_ezsigntemplatedocumentpagerecognition_operator__eq, ezmax_api_definition__full_field_e_ezsigntemplatedocumentpagerecognition_operator__in, ezmax_api_definition__full_field_e_ezsigntemplatedocumentpagerecognition_operator__similar } ezmax_api_definition__full_field_e_ezsigntemplatedocumentpagerecognition_operator__e;

char* field_e_ezsigntemplatedocumentpagerecognition_operator_field_e_ezsigntemplatedocumentpagerecognition_operator_ToString(ezmax_api_definition__full_field_e_ezsigntemplatedocumentpagerecognition_operator__e field_e_ezsigntemplatedocumentpagerecognition_operator);

ezmax_api_definition__full_field_e_ezsigntemplatedocumentpagerecognition_operator__e field_e_ezsigntemplatedocumentpagerecognition_operator_field_e_ezsigntemplatedocumentpagerecognition_operator_FromString(char* field_e_ezsigntemplatedocumentpagerecognition_operator);

//cJSON *field_e_ezsigntemplatedocumentpagerecognition_operator_field_e_ezsigntemplatedocumentpagerecognition_operator_convertToJSON(ezmax_api_definition__full_field_e_ezsigntemplatedocumentpagerecognition_operator__e field_e_ezsigntemplatedocumentpagerecognition_operator);

//ezmax_api_definition__full_field_e_ezsigntemplatedocumentpagerecognition_operator__e field_e_ezsigntemplatedocumentpagerecognition_operator_field_e_ezsigntemplatedocumentpagerecognition_operator_parseFromJSON(cJSON *field_e_ezsigntemplatedocumentpagerecognition_operatorJSON);

#endif /* _field_e_ezsigntemplatedocumentpagerecognition_operator_H_ */

