/*
 * field_e_ezsignsignature_tooltipposition.h
 *
 * The location of the tooltip relative to the Ezsignsignature&#39;s location.
 */

#ifndef _field_e_ezsignsignature_tooltipposition_H_
#define _field_e_ezsignsignature_tooltipposition_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct field_e_ezsignsignature_tooltipposition_t field_e_ezsignsignature_tooltipposition_t;


// Enum  for field_e_ezsignsignature_tooltipposition

typedef enum { ezmax_api_definition__full_field_e_ezsignsignature_tooltipposition__NULL = 0, ezmax_api_definition__full_field_e_ezsignsignature_tooltipposition__TopLeft, ezmax_api_definition__full_field_e_ezsignsignature_tooltipposition__TopCenter, ezmax_api_definition__full_field_e_ezsignsignature_tooltipposition__TopRight, ezmax_api_definition__full_field_e_ezsignsignature_tooltipposition__MiddleLeft, ezmax_api_definition__full_field_e_ezsignsignature_tooltipposition__MiddleRight, ezmax_api_definition__full_field_e_ezsignsignature_tooltipposition__BottomLeft, ezmax_api_definition__full_field_e_ezsignsignature_tooltipposition__BottomCenter, ezmax_api_definition__full_field_e_ezsignsignature_tooltipposition__BottomRight } ezmax_api_definition__full_field_e_ezsignsignature_tooltipposition__e;

char* field_e_ezsignsignature_tooltipposition_field_e_ezsignsignature_tooltipposition_ToString(ezmax_api_definition__full_field_e_ezsignsignature_tooltipposition__e field_e_ezsignsignature_tooltipposition);

ezmax_api_definition__full_field_e_ezsignsignature_tooltipposition__e field_e_ezsignsignature_tooltipposition_field_e_ezsignsignature_tooltipposition_FromString(char* field_e_ezsignsignature_tooltipposition);

//cJSON *field_e_ezsignsignature_tooltipposition_field_e_ezsignsignature_tooltipposition_convertToJSON(ezmax_api_definition__full_field_e_ezsignsignature_tooltipposition__e field_e_ezsignsignature_tooltipposition);

//ezmax_api_definition__full_field_e_ezsignsignature_tooltipposition__e field_e_ezsignsignature_tooltipposition_field_e_ezsignsignature_tooltipposition_parseFromJSON(cJSON *field_e_ezsignsignature_tooltippositionJSON);

#endif /* _field_e_ezsignsignature_tooltipposition_H_ */

