/*
 * inscriptionnotauthenticated_get_communication_count_v1_response_m_payload.h
 *
 * Response for GET /1/object/inscriptionnotauthenticated/{pkiInscriptionnotauthenticatedID}/getCommunicationCount
 */

#ifndef _inscriptionnotauthenticated_get_communication_count_v1_response_m_payload_H_
#define _inscriptionnotauthenticated_get_communication_count_v1_response_m_payload_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct inscriptionnotauthenticated_get_communication_count_v1_response_m_payload_t inscriptionnotauthenticated_get_communication_count_v1_response_m_payload_t;




typedef struct inscriptionnotauthenticated_get_communication_count_v1_response_m_payload_t {
    int i_communication_count; //numeric

    int _library_owned; // Is the library responsible for freeing this object?
} inscriptionnotauthenticated_get_communication_count_v1_response_m_payload_t;

__attribute__((deprecated)) inscriptionnotauthenticated_get_communication_count_v1_response_m_payload_t *inscriptionnotauthenticated_get_communication_count_v1_response_m_payload_create(
    int i_communication_count
);

void inscriptionnotauthenticated_get_communication_count_v1_response_m_payload_free(inscriptionnotauthenticated_get_communication_count_v1_response_m_payload_t *inscriptionnotauthenticated_get_communication_count_v1_response_m_payload);

inscriptionnotauthenticated_get_communication_count_v1_response_m_payload_t *inscriptionnotauthenticated_get_communication_count_v1_response_m_payload_parseFromJSON(cJSON *inscriptionnotauthenticated_get_communication_count_v1_response_m_payloadJSON);

cJSON *inscriptionnotauthenticated_get_communication_count_v1_response_m_payload_convertToJSON(inscriptionnotauthenticated_get_communication_count_v1_response_m_payload_t *inscriptionnotauthenticated_get_communication_count_v1_response_m_payload);

#endif /* _inscriptionnotauthenticated_get_communication_count_v1_response_m_payload_H_ */

