/*
 * inscriptionnotauthenticated_fill_inscriptionnotauthenticatedcondition_v1_response.h
 *
 * Response for POST /1/object/inscriptionnotauthenticated/{pkiInscriptionnotauthenticatedID}/fillInscriptionnotauthenticatedcondition
 */

#ifndef _inscriptionnotauthenticated_fill_inscriptionnotauthenticatedcondition_v1_response_H_
#define _inscriptionnotauthenticated_fill_inscriptionnotauthenticatedcondition_v1_response_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct inscriptionnotauthenticated_fill_inscriptionnotauthenticatedcondition_v1_response_t inscriptionnotauthenticated_fill_inscriptionnotauthenticatedcondition_v1_response_t;

#include "common_response_obj_debug.h"
#include "common_response_obj_debug_payload.h"



typedef struct inscriptionnotauthenticated_fill_inscriptionnotauthenticatedcondition_v1_response_t {
    struct common_response_obj_debug_payload_t *obj_debug_payload; //model
    struct common_response_obj_debug_t *obj_debug; //model

    int _library_owned; // Is the library responsible for freeing this object?
} inscriptionnotauthenticated_fill_inscriptionnotauthenticatedcondition_v1_response_t;

__attribute__((deprecated)) inscriptionnotauthenticated_fill_inscriptionnotauthenticatedcondition_v1_response_t *inscriptionnotauthenticated_fill_inscriptionnotauthenticatedcondition_v1_response_create(
    common_response_obj_debug_payload_t *obj_debug_payload,
    common_response_obj_debug_t *obj_debug
);

void inscriptionnotauthenticated_fill_inscriptionnotauthenticatedcondition_v1_response_free(inscriptionnotauthenticated_fill_inscriptionnotauthenticatedcondition_v1_response_t *inscriptionnotauthenticated_fill_inscriptionnotauthenticatedcondition_v1_response);

inscriptionnotauthenticated_fill_inscriptionnotauthenticatedcondition_v1_response_t *inscriptionnotauthenticated_fill_inscriptionnotauthenticatedcondition_v1_response_parseFromJSON(cJSON *inscriptionnotauthenticated_fill_inscriptionnotauthenticatedcondition_v1_responseJSON);

cJSON *inscriptionnotauthenticated_fill_inscriptionnotauthenticatedcondition_v1_response_convertToJSON(inscriptionnotauthenticated_fill_inscriptionnotauthenticatedcondition_v1_response_t *inscriptionnotauthenticated_fill_inscriptionnotauthenticatedcondition_v1_response);

#endif /* _inscriptionnotauthenticated_fill_inscriptionnotauthenticatedcondition_v1_response_H_ */

