/*
 * rejectedoffertopurchase_get_communicationsenders_v1_response_m_payload.h
 *
 * Response for GET /1/object/rejectedoffertopurchase/{pkiRejectedoffertopurchaseID}/getCommunicationsenders
 */

#ifndef _rejectedoffertopurchase_get_communicationsenders_v1_response_m_payload_H_
#define _rejectedoffertopurchase_get_communicationsenders_v1_response_m_payload_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct rejectedoffertopurchase_get_communicationsenders_v1_response_m_payload_t rejectedoffertopurchase_get_communicationsenders_v1_response_m_payload_t;

#include "custom_communicationsender_response.h"



typedef struct rejectedoffertopurchase_get_communicationsenders_v1_response_m_payload_t {
    list_t *a_obj_communicationsenders; //nonprimitive container

} rejectedoffertopurchase_get_communicationsenders_v1_response_m_payload_t;

rejectedoffertopurchase_get_communicationsenders_v1_response_m_payload_t *rejectedoffertopurchase_get_communicationsenders_v1_response_m_payload_create(
    list_t *a_obj_communicationsenders
);

void rejectedoffertopurchase_get_communicationsenders_v1_response_m_payload_free(rejectedoffertopurchase_get_communicationsenders_v1_response_m_payload_t *rejectedoffertopurchase_get_communicationsenders_v1_response_m_payload);

rejectedoffertopurchase_get_communicationsenders_v1_response_m_payload_t *rejectedoffertopurchase_get_communicationsenders_v1_response_m_payload_parseFromJSON(cJSON *rejectedoffertopurchase_get_communicationsenders_v1_response_m_payloadJSON);

cJSON *rejectedoffertopurchase_get_communicationsenders_v1_response_m_payload_convertToJSON(rejectedoffertopurchase_get_communicationsenders_v1_response_m_payload_t *rejectedoffertopurchase_get_communicationsenders_v1_response_m_payload);

#endif /* _rejectedoffertopurchase_get_communicationsenders_v1_response_m_payload_H_ */

