/*
 * rejectedoffertopurchase_get_communication_count_v1_response_m_payload.h
 *
 * Response for GET /1/object/ezsignfolder/{pkiEzsignfolderID}/getCommunicationCount
 */

#ifndef _rejectedoffertopurchase_get_communication_count_v1_response_m_payload_H_
#define _rejectedoffertopurchase_get_communication_count_v1_response_m_payload_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct rejectedoffertopurchase_get_communication_count_v1_response_m_payload_t rejectedoffertopurchase_get_communication_count_v1_response_m_payload_t;




typedef struct rejectedoffertopurchase_get_communication_count_v1_response_m_payload_t {
    int i_communication_count; //numeric

    int _library_owned; // Is the library responsible for freeing this object?
} rejectedoffertopurchase_get_communication_count_v1_response_m_payload_t;

__attribute__((deprecated)) rejectedoffertopurchase_get_communication_count_v1_response_m_payload_t *rejectedoffertopurchase_get_communication_count_v1_response_m_payload_create(
    int i_communication_count
);

void rejectedoffertopurchase_get_communication_count_v1_response_m_payload_free(rejectedoffertopurchase_get_communication_count_v1_response_m_payload_t *rejectedoffertopurchase_get_communication_count_v1_response_m_payload);

rejectedoffertopurchase_get_communication_count_v1_response_m_payload_t *rejectedoffertopurchase_get_communication_count_v1_response_m_payload_parseFromJSON(cJSON *rejectedoffertopurchase_get_communication_count_v1_response_m_payloadJSON);

cJSON *rejectedoffertopurchase_get_communication_count_v1_response_m_payload_convertToJSON(rejectedoffertopurchase_get_communication_count_v1_response_m_payload_t *rejectedoffertopurchase_get_communication_count_v1_response_m_payload);

#endif /* _rejectedoffertopurchase_get_communication_count_v1_response_m_payload_H_ */

