#ifndef ezsignfoldersignerassociation_create_object_v1_response_m_payload_TEST
#define ezsignfoldersignerassociation_create_object_v1_response_m_payload_TEST

// the following is to include only the main from the first c file
#ifndef TEST_MAIN
#define TEST_MAIN
#define ezsignfoldersignerassociation_create_object_v1_response_m_payload_MAIN
#endif // TEST_MAIN

#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <stdbool.h>
#include "../external/cJSON.h"

#include "../model/ezsignfoldersignerassociation_create_object_v1_response_m_payload.h"
ezsignfoldersignerassociation_create_object_v1_response_m_payload_t* instantiate_ezsignfoldersignerassociation_create_object_v1_response_m_payload(int include_optional);



ezsignfoldersignerassociation_create_object_v1_response_m_payload_t* instantiate_ezsignfoldersignerassociation_create_object_v1_response_m_payload(int include_optional) {
  ezsignfoldersignerassociation_create_object_v1_response_m_payload_t* ezsignfoldersignerassociation_create_object_v1_response_m_payload = NULL;
  if (include_optional) {
    ezsignfoldersignerassociation_create_object_v1_response_m_payload = ezsignfoldersignerassociation_create_object_v1_response_m_payload_create(
      list_create()
    );
  } else {
    ezsignfoldersignerassociation_create_object_v1_response_m_payload = ezsignfoldersignerassociation_create_object_v1_response_m_payload_create(
      list_create()
    );
  }

  return ezsignfoldersignerassociation_create_object_v1_response_m_payload;
}


#ifdef ezsignfoldersignerassociation_create_object_v1_response_m_payload_MAIN

void test_ezsignfoldersignerassociation_create_object_v1_response_m_payload(int include_optional) {
    ezsignfoldersignerassociation_create_object_v1_response_m_payload_t* ezsignfoldersignerassociation_create_object_v1_response_m_payload_1 = instantiate_ezsignfoldersignerassociation_create_object_v1_response_m_payload(include_optional);

	cJSON* jsonezsignfoldersignerassociation_create_object_v1_response_m_payload_1 = ezsignfoldersignerassociation_create_object_v1_response_m_payload_convertToJSON(ezsignfoldersignerassociation_create_object_v1_response_m_payload_1);
	printf("ezsignfoldersignerassociation_create_object_v1_response_m_payload :\n%s\n", cJSON_Print(jsonezsignfoldersignerassociation_create_object_v1_response_m_payload_1));
	ezsignfoldersignerassociation_create_object_v1_response_m_payload_t* ezsignfoldersignerassociation_create_object_v1_response_m_payload_2 = ezsignfoldersignerassociation_create_object_v1_response_m_payload_parseFromJSON(jsonezsignfoldersignerassociation_create_object_v1_response_m_payload_1);
	cJSON* jsonezsignfoldersignerassociation_create_object_v1_response_m_payload_2 = ezsignfoldersignerassociation_create_object_v1_response_m_payload_convertToJSON(ezsignfoldersignerassociation_create_object_v1_response_m_payload_2);
	printf("repeating ezsignfoldersignerassociation_create_object_v1_response_m_payload:\n%s\n", cJSON_Print(jsonezsignfoldersignerassociation_create_object_v1_response_m_payload_2));
}

int main() {
  test_ezsignfoldersignerassociation_create_object_v1_response_m_payload(1);
  test_ezsignfoldersignerassociation_create_object_v1_response_m_payload(0);

  printf("Hello world \n");
  return 0;
}

#endif // ezsignfoldersignerassociation_create_object_v1_response_m_payload_MAIN
#endif // ezsignfoldersignerassociation_create_object_v1_response_m_payload_TEST
