#ifndef ezsigntemplateformfieldgroup_create_object_v1_response_m_payload_TEST
#define ezsigntemplateformfieldgroup_create_object_v1_response_m_payload_TEST

// the following is to include only the main from the first c file
#ifndef TEST_MAIN
#define TEST_MAIN
#define ezsigntemplateformfieldgroup_create_object_v1_response_m_payload_MAIN
#endif // TEST_MAIN

#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <stdbool.h>
#include "../external/cJSON.h"

#include "../model/ezsigntemplateformfieldgroup_create_object_v1_response_m_payload.h"
ezsigntemplateformfieldgroup_create_object_v1_response_m_payload_t* instantiate_ezsigntemplateformfieldgroup_create_object_v1_response_m_payload(int include_optional);



ezsigntemplateformfieldgroup_create_object_v1_response_m_payload_t* instantiate_ezsigntemplateformfieldgroup_create_object_v1_response_m_payload(int include_optional) {
  ezsigntemplateformfieldgroup_create_object_v1_response_m_payload_t* ezsigntemplateformfieldgroup_create_object_v1_response_m_payload = NULL;
  if (include_optional) {
    ezsigntemplateformfieldgroup_create_object_v1_response_m_payload = ezsigntemplateformfieldgroup_create_object_v1_response_m_payload_create(
      list_createList()
    );
  } else {
    ezsigntemplateformfieldgroup_create_object_v1_response_m_payload = ezsigntemplateformfieldgroup_create_object_v1_response_m_payload_create(
      list_createList()
    );
  }

  return ezsigntemplateformfieldgroup_create_object_v1_response_m_payload;
}


#ifdef ezsigntemplateformfieldgroup_create_object_v1_response_m_payload_MAIN

void test_ezsigntemplateformfieldgroup_create_object_v1_response_m_payload(int include_optional) {
    ezsigntemplateformfieldgroup_create_object_v1_response_m_payload_t* ezsigntemplateformfieldgroup_create_object_v1_response_m_payload_1 = instantiate_ezsigntemplateformfieldgroup_create_object_v1_response_m_payload(include_optional);

	cJSON* jsonezsigntemplateformfieldgroup_create_object_v1_response_m_payload_1 = ezsigntemplateformfieldgroup_create_object_v1_response_m_payload_convertToJSON(ezsigntemplateformfieldgroup_create_object_v1_response_m_payload_1);
	printf("ezsigntemplateformfieldgroup_create_object_v1_response_m_payload :\n%s\n", cJSON_Print(jsonezsigntemplateformfieldgroup_create_object_v1_response_m_payload_1));
	ezsigntemplateformfieldgroup_create_object_v1_response_m_payload_t* ezsigntemplateformfieldgroup_create_object_v1_response_m_payload_2 = ezsigntemplateformfieldgroup_create_object_v1_response_m_payload_parseFromJSON(jsonezsigntemplateformfieldgroup_create_object_v1_response_m_payload_1);
	cJSON* jsonezsigntemplateformfieldgroup_create_object_v1_response_m_payload_2 = ezsigntemplateformfieldgroup_create_object_v1_response_m_payload_convertToJSON(ezsigntemplateformfieldgroup_create_object_v1_response_m_payload_2);
	printf("repeating ezsigntemplateformfieldgroup_create_object_v1_response_m_payload:\n%s\n", cJSON_Print(jsonezsigntemplateformfieldgroup_create_object_v1_response_m_payload_2));
}

int main() {
  test_ezsigntemplateformfieldgroup_create_object_v1_response_m_payload(1);
  test_ezsigntemplateformfieldgroup_create_object_v1_response_m_payload(0);

  printf("Hello world \n");
  return 0;
}

#endif // ezsigntemplateformfieldgroup_create_object_v1_response_m_payload_MAIN
#endif // ezsigntemplateformfieldgroup_create_object_v1_response_m_payload_TEST
