#ifndef ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload_TEST
#define ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload_TEST

// the following is to include only the main from the first c file
#ifndef TEST_MAIN
#define TEST_MAIN
#define ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload_MAIN
#endif // TEST_MAIN

#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <stdbool.h>
#include "../external/cJSON.h"

#include "../model/ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload.h"
ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload_t* instantiate_ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload(int include_optional);

#include "test_ezsigntemplatedocumentpagerecognition_response_compound.c"


ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload_t* instantiate_ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload(int include_optional) {
  ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload_t* ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload = NULL;
  if (include_optional) {
    ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload = ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload_create(
       // false, not to have infinite recursion
      instantiate_ezsigntemplatedocumentpagerecognition_response_compound(0)
    );
  } else {
    ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload = ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload_create(
      NULL
    );
  }

  return ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload;
}


#ifdef ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload_MAIN

void test_ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload(int include_optional) {
    ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload_t* ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload_1 = instantiate_ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload(include_optional);

	cJSON* jsonezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload_1 = ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload_convertToJSON(ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload_1);
	printf("ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload :\n%s\n", cJSON_Print(jsonezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload_1));
	ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload_t* ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload_2 = ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload_parseFromJSON(jsonezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload_1);
	cJSON* jsonezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload_2 = ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload_convertToJSON(ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload_2);
	printf("repeating ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload:\n%s\n", cJSON_Print(jsonezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload_2));
}

int main() {
  test_ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload(1);
  test_ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload(0);

  printf("Hello world \n");
  return 0;
}

#endif // ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload_MAIN
#endif // ezsigntemplatedocumentpagerecognition_get_object_v2_response_m_payload_TEST
