#ifndef ezsignsignergroupmembership_create_object_v1_response_m_payload_TEST
#define ezsignsignergroupmembership_create_object_v1_response_m_payload_TEST

// the following is to include only the main from the first c file
#ifndef TEST_MAIN
#define TEST_MAIN
#define ezsignsignergroupmembership_create_object_v1_response_m_payload_MAIN
#endif // TEST_MAIN

#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <stdbool.h>
#include "../external/cJSON.h"

#include "../model/ezsignsignergroupmembership_create_object_v1_response_m_payload.h"
ezsignsignergroupmembership_create_object_v1_response_m_payload_t* instantiate_ezsignsignergroupmembership_create_object_v1_response_m_payload(int include_optional);



ezsignsignergroupmembership_create_object_v1_response_m_payload_t* instantiate_ezsignsignergroupmembership_create_object_v1_response_m_payload(int include_optional) {
  ezsignsignergroupmembership_create_object_v1_response_m_payload_t* ezsignsignergroupmembership_create_object_v1_response_m_payload = NULL;
  if (include_optional) {
    ezsignsignergroupmembership_create_object_v1_response_m_payload = ezsignsignergroupmembership_create_object_v1_response_m_payload_create(
      list_createList()
    );
  } else {
    ezsignsignergroupmembership_create_object_v1_response_m_payload = ezsignsignergroupmembership_create_object_v1_response_m_payload_create(
      list_createList()
    );
  }

  return ezsignsignergroupmembership_create_object_v1_response_m_payload;
}


#ifdef ezsignsignergroupmembership_create_object_v1_response_m_payload_MAIN

void test_ezsignsignergroupmembership_create_object_v1_response_m_payload(int include_optional) {
    ezsignsignergroupmembership_create_object_v1_response_m_payload_t* ezsignsignergroupmembership_create_object_v1_response_m_payload_1 = instantiate_ezsignsignergroupmembership_create_object_v1_response_m_payload(include_optional);

	cJSON* jsonezsignsignergroupmembership_create_object_v1_response_m_payload_1 = ezsignsignergroupmembership_create_object_v1_response_m_payload_convertToJSON(ezsignsignergroupmembership_create_object_v1_response_m_payload_1);
	printf("ezsignsignergroupmembership_create_object_v1_response_m_payload :\n%s\n", cJSON_Print(jsonezsignsignergroupmembership_create_object_v1_response_m_payload_1));
	ezsignsignergroupmembership_create_object_v1_response_m_payload_t* ezsignsignergroupmembership_create_object_v1_response_m_payload_2 = ezsignsignergroupmembership_create_object_v1_response_m_payload_parseFromJSON(jsonezsignsignergroupmembership_create_object_v1_response_m_payload_1);
	cJSON* jsonezsignsignergroupmembership_create_object_v1_response_m_payload_2 = ezsignsignergroupmembership_create_object_v1_response_m_payload_convertToJSON(ezsignsignergroupmembership_create_object_v1_response_m_payload_2);
	printf("repeating ezsignsignergroupmembership_create_object_v1_response_m_payload:\n%s\n", cJSON_Print(jsonezsignsignergroupmembership_create_object_v1_response_m_payload_2));
}

int main() {
  test_ezsignsignergroupmembership_create_object_v1_response_m_payload(1);
  test_ezsignsignergroupmembership_create_object_v1_response_m_payload(0);

  printf("Hello world \n");
  return 0;
}

#endif // ezsignsignergroupmembership_create_object_v1_response_m_payload_MAIN
#endif // ezsignsignergroupmembership_create_object_v1_response_m_payload_TEST
