#ifndef ezsigntemplatepackagesignermembership_create_object_v1_request_TEST
#define ezsigntemplatepackagesignermembership_create_object_v1_request_TEST

// the following is to include only the main from the first c file
#ifndef TEST_MAIN
#define TEST_MAIN
#define ezsigntemplatepackagesignermembership_create_object_v1_request_MAIN
#endif // TEST_MAIN

#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <stdbool.h>
#include "../external/cJSON.h"

#include "../model/ezsigntemplatepackagesignermembership_create_object_v1_request.h"
ezsigntemplatepackagesignermembership_create_object_v1_request_t* instantiate_ezsigntemplatepackagesignermembership_create_object_v1_request(int include_optional);



ezsigntemplatepackagesignermembership_create_object_v1_request_t* instantiate_ezsigntemplatepackagesignermembership_create_object_v1_request(int include_optional) {
  ezsigntemplatepackagesignermembership_create_object_v1_request_t* ezsigntemplatepackagesignermembership_create_object_v1_request = NULL;
  if (include_optional) {
    ezsigntemplatepackagesignermembership_create_object_v1_request = ezsigntemplatepackagesignermembership_create_object_v1_request_create(
      list_createList()
    );
  } else {
    ezsigntemplatepackagesignermembership_create_object_v1_request = ezsigntemplatepackagesignermembership_create_object_v1_request_create(
      list_createList()
    );
  }

  return ezsigntemplatepackagesignermembership_create_object_v1_request;
}


#ifdef ezsigntemplatepackagesignermembership_create_object_v1_request_MAIN

void test_ezsigntemplatepackagesignermembership_create_object_v1_request(int include_optional) {
    ezsigntemplatepackagesignermembership_create_object_v1_request_t* ezsigntemplatepackagesignermembership_create_object_v1_request_1 = instantiate_ezsigntemplatepackagesignermembership_create_object_v1_request(include_optional);

	cJSON* jsonezsigntemplatepackagesignermembership_create_object_v1_request_1 = ezsigntemplatepackagesignermembership_create_object_v1_request_convertToJSON(ezsigntemplatepackagesignermembership_create_object_v1_request_1);
	printf("ezsigntemplatepackagesignermembership_create_object_v1_request :\n%s\n", cJSON_Print(jsonezsigntemplatepackagesignermembership_create_object_v1_request_1));
	ezsigntemplatepackagesignermembership_create_object_v1_request_t* ezsigntemplatepackagesignermembership_create_object_v1_request_2 = ezsigntemplatepackagesignermembership_create_object_v1_request_parseFromJSON(jsonezsigntemplatepackagesignermembership_create_object_v1_request_1);
	cJSON* jsonezsigntemplatepackagesignermembership_create_object_v1_request_2 = ezsigntemplatepackagesignermembership_create_object_v1_request_convertToJSON(ezsigntemplatepackagesignermembership_create_object_v1_request_2);
	printf("repeating ezsigntemplatepackagesignermembership_create_object_v1_request:\n%s\n", cJSON_Print(jsonezsigntemplatepackagesignermembership_create_object_v1_request_2));
}

int main() {
  test_ezsigntemplatepackagesignermembership_create_object_v1_request(1);
  test_ezsigntemplatepackagesignermembership_create_object_v1_request(0);

  printf("Hello world \n");
  return 0;
}

#endif // ezsigntemplatepackagesignermembership_create_object_v1_request_MAIN
#endif // ezsigntemplatepackagesignermembership_create_object_v1_request_TEST
