#ifndef ezsigntemplatedocumentpagerecognition_create_object_v1_response_m_payload_TEST
#define ezsigntemplatedocumentpagerecognition_create_object_v1_response_m_payload_TEST

// the following is to include only the main from the first c file
#ifndef TEST_MAIN
#define TEST_MAIN
#define ezsigntemplatedocumentpagerecognition_create_object_v1_response_m_payload_MAIN
#endif // TEST_MAIN

#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <stdbool.h>
#include "../external/cJSON.h"

#include "../model/ezsigntemplatedocumentpagerecognition_create_object_v1_response_m_payload.h"
ezsigntemplatedocumentpagerecognition_create_object_v1_response_m_payload_t* instantiate_ezsigntemplatedocumentpagerecognition_create_object_v1_response_m_payload(int include_optional);



ezsigntemplatedocumentpagerecognition_create_object_v1_response_m_payload_t* instantiate_ezsigntemplatedocumentpagerecognition_create_object_v1_response_m_payload(int include_optional) {
  ezsigntemplatedocumentpagerecognition_create_object_v1_response_m_payload_t* ezsigntemplatedocumentpagerecognition_create_object_v1_response_m_payload = NULL;
  if (include_optional) {
    ezsigntemplatedocumentpagerecognition_create_object_v1_response_m_payload = ezsigntemplatedocumentpagerecognition_create_object_v1_response_m_payload_create(
      list_createList()
    );
  } else {
    ezsigntemplatedocumentpagerecognition_create_object_v1_response_m_payload = ezsigntemplatedocumentpagerecognition_create_object_v1_response_m_payload_create(
      list_createList()
    );
  }

  return ezsigntemplatedocumentpagerecognition_create_object_v1_response_m_payload;
}


#ifdef ezsigntemplatedocumentpagerecognition_create_object_v1_response_m_payload_MAIN

void test_ezsigntemplatedocumentpagerecognition_create_object_v1_response_m_payload(int include_optional) {
    ezsigntemplatedocumentpagerecognition_create_object_v1_response_m_payload_t* ezsigntemplatedocumentpagerecognition_create_object_v1_response_m_payload_1 = instantiate_ezsigntemplatedocumentpagerecognition_create_object_v1_response_m_payload(include_optional);

	cJSON* jsonezsigntemplatedocumentpagerecognition_create_object_v1_response_m_payload_1 = ezsigntemplatedocumentpagerecognition_create_object_v1_response_m_payload_convertToJSON(ezsigntemplatedocumentpagerecognition_create_object_v1_response_m_payload_1);
	printf("ezsigntemplatedocumentpagerecognition_create_object_v1_response_m_payload :\n%s\n", cJSON_Print(jsonezsigntemplatedocumentpagerecognition_create_object_v1_response_m_payload_1));
	ezsigntemplatedocumentpagerecognition_create_object_v1_response_m_payload_t* ezsigntemplatedocumentpagerecognition_create_object_v1_response_m_payload_2 = ezsigntemplatedocumentpagerecognition_create_object_v1_response_m_payload_parseFromJSON(jsonezsigntemplatedocumentpagerecognition_create_object_v1_response_m_payload_1);
	cJSON* jsonezsigntemplatedocumentpagerecognition_create_object_v1_response_m_payload_2 = ezsigntemplatedocumentpagerecognition_create_object_v1_response_m_payload_convertToJSON(ezsigntemplatedocumentpagerecognition_create_object_v1_response_m_payload_2);
	printf("repeating ezsigntemplatedocumentpagerecognition_create_object_v1_response_m_payload:\n%s\n", cJSON_Print(jsonezsigntemplatedocumentpagerecognition_create_object_v1_response_m_payload_2));
}

int main() {
  test_ezsigntemplatedocumentpagerecognition_create_object_v1_response_m_payload(1);
  test_ezsigntemplatedocumentpagerecognition_create_object_v1_response_m_payload(0);

  printf("Hello world \n");
  return 0;
}

#endif // ezsigntemplatedocumentpagerecognition_create_object_v1_response_m_payload_MAIN
#endif // ezsigntemplatedocumentpagerecognition_create_object_v1_response_m_payload_TEST
