#ifndef ezsignfolder_import_ezsigntemplatepackage_v1_response_m_payload_TEST
#define ezsignfolder_import_ezsigntemplatepackage_v1_response_m_payload_TEST

// the following is to include only the main from the first c file
#ifndef TEST_MAIN
#define TEST_MAIN
#define ezsignfolder_import_ezsigntemplatepackage_v1_response_m_payload_MAIN
#endif // TEST_MAIN

#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <stdbool.h>
#include "../external/cJSON.h"

#include "../model/ezsignfolder_import_ezsigntemplatepackage_v1_response_m_payload.h"
ezsignfolder_import_ezsigntemplatepackage_v1_response_m_payload_t* instantiate_ezsignfolder_import_ezsigntemplatepackage_v1_response_m_payload(int include_optional);



ezsignfolder_import_ezsigntemplatepackage_v1_response_m_payload_t* instantiate_ezsignfolder_import_ezsigntemplatepackage_v1_response_m_payload(int include_optional) {
  ezsignfolder_import_ezsigntemplatepackage_v1_response_m_payload_t* ezsignfolder_import_ezsigntemplatepackage_v1_response_m_payload = NULL;
  if (include_optional) {
    ezsignfolder_import_ezsigntemplatepackage_v1_response_m_payload = ezsignfolder_import_ezsigntemplatepackage_v1_response_m_payload_create(
      list_createList()
    );
  } else {
    ezsignfolder_import_ezsigntemplatepackage_v1_response_m_payload = ezsignfolder_import_ezsigntemplatepackage_v1_response_m_payload_create(
      list_createList()
    );
  }

  return ezsignfolder_import_ezsigntemplatepackage_v1_response_m_payload;
}


#ifdef ezsignfolder_import_ezsigntemplatepackage_v1_response_m_payload_MAIN

void test_ezsignfolder_import_ezsigntemplatepackage_v1_response_m_payload(int include_optional) {
    ezsignfolder_import_ezsigntemplatepackage_v1_response_m_payload_t* ezsignfolder_import_ezsigntemplatepackage_v1_response_m_payload_1 = instantiate_ezsignfolder_import_ezsigntemplatepackage_v1_response_m_payload(include_optional);

	cJSON* jsonezsignfolder_import_ezsigntemplatepackage_v1_response_m_payload_1 = ezsignfolder_import_ezsigntemplatepackage_v1_response_m_payload_convertToJSON(ezsignfolder_import_ezsigntemplatepackage_v1_response_m_payload_1);
	printf("ezsignfolder_import_ezsigntemplatepackage_v1_response_m_payload :\n%s\n", cJSON_Print(jsonezsignfolder_import_ezsigntemplatepackage_v1_response_m_payload_1));
	ezsignfolder_import_ezsigntemplatepackage_v1_response_m_payload_t* ezsignfolder_import_ezsigntemplatepackage_v1_response_m_payload_2 = ezsignfolder_import_ezsigntemplatepackage_v1_response_m_payload_parseFromJSON(jsonezsignfolder_import_ezsigntemplatepackage_v1_response_m_payload_1);
	cJSON* jsonezsignfolder_import_ezsigntemplatepackage_v1_response_m_payload_2 = ezsignfolder_import_ezsigntemplatepackage_v1_response_m_payload_convertToJSON(ezsignfolder_import_ezsigntemplatepackage_v1_response_m_payload_2);
	printf("repeating ezsignfolder_import_ezsigntemplatepackage_v1_response_m_payload:\n%s\n", cJSON_Print(jsonezsignfolder_import_ezsigntemplatepackage_v1_response_m_payload_2));
}

int main() {
  test_ezsignfolder_import_ezsigntemplatepackage_v1_response_m_payload(1);
  test_ezsignfolder_import_ezsigntemplatepackage_v1_response_m_payload(0);

  printf("Hello world \n");
  return 0;
}

#endif // ezsignfolder_import_ezsigntemplatepackage_v1_response_m_payload_MAIN
#endif // ezsignfolder_import_ezsigntemplatepackage_v1_response_m_payload_TEST
