#ifndef ezdoctemplatefieldtypecategory_get_autocomplete_v2_response_m_payload_TEST
#define ezdoctemplatefieldtypecategory_get_autocomplete_v2_response_m_payload_TEST

// the following is to include only the main from the first c file
#ifndef TEST_MAIN
#define TEST_MAIN
#define ezdoctemplatefieldtypecategory_get_autocomplete_v2_response_m_payload_MAIN
#endif // TEST_MAIN

#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <stdbool.h>
#include "../external/cJSON.h"

#include "../model/ezdoctemplatefieldtypecategory_get_autocomplete_v2_response_m_payload.h"
ezdoctemplatefieldtypecategory_get_autocomplete_v2_response_m_payload_t* instantiate_ezdoctemplatefieldtypecategory_get_autocomplete_v2_response_m_payload(int include_optional);



ezdoctemplatefieldtypecategory_get_autocomplete_v2_response_m_payload_t* instantiate_ezdoctemplatefieldtypecategory_get_autocomplete_v2_response_m_payload(int include_optional) {
  ezdoctemplatefieldtypecategory_get_autocomplete_v2_response_m_payload_t* ezdoctemplatefieldtypecategory_get_autocomplete_v2_response_m_payload = NULL;
  if (include_optional) {
    ezdoctemplatefieldtypecategory_get_autocomplete_v2_response_m_payload = ezdoctemplatefieldtypecategory_get_autocomplete_v2_response_m_payload_create(
      list_createList()
    );
  } else {
    ezdoctemplatefieldtypecategory_get_autocomplete_v2_response_m_payload = ezdoctemplatefieldtypecategory_get_autocomplete_v2_response_m_payload_create(
      list_createList()
    );
  }

  return ezdoctemplatefieldtypecategory_get_autocomplete_v2_response_m_payload;
}


#ifdef ezdoctemplatefieldtypecategory_get_autocomplete_v2_response_m_payload_MAIN

void test_ezdoctemplatefieldtypecategory_get_autocomplete_v2_response_m_payload(int include_optional) {
    ezdoctemplatefieldtypecategory_get_autocomplete_v2_response_m_payload_t* ezdoctemplatefieldtypecategory_get_autocomplete_v2_response_m_payload_1 = instantiate_ezdoctemplatefieldtypecategory_get_autocomplete_v2_response_m_payload(include_optional);

	cJSON* jsonezdoctemplatefieldtypecategory_get_autocomplete_v2_response_m_payload_1 = ezdoctemplatefieldtypecategory_get_autocomplete_v2_response_m_payload_convertToJSON(ezdoctemplatefieldtypecategory_get_autocomplete_v2_response_m_payload_1);
	printf("ezdoctemplatefieldtypecategory_get_autocomplete_v2_response_m_payload :\n%s\n", cJSON_Print(jsonezdoctemplatefieldtypecategory_get_autocomplete_v2_response_m_payload_1));
	ezdoctemplatefieldtypecategory_get_autocomplete_v2_response_m_payload_t* ezdoctemplatefieldtypecategory_get_autocomplete_v2_response_m_payload_2 = ezdoctemplatefieldtypecategory_get_autocomplete_v2_response_m_payload_parseFromJSON(jsonezdoctemplatefieldtypecategory_get_autocomplete_v2_response_m_payload_1);
	cJSON* jsonezdoctemplatefieldtypecategory_get_autocomplete_v2_response_m_payload_2 = ezdoctemplatefieldtypecategory_get_autocomplete_v2_response_m_payload_convertToJSON(ezdoctemplatefieldtypecategory_get_autocomplete_v2_response_m_payload_2);
	printf("repeating ezdoctemplatefieldtypecategory_get_autocomplete_v2_response_m_payload:\n%s\n", cJSON_Print(jsonezdoctemplatefieldtypecategory_get_autocomplete_v2_response_m_payload_2));
}

int main() {
  test_ezdoctemplatefieldtypecategory_get_autocomplete_v2_response_m_payload(1);
  test_ezdoctemplatefieldtypecategory_get_autocomplete_v2_response_m_payload(0);

  printf("Hello world \n");
  return 0;
}

#endif // ezdoctemplatefieldtypecategory_get_autocomplete_v2_response_m_payload_MAIN
#endif // ezdoctemplatefieldtypecategory_get_autocomplete_v2_response_m_payload_TEST
