#include <stdlib.h>
#include <stdio.h>
#include "../include/apiClient.h"
#include "../include/list.h"
#include "../external/cJSON.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"
#include "../model/common_response_error.h"
#include "../model/header_accept_language.h"
#include "../model/rejectedoffertopurchase_get_communication_count_v1_response.h"
#include "../model/rejectedoffertopurchase_get_communication_list_v1_response.h"
#include "../model/rejectedoffertopurchase_get_communicationrecipients_v1_response.h"
#include "../model/rejectedoffertopurchase_get_communicationsenders_v1_response.h"
#include "../model/rejectedoffertopurchase_get_list_v1_response.h"
#include "../model/rejectedoffertopurchase_import_into_edm_v1_request.h"
#include "../model/rejectedoffertopurchase_import_into_edm_v1_response.h"

// Enum EORDERBY for ObjectRejectedoffertopurchaseAPI_rejectedoffertopurchaseGetListV1
typedef enum  { ezmax_api_definition__full_rejectedoffertopurchaseGetListV1_EORDERBY_NULL = 0, ezmax_api_definition__full_rejectedoffertopurchaseGetListV1_EORDERBY_pkiRejectedoffertopurchaseID_ASC, ezmax_api_definition__full_rejectedoffertopurchaseGetListV1_EORDERBY_pkiRejectedoffertopurchaseID_DESC, ezmax_api_definition__full_rejectedoffertopurchaseGetListV1_EORDERBY_sRejectedoffertopurchaseNumber_ASC, ezmax_api_definition__full_rejectedoffertopurchaseGetListV1_EORDERBY_sRejectedoffertopurchaseNumber_DESC, ezmax_api_definition__full_rejectedoffertopurchaseGetListV1_EORDERBY_dtRejectedoffertopurchaseDate_ASC, ezmax_api_definition__full_rejectedoffertopurchaseGetListV1_EORDERBY_dtRejectedoffertopurchaseDate_DESC, ezmax_api_definition__full_rejectedoffertopurchaseGetListV1_EORDERBY_bRejectedoffertopurchaseIsactive_ASC, ezmax_api_definition__full_rejectedoffertopurchaseGetListV1_EORDERBY_bRejectedoffertopurchaseIsactive_DESC, ezmax_api_definition__full_rejectedoffertopurchaseGetListV1_EORDERBY_bRejectedoffertopurchaseLinkedtoinscription_ASC, ezmax_api_definition__full_rejectedoffertopurchaseGetListV1_EORDERBY_bRejectedoffertopurchaseLinkedtoinscription_DESC, ezmax_api_definition__full_rejectedoffertopurchaseGetListV1_EORDERBY_dtCreatedDate_ASC, ezmax_api_definition__full_rejectedoffertopurchaseGetListV1_EORDERBY_dtCreatedDate_DESC, ezmax_api_definition__full_rejectedoffertopurchaseGetListV1_EORDERBY_sAddressCivic_ASC, ezmax_api_definition__full_rejectedoffertopurchaseGetListV1_EORDERBY_sAddressCivic_DESC, ezmax_api_definition__full_rejectedoffertopurchaseGetListV1_EORDERBY_sAddressStreet_ASC, ezmax_api_definition__full_rejectedoffertopurchaseGetListV1_EORDERBY_sAddressStreet_DESC, ezmax_api_definition__full_rejectedoffertopurchaseGetListV1_EORDERBY_sAddressSuite_ASC, ezmax_api_definition__full_rejectedoffertopurchaseGetListV1_EORDERBY_sAddressSuite_DESC, ezmax_api_definition__full_rejectedoffertopurchaseGetListV1_EORDERBY_sAddressCity_ASC, ezmax_api_definition__full_rejectedoffertopurchaseGetListV1_EORDERBY_sAddressCity_DESC, ezmax_api_definition__full_rejectedoffertopurchaseGetListV1_EORDERBY_sAddressZip_ASC, ezmax_api_definition__full_rejectedoffertopurchaseGetListV1_EORDERBY_sAddressZip_DESC, ezmax_api_definition__full_rejectedoffertopurchaseGetListV1_EORDERBY_sProvinceNameX_ASC, ezmax_api_definition__full_rejectedoffertopurchaseGetListV1_EORDERBY_sProvinceNameX_DESC, ezmax_api_definition__full_rejectedoffertopurchaseGetListV1_EORDERBY_sCountryNameX_ASC, ezmax_api_definition__full_rejectedoffertopurchaseGetListV1_EORDERBY_sCountryNameX_DESC } ezmax_api_definition__full_rejectedoffertopurchaseGetListV1_eOrderBy_e;

// Enum  for ObjectRejectedoffertopurchaseAPI_rejectedoffertopurchaseGetListV1
typedef enum  { ezmax_api_definition__full_rejectedoffertopurchaseGetListV1__NULL = 0, ezmax_api_definition__full_rejectedoffertopurchaseGetListV1__*, ezmax_api_definition__full_rejectedoffertopurchaseGetListV1__en, ezmax_api_definition__full_rejectedoffertopurchaseGetListV1__fr } ezmax_api_definition__full_rejectedoffertopurchaseGetListV1_Accept-Language_e;


// Retrieve Communication count
//
// 
//
rejectedoffertopurchase_get_communication_count_v1_response_t*
ObjectRejectedoffertopurchaseAPI_rejectedoffertopurchaseGetCommunicationCountV1(apiClient_t *apiClient, int *pkiRejectedoffertopurchaseID);


// Retrieve Communication list
//
// 
//
rejectedoffertopurchase_get_communication_list_v1_response_t*
ObjectRejectedoffertopurchaseAPI_rejectedoffertopurchaseGetCommunicationListV1(apiClient_t *apiClient, int *pkiRejectedoffertopurchaseID);


// Retrieve Rejectedoffertopurchase's Communicationrecipient
//
// 
//
rejectedoffertopurchase_get_communicationrecipients_v1_response_t*
ObjectRejectedoffertopurchaseAPI_rejectedoffertopurchaseGetCommunicationrecipientsV1(apiClient_t *apiClient, int *pkiRejectedoffertopurchaseID);


// Retrieve Rejectedoffertopurchase's Communicationsender
//
// 
//
rejectedoffertopurchase_get_communicationsenders_v1_response_t*
ObjectRejectedoffertopurchaseAPI_rejectedoffertopurchaseGetCommunicationsendersV1(apiClient_t *apiClient, int *pkiRejectedoffertopurchaseID);


// Retrieve Rejectedoffertopurchase list
//
// 
//
rejectedoffertopurchase_get_list_v1_response_t*
ObjectRejectedoffertopurchaseAPI_rejectedoffertopurchaseGetListV1(apiClient_t *apiClient, ezmax_api_definition__full_rejectedoffertopurchaseGetListV1_eOrderBy_e eOrderBy, int *iRowMax, int *iRowOffset, header_accept_language_e Accept_Language, char *sFilter);


// Import attachments into the Rejectedoffertopurchase
//
// 
//
rejectedoffertopurchase_import_into_edm_v1_response_t*
ObjectRejectedoffertopurchaseAPI_rejectedoffertopurchaseImportIntoEDMV1(apiClient_t *apiClient, int *pkiRejectedoffertopurchaseID, rejectedoffertopurchase_import_into_edm_v1_request_t *rejectedoffertopurchase_import_into_edm_v1_request);


