#include <stdlib.h>
#include <stdio.h>
#include "../include/apiClient.h"
#include "../include/list.h"
#include "../external/cJSON.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"
#include "../model/common_get_autocomplete_disabled_v1_response.h"
#include "../model/common_response_error.h"
#include "../model/ezsigntemplatepackage_create_object_v1_request.h"
#include "../model/ezsigntemplatepackage_create_object_v1_response.h"
#include "../model/ezsigntemplatepackage_delete_object_v1_response.h"
#include "../model/ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v1_request.h"
#include "../model/ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v1_response.h"
#include "../model/ezsigntemplatepackage_edit_object_v1_request.h"
#include "../model/ezsigntemplatepackage_edit_object_v1_response.h"
#include "../model/ezsigntemplatepackage_get_list_v1_response.h"
#include "../model/ezsigntemplatepackage_get_object_v1_response.h"
#include "../model/header_accept_language.h"

// Enum SSELECTOR for ObjectEzsigntemplatepackageAPI_ezsigntemplatepackageGetAutocompleteV1
typedef enum  { ezmax_api_definition__full_ezsigntemplatepackageGetAutocompleteV1_SSELECTOR_NULL = 0, ezmax_api_definition__full_ezsigntemplatepackageGetAutocompleteV1_SSELECTOR_All, ezmax_api_definition__full_ezsigntemplatepackageGetAutocompleteV1_SSELECTOR_AllMultipleCopiesDisabled } ezmax_api_definition__full_ezsigntemplatepackageGetAutocompleteV1_sSelector_e;

// Enum EFILTERACTIVE for ObjectEzsigntemplatepackageAPI_ezsigntemplatepackageGetAutocompleteV1
typedef enum  { ezmax_api_definition__full_ezsigntemplatepackageGetAutocompleteV1_EFILTERACTIVE_NULL = 0, ezmax_api_definition__full_ezsigntemplatepackageGetAutocompleteV1_EFILTERACTIVE_All, ezmax_api_definition__full_ezsigntemplatepackageGetAutocompleteV1_EFILTERACTIVE_Active, ezmax_api_definition__full_ezsigntemplatepackageGetAutocompleteV1_EFILTERACTIVE_Inactive } ezmax_api_definition__full_ezsigntemplatepackageGetAutocompleteV1_eFilterActive_e;

// Enum  for ObjectEzsigntemplatepackageAPI_ezsigntemplatepackageGetAutocompleteV1
typedef enum  { ezmax_api_definition__full_ezsigntemplatepackageGetAutocompleteV1__NULL = 0, ezmax_api_definition__full_ezsigntemplatepackageGetAutocompleteV1__*, ezmax_api_definition__full_ezsigntemplatepackageGetAutocompleteV1__en, ezmax_api_definition__full_ezsigntemplatepackageGetAutocompleteV1__fr } ezmax_api_definition__full_ezsigntemplatepackageGetAutocompleteV1_Accept-Language_e;

// Enum EORDERBY for ObjectEzsigntemplatepackageAPI_ezsigntemplatepackageGetListV1
typedef enum  { ezmax_api_definition__full_ezsigntemplatepackageGetListV1_EORDERBY_NULL = 0, ezmax_api_definition__full_ezsigntemplatepackageGetListV1_EORDERBY_pkiEzsigntemplatepackageID_ASC, ezmax_api_definition__full_ezsigntemplatepackageGetListV1_EORDERBY_pkiEzsigntemplatepackageID_DESC, ezmax_api_definition__full_ezsigntemplatepackageGetListV1_EORDERBY_fkiTeamID_ASC, ezmax_api_definition__full_ezsigntemplatepackageGetListV1_EORDERBY_fkiTeamID_DESC, ezmax_api_definition__full_ezsigntemplatepackageGetListV1_EORDERBY_fkiEzsignfoldertypeID_ASC, ezmax_api_definition__full_ezsigntemplatepackageGetListV1_EORDERBY_fkiEzsignfoldertypeID_DESC, ezmax_api_definition__full_ezsigntemplatepackageGetListV1_EORDERBY_fkiLanguageID_ASC, ezmax_api_definition__full_ezsigntemplatepackageGetListV1_EORDERBY_fkiLanguageID_DESC, ezmax_api_definition__full_ezsigntemplatepackageGetListV1_EORDERBY_eEzsigntemplatepackageType_ASC, ezmax_api_definition__full_ezsigntemplatepackageGetListV1_EORDERBY_eEzsigntemplatepackageType_DESC, ezmax_api_definition__full_ezsigntemplatepackageGetListV1_EORDERBY_sEzsigntemplatepackageTypedescriptionX_ASC, ezmax_api_definition__full_ezsigntemplatepackageGetListV1_EORDERBY_sEzsigntemplatepackageTypedescriptionX_DESC, ezmax_api_definition__full_ezsigntemplatepackageGetListV1_EORDERBY_sEzsigntemplatepackageDescription_ASC, ezmax_api_definition__full_ezsigntemplatepackageGetListV1_EORDERBY_sEzsigntemplatepackageDescription_DESC, ezmax_api_definition__full_ezsigntemplatepackageGetListV1_EORDERBY_bEzsigntemplatepackageNeedvalidation_ASC, ezmax_api_definition__full_ezsigntemplatepackageGetListV1_EORDERBY_bEzsigntemplatepackageNeedvalidation_DESC, ezmax_api_definition__full_ezsigntemplatepackageGetListV1_EORDERBY_iEzsigntemplatepackagemembership_ASC, ezmax_api_definition__full_ezsigntemplatepackageGetListV1_EORDERBY_iEzsigntemplatepackagemembership_DESC, ezmax_api_definition__full_ezsigntemplatepackageGetListV1_EORDERBY_bEzsigntemplatepackageIsactive_ASC, ezmax_api_definition__full_ezsigntemplatepackageGetListV1_EORDERBY_bEzsigntemplatepackageIsactive_DESC } ezmax_api_definition__full_ezsigntemplatepackageGetListV1_eOrderBy_e;

// Enum  for ObjectEzsigntemplatepackageAPI_ezsigntemplatepackageGetListV1
typedef enum  { ezmax_api_definition__full_ezsigntemplatepackageGetListV1__NULL = 0, ezmax_api_definition__full_ezsigntemplatepackageGetListV1__*, ezmax_api_definition__full_ezsigntemplatepackageGetListV1__en, ezmax_api_definition__full_ezsigntemplatepackageGetListV1__fr } ezmax_api_definition__full_ezsigntemplatepackageGetListV1_Accept-Language_e;


// Create a new Ezsigntemplatepackage
//
// The endpoint allows to create one or many elements at once.
//
ezsigntemplatepackage_create_object_v1_response_t*
ObjectEzsigntemplatepackageAPI_ezsigntemplatepackageCreateObjectV1(apiClient_t *apiClient, ezsigntemplatepackage_create_object_v1_request_t * ezsigntemplatepackage_create_object_v1_request );


// Delete an existing Ezsigntemplatepackage
//
// 
//
ezsigntemplatepackage_delete_object_v1_response_t*
ObjectEzsigntemplatepackageAPI_ezsigntemplatepackageDeleteObjectV1(apiClient_t *apiClient, int pkiEzsigntemplatepackageID );


// Edit multiple Ezsigntemplatepackagesigners
//
// Using this endpoint, you can edit multiple Ezsigntemplatepackagesigners at the same time.
//
ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v1_response_t*
ObjectEzsigntemplatepackageAPI_ezsigntemplatepackageEditEzsigntemplatepackagesignersV1(apiClient_t *apiClient, int pkiEzsigntemplatepackageID , ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v1_request_t * ezsigntemplatepackage_edit_ezsigntemplatepackagesigners_v1_request );


// Edit an existing Ezsigntemplatepackage
//
// 
//
ezsigntemplatepackage_edit_object_v1_response_t*
ObjectEzsigntemplatepackageAPI_ezsigntemplatepackageEditObjectV1(apiClient_t *apiClient, int pkiEzsigntemplatepackageID , ezsigntemplatepackage_edit_object_v1_request_t * ezsigntemplatepackage_edit_object_v1_request );


// Retrieve Ezsigntemplatepackages and IDs
//
// Get the list of Ezsigntemplatepackage to be used in a dropdown or autocomplete control.
//
common_get_autocomplete_disabled_v1_response_t*
ObjectEzsigntemplatepackageAPI_ezsigntemplatepackageGetAutocompleteV1(apiClient_t *apiClient, ezmax_api_definition__full_ezsigntemplatepackageGetAutocompleteV1_sSelector_e sSelector , ezmax_api_definition__full_ezsigntemplatepackageGetAutocompleteV1_eFilterActive_e eFilterActive , char * sQuery , header_accept_language_e Accept_Language );


// Retrieve Ezsigntemplatepackage list
//
// Enum values that can be filtered in query parameter *sFilter*:  | Variable | Valid values | |---|---| | eEzsigntemplatepackageType | Company<br>Team<br>User<br>Usergroup |
//
ezsigntemplatepackage_get_list_v1_response_t*
ObjectEzsigntemplatepackageAPI_ezsigntemplatepackageGetListV1(apiClient_t *apiClient, ezmax_api_definition__full_ezsigntemplatepackageGetListV1_eOrderBy_e eOrderBy , int iRowMax , int iRowOffset , header_accept_language_e Accept_Language , char * sFilter );


// Retrieve an existing Ezsigntemplatepackage
//
// 
//
ezsigntemplatepackage_get_object_v1_response_t*
ObjectEzsigntemplatepackageAPI_ezsigntemplatepackageGetObjectV1(apiClient_t *apiClient, int pkiEzsigntemplatepackageID );


