#include <stdlib.h>
#include <stdio.h>
#include "../include/apiClient.h"
#include "../include/list.h"
#include "../external/cJSON.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"
#include "../model/common_response_error.h"
#include "../model/header_accept_language.h"
#include "../model/purchase_batch_download_v1_request.h"
#include "../model/purchase_get_attachments_v1_response.h"
#include "../model/purchase_get_list_v1_response.h"
#include "../model/purchase_import_into_edm_v1_request.h"
#include "../model/purchase_import_into_edm_v1_response.h"

// Enum EORDERBY for ObjectPurchaseAPI_purchaseGetListV1
typedef enum  { ezmax_api_definition__full_purchaseGetListV1_EORDERBY_NULL = 0, ezmax_api_definition__full_purchaseGetListV1_EORDERBY_pkiPurchaseID_ASC, ezmax_api_definition__full_purchaseGetListV1_EORDERBY_pkiPurchaseID_DESC, ezmax_api_definition__full_purchaseGetListV1_EORDERBY_fkiFranchiseofficeID_ASC, ezmax_api_definition__full_purchaseGetListV1_EORDERBY_fkiFranchiseofficeID_DESC, ezmax_api_definition__full_purchaseGetListV1_EORDERBY_fkiSupplierID_ASC, ezmax_api_definition__full_purchaseGetListV1_EORDERBY_fkiSupplierID_DESC, ezmax_api_definition__full_purchaseGetListV1_EORDERBY_fkiPeriodID_ASC, ezmax_api_definition__full_purchaseGetListV1_EORDERBY_fkiPeriodID_DESC, ezmax_api_definition__full_purchaseGetListV1_EORDERBY_sPurchaseBillnumber_ASC, ezmax_api_definition__full_purchaseGetListV1_EORDERBY_sPurchaseBillnumber_DESC, ezmax_api_definition__full_purchaseGetListV1_EORDERBY_dtPurchaseDate_ASC, ezmax_api_definition__full_purchaseGetListV1_EORDERBY_dtPurchaseDate_DESC, ezmax_api_definition__full_purchaseGetListV1_EORDERBY_dtPurchasePaydate_ASC, ezmax_api_definition__full_purchaseGetListV1_EORDERBY_dtPurchasePaydate_DESC, ezmax_api_definition__full_purchaseGetListV1_EORDERBY_dPurchaseTotal_ASC, ezmax_api_definition__full_purchaseGetListV1_EORDERBY_dPurchaseTotal_DESC, ezmax_api_definition__full_purchaseGetListV1_EORDERBY_bPurchaseIsfinanced_ASC, ezmax_api_definition__full_purchaseGetListV1_EORDERBY_bPurchaseIsfinanced_DESC, ezmax_api_definition__full_purchaseGetListV1_EORDERBY_bPurchaseIspaid_ASC, ezmax_api_definition__full_purchaseGetListV1_EORDERBY_bPurchaseIspaid_DESC, ezmax_api_definition__full_purchaseGetListV1_EORDERBY_sFranchiseagenceName_ASC, ezmax_api_definition__full_purchaseGetListV1_EORDERBY_sFranchiseagenceName_DESC, ezmax_api_definition__full_purchaseGetListV1_EORDERBY_iFranchiseofficeCode_ASC, ezmax_api_definition__full_purchaseGetListV1_EORDERBY_iFranchiseofficeCode_DESC, ezmax_api_definition__full_purchaseGetListV1_EORDERBY_sSupplierName_ASC, ezmax_api_definition__full_purchaseGetListV1_EORDERBY_sSupplierName_DESC } ezmax_api_definition__full_purchaseGetListV1_eOrderBy_e;

// Enum  for ObjectPurchaseAPI_purchaseGetListV1
typedef enum  { ezmax_api_definition__full_purchaseGetListV1__NULL = 0, ezmax_api_definition__full_purchaseGetListV1__*, ezmax_api_definition__full_purchaseGetListV1__en, ezmax_api_definition__full_purchaseGetListV1__fr } ezmax_api_definition__full_purchaseGetListV1_Accept-Language_e;


// Download multiples attachments from a Purchase
//
binary_t*
ObjectPurchaseAPI_purchaseBatchDownloadV1(apiClient_t *apiClient, int *pkiPurchaseID, purchase_batch_download_v1_request_t *purchase_batch_download_v1_request);


// Retrieve Purchase's attachments
//
purchase_get_attachments_v1_response_t*
ObjectPurchaseAPI_purchaseGetAttachmentsV1(apiClient_t *apiClient, int *pkiPurchaseID);


// Retrieve Purchase list
//
// 
//
purchase_get_list_v1_response_t*
ObjectPurchaseAPI_purchaseGetListV1(apiClient_t *apiClient, ezmax_api_definition__full_purchaseGetListV1_eOrderBy_e eOrderBy, int *iRowMax, int *iRowOffset, header_accept_language_e Accept_Language, char *sFilter);


// Import attachments into the Purchase
//
purchase_import_into_edm_v1_response_t*
ObjectPurchaseAPI_purchaseImportIntoEDMV1(apiClient_t *apiClient, int *pkiPurchaseID, purchase_import_into_edm_v1_request_t *purchase_import_into_edm_v1_request);


