#include <stdlib.h>
#include <stdio.h>
#include "../include/apiClient.h"
#include "../include/list.h"
#include "../external/cJSON.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"
#include "../model/bankaccount_batch_download_v1_request.h"
#include "../model/bankaccount_get_attachments_v1_response.h"
#include "../model/bankaccount_get_autocomplete_v2_response.h"
#include "../model/bankaccount_get_communication_count_v1_response.h"
#include "../model/bankaccount_get_communication_list_v1_response.h"
#include "../model/bankaccount_get_communicationrecipients_v1_response.h"
#include "../model/bankaccount_get_communicationsenders_v1_response.h"
#include "../model/bankaccount_get_list_v1_response.h"
#include "../model/bankaccount_import_into_edm_v1_request.h"
#include "../model/bankaccount_import_into_edm_v1_response.h"
#include "../model/common_response_error.h"
#include "../model/header_accept_language.h"

// Enum SSELECTOR for ObjectBankaccountAPI_bankaccountGetAutocompleteV2
typedef enum  { ezmax_api_definition__full_bankaccountGetAutocompleteV2_SSELECTOR_NULL = 0, ezmax_api_definition__full_bankaccountGetAutocompleteV2_SSELECTOR_All } ezmax_api_definition__full_bankaccountGetAutocompleteV2_sSelector_e;

// Enum EFILTERACTIVE for ObjectBankaccountAPI_bankaccountGetAutocompleteV2
typedef enum  { ezmax_api_definition__full_bankaccountGetAutocompleteV2_EFILTERACTIVE_NULL = 0, ezmax_api_definition__full_bankaccountGetAutocompleteV2_EFILTERACTIVE_All, ezmax_api_definition__full_bankaccountGetAutocompleteV2_EFILTERACTIVE_Active, ezmax_api_definition__full_bankaccountGetAutocompleteV2_EFILTERACTIVE_Inactive } ezmax_api_definition__full_bankaccountGetAutocompleteV2_eFilterActive_e;

// Enum  for ObjectBankaccountAPI_bankaccountGetAutocompleteV2
typedef enum  { ezmax_api_definition__full_bankaccountGetAutocompleteV2__NULL = 0, ezmax_api_definition__full_bankaccountGetAutocompleteV2__*, ezmax_api_definition__full_bankaccountGetAutocompleteV2__en, ezmax_api_definition__full_bankaccountGetAutocompleteV2__fr } ezmax_api_definition__full_bankaccountGetAutocompleteV2_Accept-Language_e;

// Enum EORDERBY for ObjectBankaccountAPI_bankaccountGetListV1
typedef enum  { ezmax_api_definition__full_bankaccountGetListV1_EORDERBY_NULL = 0, ezmax_api_definition__full_bankaccountGetListV1_EORDERBY_pkiBankaccountID_ASC, ezmax_api_definition__full_bankaccountGetListV1_EORDERBY_pkiBankaccountID_DESC, ezmax_api_definition__full_bankaccountGetListV1_EORDERBY_sBankaccountBankname_ASC, ezmax_api_definition__full_bankaccountGetListV1_EORDERBY_sBankaccountBankname_DESC, ezmax_api_definition__full_bankaccountGetListV1_EORDERBY_sBankaccountTransit_ASC, ezmax_api_definition__full_bankaccountGetListV1_EORDERBY_sBankaccountTransit_DESC, ezmax_api_definition__full_bankaccountGetListV1_EORDERBY_sBankaccountInstitution_ASC, ezmax_api_definition__full_bankaccountGetListV1_EORDERBY_sBankaccountInstitution_DESC, ezmax_api_definition__full_bankaccountGetListV1_EORDERBY_sBankaccountAccount_ASC, ezmax_api_definition__full_bankaccountGetListV1_EORDERBY_sBankaccountAccount_DESC, ezmax_api_definition__full_bankaccountGetListV1_EORDERBY_sBankaccountNumber_ASC, ezmax_api_definition__full_bankaccountGetListV1_EORDERBY_sBankaccountNumber_DESC, ezmax_api_definition__full_bankaccountGetListV1_EORDERBY_eBankaccountType_ASC, ezmax_api_definition__full_bankaccountGetListV1_EORDERBY_eBankaccountType_DESC, ezmax_api_definition__full_bankaccountGetListV1_EORDERBY_bBankaccountCommissionprocessing_ASC, ezmax_api_definition__full_bankaccountGetListV1_EORDERBY_bBankaccountCommissionprocessing_DESC, ezmax_api_definition__full_bankaccountGetListV1_EORDERBY_bBankaccountIsactive_ASC, ezmax_api_definition__full_bankaccountGetListV1_EORDERBY_bBankaccountIsactive_DESC, ezmax_api_definition__full_bankaccountGetListV1_EORDERBY_iGlaccountCode_ASC, ezmax_api_definition__full_bankaccountGetListV1_EORDERBY_iGlaccountCode_DESC, ezmax_api_definition__full_bankaccountGetListV1_EORDERBY_sGlaccountDescriptionX_ASC, ezmax_api_definition__full_bankaccountGetListV1_EORDERBY_sGlaccountDescriptionX_DESC } ezmax_api_definition__full_bankaccountGetListV1_eOrderBy_e;

// Enum  for ObjectBankaccountAPI_bankaccountGetListV1
typedef enum  { ezmax_api_definition__full_bankaccountGetListV1__NULL = 0, ezmax_api_definition__full_bankaccountGetListV1__*, ezmax_api_definition__full_bankaccountGetListV1__en, ezmax_api_definition__full_bankaccountGetListV1__fr } ezmax_api_definition__full_bankaccountGetListV1_Accept-Language_e;


// Download multiples attachments from a Bankaccount
//
binary_t*
ObjectBankaccountAPI_bankaccountBatchDownloadV1(apiClient_t *apiClient, int *pkiBankaccountID, bankaccount_batch_download_v1_request_t *bankaccount_batch_download_v1_request);


// Retrieve Bankaccount's attachments
//
bankaccount_get_attachments_v1_response_t*
ObjectBankaccountAPI_bankaccountGetAttachmentsV1(apiClient_t *apiClient, int *pkiBankaccountID);


// Retrieve Bankaccounts and IDs
//
// Get the list of Bankaccount to be used in a dropdown or autocomplete control.
//
bankaccount_get_autocomplete_v2_response_t*
ObjectBankaccountAPI_bankaccountGetAutocompleteV2(apiClient_t *apiClient, ezmax_api_definition__full_bankaccountGetAutocompleteV2_sSelector_e sSelector, ezmax_api_definition__full_bankaccountGetAutocompleteV2_eFilterActive_e eFilterActive, char *sQuery, header_accept_language_e Accept_Language);


// Retrieve Communication count
//
bankaccount_get_communication_count_v1_response_t*
ObjectBankaccountAPI_bankaccountGetCommunicationCountV1(apiClient_t *apiClient, int *pkiBankaccountID);


// Retrieve Communication list
//
bankaccount_get_communication_list_v1_response_t*
ObjectBankaccountAPI_bankaccountGetCommunicationListV1(apiClient_t *apiClient, int *pkiBankaccountID);


// Retrieve Communication recipients
//
bankaccount_get_communicationrecipients_v1_response_t*
ObjectBankaccountAPI_bankaccountGetCommunicationrecipientsV1(apiClient_t *apiClient, int *pkiBankaccountID);


// Retrieve Communication senders
//
bankaccount_get_communicationsenders_v1_response_t*
ObjectBankaccountAPI_bankaccountGetCommunicationsendersV1(apiClient_t *apiClient, int *pkiBankaccountID);


// Retrieve Bankaccount list
//
// Enum values that can be filtered in query parameter *sFilter*:  | Variable | Valid values | |---|---| | eBankaccountType | Chequing<br>Trust |
//
bankaccount_get_list_v1_response_t*
ObjectBankaccountAPI_bankaccountGetListV1(apiClient_t *apiClient, ezmax_api_definition__full_bankaccountGetListV1_eOrderBy_e eOrderBy, int *iRowMax, int *iRowOffset, header_accept_language_e Accept_Language, char *sFilter);


// Import attachments into the Bankaccount
//
bankaccount_import_into_edm_v1_response_t*
ObjectBankaccountAPI_bankaccountImportIntoEDMV1(apiClient_t *apiClient, int *pkiBankaccountID, bankaccount_import_into_edm_v1_request_t *bankaccount_import_into_edm_v1_request);


