#include <stdlib.h>
#include <stdio.h>
#include "../include/apiClient.h"
#include "../include/list.h"
#include "../external/cJSON.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"
#include "../model/common_response_error.h"
#include "../model/deposit_batch_download_v1_request.h"
#include "../model/deposit_get_attachments_v1_response.h"
#include "../model/deposit_get_communication_count_v1_response.h"
#include "../model/deposit_get_communication_list_v1_response.h"
#include "../model/deposit_get_communicationrecipients_v1_response.h"
#include "../model/deposit_get_communicationsenders_v1_response.h"
#include "../model/deposit_get_list_v1_response.h"
#include "../model/deposit_import_into_edm_v1_request.h"
#include "../model/deposit_import_into_edm_v1_response.h"
#include "../model/header_accept_language.h"

// Enum EORDERBY for ObjectDepositAPI_depositGetListV1
typedef enum  { ezmax_api_definition__full_depositGetListV1_EORDERBY_NULL = 0, ezmax_api_definition__full_depositGetListV1_EORDERBY_pkiDepositID_ASC, ezmax_api_definition__full_depositGetListV1_EORDERBY_pkiDepositID_DESC, ezmax_api_definition__full_depositGetListV1_EORDERBY_fkiPeriodID_ASC, ezmax_api_definition__full_depositGetListV1_EORDERBY_fkiPeriodID_DESC, ezmax_api_definition__full_depositGetListV1_EORDERBY_fkiBankaccountID_ASC, ezmax_api_definition__full_depositGetListV1_EORDERBY_fkiBankaccountID_DESC, ezmax_api_definition__full_depositGetListV1_EORDERBY_fkiUserIDCreated_ASC, ezmax_api_definition__full_depositGetListV1_EORDERBY_fkiUserIDCreated_DESC, ezmax_api_definition__full_depositGetListV1_EORDERBY_sDepositNumber_ASC, ezmax_api_definition__full_depositGetListV1_EORDERBY_sDepositNumber_DESC, ezmax_api_definition__full_depositGetListV1_EORDERBY_dtDepositDate_ASC, ezmax_api_definition__full_depositGetListV1_EORDERBY_dtDepositDate_DESC, ezmax_api_definition__full_depositGetListV1_EORDERBY_dDepositTotal_ASC, ezmax_api_definition__full_depositGetListV1_EORDERBY_dDepositTotal_DESC, ezmax_api_definition__full_depositGetListV1_EORDERBY_dtCreatedDate_ASC, ezmax_api_definition__full_depositGetListV1_EORDERBY_dtCreatedDate_DESC, ezmax_api_definition__full_depositGetListV1_EORDERBY_bDepositDraft_ASC, ezmax_api_definition__full_depositGetListV1_EORDERBY_bDepositDraft_DESC, ezmax_api_definition__full_depositGetListV1_EORDERBY_bDepositReconciled_ASC, ezmax_api_definition__full_depositGetListV1_EORDERBY_bDepositReconciled_DESC, ezmax_api_definition__full_depositGetListV1_EORDERBY_fkiReconciliationID_ASC, ezmax_api_definition__full_depositGetListV1_EORDERBY_fkiReconciliationID_DESC, ezmax_api_definition__full_depositGetListV1_EORDERBY_sBankaccountBankname_ASC, ezmax_api_definition__full_depositGetListV1_EORDERBY_sBankaccountBankname_DESC, ezmax_api_definition__full_depositGetListV1_EORDERBY_sPeriodYYYYMM_ASC, ezmax_api_definition__full_depositGetListV1_EORDERBY_sPeriodYYYYMM_DESC, ezmax_api_definition__full_depositGetListV1_EORDERBY_sUserLoginname_ASC, ezmax_api_definition__full_depositGetListV1_EORDERBY_sUserLoginname_DESC } ezmax_api_definition__full_depositGetListV1_eOrderBy_e;

// Enum  for ObjectDepositAPI_depositGetListV1
typedef enum  { ezmax_api_definition__full_depositGetListV1__NULL = 0, ezmax_api_definition__full_depositGetListV1__*, ezmax_api_definition__full_depositGetListV1__en, ezmax_api_definition__full_depositGetListV1__fr } ezmax_api_definition__full_depositGetListV1_Accept-Language_e;


// Download multiples attachments from a Deposit
//
binary_t*
ObjectDepositAPI_depositBatchDownloadV1(apiClient_t *apiClient, int *pkiDepositID, deposit_batch_download_v1_request_t *deposit_batch_download_v1_request);


// Retrieve Deposit's attachments
//
deposit_get_attachments_v1_response_t*
ObjectDepositAPI_depositGetAttachmentsV1(apiClient_t *apiClient, int *pkiDepositID);


// Retrieve Communication count
//
deposit_get_communication_count_v1_response_t*
ObjectDepositAPI_depositGetCommunicationCountV1(apiClient_t *apiClient, int *pkiDepositID);


// Retrieve Communication list
//
deposit_get_communication_list_v1_response_t*
ObjectDepositAPI_depositGetCommunicationListV1(apiClient_t *apiClient, int *pkiDepositID);


// Retrieve Communication recipients
//
deposit_get_communicationrecipients_v1_response_t*
ObjectDepositAPI_depositGetCommunicationrecipientsV1(apiClient_t *apiClient, int *pkiDepositID);


// Retrieve Communication senders
//
deposit_get_communicationsenders_v1_response_t*
ObjectDepositAPI_depositGetCommunicationsendersV1(apiClient_t *apiClient, int *pkiDepositID);


// Retrieve Deposit list
//
// 
//
deposit_get_list_v1_response_t*
ObjectDepositAPI_depositGetListV1(apiClient_t *apiClient, ezmax_api_definition__full_depositGetListV1_eOrderBy_e eOrderBy, int *iRowMax, int *iRowOffset, header_accept_language_e Accept_Language, char *sFilter);


// Import attachments into the Deposit
//
deposit_import_into_edm_v1_response_t*
ObjectDepositAPI_depositImportIntoEDMV1(apiClient_t *apiClient, int *pkiDepositID, deposit_import_into_edm_v1_request_t *deposit_import_into_edm_v1_request);


