#include <stdlib.h>
#include <stdio.h>
#include "../include/apiClient.h"
#include "../include/list.h"
#include "../external/cJSON.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"
#include "../model/common_response_error.h"
#include "../model/communication_get_list_v1_response.h"
#include "../model/communication_get_object_v2_response.h"
#include "../model/header_accept_language.h"

// Enum EORDERBY for ObjectCommunicationAPI_communicationGetListV1
typedef enum  { ezmax_api_definition__full_communicationGetListV1_EORDERBY_NULL = 0, ezmax_api_definition__full_communicationGetListV1_EORDERBY_pkiCommunicationID_ASC, ezmax_api_definition__full_communicationGetListV1_EORDERBY_pkiCommunicationID_DESC, ezmax_api_definition__full_communicationGetListV1_EORDERBY_fkiEzsignfolderID_ASC, ezmax_api_definition__full_communicationGetListV1_EORDERBY_fkiEzsignfolderID_DESC, ezmax_api_definition__full_communicationGetListV1_EORDERBY_dtCreatedDate_ASC, ezmax_api_definition__full_communicationGetListV1_EORDERBY_dtCreatedDate_DESC, ezmax_api_definition__full_communicationGetListV1_EORDERBY_eCommunicationDirection_ASC, ezmax_api_definition__full_communicationGetListV1_EORDERBY_eCommunicationDirection_DESC, ezmax_api_definition__full_communicationGetListV1_EORDERBY_eCommunicationImportance_ASC, ezmax_api_definition__full_communicationGetListV1_EORDERBY_eCommunicationImportance_DESC, ezmax_api_definition__full_communicationGetListV1_EORDERBY_eCommunicationType_ASC, ezmax_api_definition__full_communicationGetListV1_EORDERBY_eCommunicationType_DESC, ezmax_api_definition__full_communicationGetListV1_EORDERBY_iCommunicationrecipientCount_ASC, ezmax_api_definition__full_communicationGetListV1_EORDERBY_iCommunicationrecipientCount_DESC, ezmax_api_definition__full_communicationGetListV1_EORDERBY_sCommunicationSubject_ASC, ezmax_api_definition__full_communicationGetListV1_EORDERBY_sCommunicationSubject_DESC, ezmax_api_definition__full_communicationGetListV1_EORDERBY_sCommunicationSender_ASC, ezmax_api_definition__full_communicationGetListV1_EORDERBY_sCommunicationSender_DESC, ezmax_api_definition__full_communicationGetListV1_EORDERBY_sCommunicationRecipient_ASC, ezmax_api_definition__full_communicationGetListV1_EORDERBY_sCommunicationRecipient_DESC } ezmax_api_definition__full_communicationGetListV1_eOrderBy_e;

// Enum  for ObjectCommunicationAPI_communicationGetListV1
typedef enum  { ezmax_api_definition__full_communicationGetListV1__NULL = 0, ezmax_api_definition__full_communicationGetListV1__*, ezmax_api_definition__full_communicationGetListV1__en, ezmax_api_definition__full_communicationGetListV1__fr } ezmax_api_definition__full_communicationGetListV1_Accept-Language_e;


// Retrieve Communication list
//
// Enum values that can be filtered in query parameter *sFilter*:  | Variable | Valid values | |---|---| | eCommunicationImportance | High<br>Normal<br>Low | | eCommunicationType | Email<br>Fax<br>Sms | | eCommunicationDirection | Inbound<br>Outbound |
//
communication_get_list_v1_response_t*
ObjectCommunicationAPI_communicationGetListV1(apiClient_t *apiClient, ezmax_api_definition__full_communicationGetListV1_eOrderBy_e eOrderBy , int iRowMax , int iRowOffset , header_accept_language_e Accept_Language , char * sFilter );


// Retrieve an existing Communication
//
// 
//
communication_get_object_v2_response_t*
ObjectCommunicationAPI_communicationGetObjectV2(apiClient_t *apiClient, int pkiCommunicationID );


