#include <stdlib.h>
#include <stdio.h>
#include "../include/apiClient.h"
#include "../include/list.h"
#include "../external/cJSON.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"
#include "../model/broker_batch_download_v1_request.h"
#include "../model/broker_get_attachments_v1_response.h"
#include "../model/broker_get_autocomplete_v2_response.h"
#include "../model/broker_get_list_v1_response.h"
#include "../model/broker_import_into_edm_v1_request.h"
#include "../model/broker_import_into_edm_v1_response.h"
#include "../model/common_response_error.h"
#include "../model/header_accept_language.h"

// Enum SSELECTOR for ObjectBrokerAPI_brokerGetAutocompleteV2
typedef enum  { ezmax_api_definition__full_brokerGetAutocompleteV2_SSELECTOR_NULL = 0, ezmax_api_definition__full_brokerGetAutocompleteV2_SSELECTOR_All } ezmax_api_definition__full_brokerGetAutocompleteV2_sSelector_e;

// Enum EFILTERACTIVE for ObjectBrokerAPI_brokerGetAutocompleteV2
typedef enum  { ezmax_api_definition__full_brokerGetAutocompleteV2_EFILTERACTIVE_NULL = 0, ezmax_api_definition__full_brokerGetAutocompleteV2_EFILTERACTIVE_All, ezmax_api_definition__full_brokerGetAutocompleteV2_EFILTERACTIVE_Active, ezmax_api_definition__full_brokerGetAutocompleteV2_EFILTERACTIVE_Inactive } ezmax_api_definition__full_brokerGetAutocompleteV2_eFilterActive_e;

// Enum  for ObjectBrokerAPI_brokerGetAutocompleteV2
typedef enum  { ezmax_api_definition__full_brokerGetAutocompleteV2__NULL = 0, ezmax_api_definition__full_brokerGetAutocompleteV2__*, ezmax_api_definition__full_brokerGetAutocompleteV2__en, ezmax_api_definition__full_brokerGetAutocompleteV2__fr } ezmax_api_definition__full_brokerGetAutocompleteV2_Accept-Language_e;

// Enum EORDERBY for ObjectBrokerAPI_brokerGetListV1
typedef enum  { ezmax_api_definition__full_brokerGetListV1_EORDERBY_NULL = 0, ezmax_api_definition__full_brokerGetListV1_EORDERBY_pkiBrokerID_ASC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_pkiBrokerID_DESC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_fkiDepartmentID_ASC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_fkiDepartmentID_DESC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_sDepartmentNameX_ASC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_sDepartmentNameX_DESC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_sLanguageNameX_ASC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_sLanguageNameX_DESC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_fkiBrokertypeID_ASC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_fkiBrokertypeID_DESC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_sBrokertypeNameX_ASC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_sBrokertypeNameX_DESC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_sRealestateboardnumberNumber_ASC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_sRealestateboardnumberNumber_DESC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_sBrokerCode_ASC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_sBrokerCode_DESC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_iBrokerPhotocopiercode_ASC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_iBrokerPhotocopiercode_DESC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_iBrokerLongdistancecode_ASC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_iBrokerLongdistancecode_DESC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_sBrokerName_ASC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_sBrokerName_DESC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_iAgentBannernumber_ASC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_iAgentBannernumber_DESC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_sBrokerRealestateassociationlicense_ASC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_sBrokerRealestateassociationlicense_DESC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_dtBrokerHiredate_ASC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_dtBrokerHiredate_DESC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_dtBrokerLeavedate_ASC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_dtBrokerLeavedate_DESC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_bBrokerTranquillit_ASC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_bBrokerTranquillit_DESC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_bBrokerResidentiallicense_ASC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_bBrokerResidentiallicense_DESC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_bBrokerCommerciallicense_ASC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_bBrokerCommerciallicense_DESC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_bBrokerMortgagelicense_ASC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_bBrokerMortgagelicense_DESC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_bBrokerPaidbyofficetranquillit_ASC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_bBrokerPaidbyofficetranquillit_DESC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_dtBrokerFintraccertification_ASC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_dtBrokerFintraccertification_DESC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_sContactFirstname_ASC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_sContactFirstname_DESC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_sContactLastname_ASC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_sContactLastname_DESC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_dtContactBirthdate_ASC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_dtContactBirthdate_DESC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_sEmailAddress_ASC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_sEmailAddress_DESC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_sPhoneE164_ASC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_sPhoneE164_DESC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_sAddressCivic_ASC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_sAddressCivic_DESC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_sAddressStreet_ASC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_sAddressStreet_DESC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_sAddressSuite_ASC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_sAddressSuite_DESC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_sAddressCity_ASC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_sAddressCity_DESC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_sAddressZip_ASC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_sAddressZip_DESC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_sProvinceNameX_ASC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_sProvinceNameX_DESC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_sCountryNameX_ASC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_sCountryNameX_DESC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_bBrokerIsactive_ASC, ezmax_api_definition__full_brokerGetListV1_EORDERBY_bBrokerIsactive_DESC } ezmax_api_definition__full_brokerGetListV1_eOrderBy_e;

// Enum  for ObjectBrokerAPI_brokerGetListV1
typedef enum  { ezmax_api_definition__full_brokerGetListV1__NULL = 0, ezmax_api_definition__full_brokerGetListV1__*, ezmax_api_definition__full_brokerGetListV1__en, ezmax_api_definition__full_brokerGetListV1__fr } ezmax_api_definition__full_brokerGetListV1_Accept-Language_e;


// Download multiples attachments from a Broker
//
binary_t*
ObjectBrokerAPI_brokerBatchDownloadV1(apiClient_t *apiClient, int *pkiBrokerID, broker_batch_download_v1_request_t *broker_batch_download_v1_request);


// Retrieve Broker's attachments
//
broker_get_attachments_v1_response_t*
ObjectBrokerAPI_brokerGetAttachmentsV1(apiClient_t *apiClient, int *pkiBrokerID);


// Retrieve Brokers and IDs
//
// Get the list of Broker to be used in a dropdown or autocomplete control.
//
broker_get_autocomplete_v2_response_t*
ObjectBrokerAPI_brokerGetAutocompleteV2(apiClient_t *apiClient, ezmax_api_definition__full_brokerGetAutocompleteV2_sSelector_e sSelector, ezmax_api_definition__full_brokerGetAutocompleteV2_eFilterActive_e eFilterActive, char *sQuery, header_accept_language_e Accept_Language);


// Retrieve Broker list
//
// 
//
broker_get_list_v1_response_t*
ObjectBrokerAPI_brokerGetListV1(apiClient_t *apiClient, ezmax_api_definition__full_brokerGetListV1_eOrderBy_e eOrderBy, int *iRowMax, int *iRowOffset, header_accept_language_e Accept_Language, char *sFilter);


// Import attachments into the Broker
//
// 
//
broker_import_into_edm_v1_response_t*
ObjectBrokerAPI_brokerImportIntoEDMV1(apiClient_t *apiClient, int *pkiBrokerID, broker_import_into_edm_v1_request_t *broker_import_into_edm_v1_request);


