#include <stdlib.h>
#include <stdio.h>
#include "../include/apiClient.h"
#include "../include/list.h"
#include "../external/cJSON.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"
#include "../model/agent_batch_download_v1_request.h"
#include "../model/agent_get_attachments_v1_response.h"
#include "../model/agent_get_autocomplete_v2_response.h"
#include "../model/agent_get_list_v1_response.h"
#include "../model/agent_import_into_edm_v1_request.h"
#include "../model/agent_import_into_edm_v1_response.h"
#include "../model/common_response_error.h"
#include "../model/header_accept_language.h"

// Enum SSELECTOR for ObjectAgentAPI_agentGetAutocompleteV2
typedef enum  { ezmax_api_definition__full_agentGetAutocompleteV2_SSELECTOR_NULL = 0, ezmax_api_definition__full_agentGetAutocompleteV2_SSELECTOR_All } ezmax_api_definition__full_agentGetAutocompleteV2_sSelector_e;

// Enum EFILTERACTIVE for ObjectAgentAPI_agentGetAutocompleteV2
typedef enum  { ezmax_api_definition__full_agentGetAutocompleteV2_EFILTERACTIVE_NULL = 0, ezmax_api_definition__full_agentGetAutocompleteV2_EFILTERACTIVE_All, ezmax_api_definition__full_agentGetAutocompleteV2_EFILTERACTIVE_Active, ezmax_api_definition__full_agentGetAutocompleteV2_EFILTERACTIVE_Inactive } ezmax_api_definition__full_agentGetAutocompleteV2_eFilterActive_e;

// Enum  for ObjectAgentAPI_agentGetAutocompleteV2
typedef enum  { ezmax_api_definition__full_agentGetAutocompleteV2__NULL = 0, ezmax_api_definition__full_agentGetAutocompleteV2__*, ezmax_api_definition__full_agentGetAutocompleteV2__en, ezmax_api_definition__full_agentGetAutocompleteV2__fr } ezmax_api_definition__full_agentGetAutocompleteV2_Accept-Language_e;

// Enum EORDERBY for ObjectAgentAPI_agentGetListV1
typedef enum  { ezmax_api_definition__full_agentGetListV1_EORDERBY_NULL = 0, ezmax_api_definition__full_agentGetListV1_EORDERBY_pkiAgentID_ASC, ezmax_api_definition__full_agentGetListV1_EORDERBY_pkiAgentID_DESC, ezmax_api_definition__full_agentGetListV1_EORDERBY_fkiAgenttypeID_ASC, ezmax_api_definition__full_agentGetListV1_EORDERBY_fkiAgenttypeID_DESC, ezmax_api_definition__full_agentGetListV1_EORDERBY_sAgenttypeNameX_ASC, ezmax_api_definition__full_agentGetListV1_EORDERBY_sAgenttypeNameX_DESC, ezmax_api_definition__full_agentGetListV1_EORDERBY_fkiAgentincorporationID_ASC, ezmax_api_definition__full_agentGetListV1_EORDERBY_fkiAgentincorporationID_DESC, ezmax_api_definition__full_agentGetListV1_EORDERBY_sAgentincorporationName_ASC, ezmax_api_definition__full_agentGetListV1_EORDERBY_sAgentincorporationName_DESC, ezmax_api_definition__full_agentGetListV1_EORDERBY_fkiDepartmentID_ASC, ezmax_api_definition__full_agentGetListV1_EORDERBY_fkiDepartmentID_DESC, ezmax_api_definition__full_agentGetListV1_EORDERBY_sDepartmentNameX_ASC, ezmax_api_definition__full_agentGetListV1_EORDERBY_sDepartmentNameX_DESC, ezmax_api_definition__full_agentGetListV1_EORDERBY_fkiLanguageID_ASC, ezmax_api_definition__full_agentGetListV1_EORDERBY_fkiLanguageID_DESC, ezmax_api_definition__full_agentGetListV1_EORDERBY_sLanguageNameX_ASC, ezmax_api_definition__full_agentGetListV1_EORDERBY_sLanguageNameX_DESC, ezmax_api_definition__full_agentGetListV1_EORDERBY_sRealestateboardnumberNumber_ASC, ezmax_api_definition__full_agentGetListV1_EORDERBY_sRealestateboardnumberNumber_DESC, ezmax_api_definition__full_agentGetListV1_EORDERBY_sAgentCode_ASC, ezmax_api_definition__full_agentGetListV1_EORDERBY_sAgentCode_DESC, ezmax_api_definition__full_agentGetListV1_EORDERBY_iAgentPhotocopiercode_ASC, ezmax_api_definition__full_agentGetListV1_EORDERBY_iAgentPhotocopiercode_DESC, ezmax_api_definition__full_agentGetListV1_EORDERBY_iAgentLongdistancecode_ASC, ezmax_api_definition__full_agentGetListV1_EORDERBY_iAgentLongdistancecode_DESC, ezmax_api_definition__full_agentGetListV1_EORDERBY_iAgentBannernumber_ASC, ezmax_api_definition__full_agentGetListV1_EORDERBY_iAgentBannernumber_DESC, ezmax_api_definition__full_agentGetListV1_EORDERBY_sAgentRealestateassociationlicense_ASC, ezmax_api_definition__full_agentGetListV1_EORDERBY_sAgentRealestateassociationlicense_DESC, ezmax_api_definition__full_agentGetListV1_EORDERBY_dtAgentPermitexpiration_ASC, ezmax_api_definition__full_agentGetListV1_EORDERBY_dtAgentPermitexpiration_DESC, ezmax_api_definition__full_agentGetListV1_EORDERBY_dtAgentHiredate_ASC, ezmax_api_definition__full_agentGetListV1_EORDERBY_dtAgentHiredate_DESC, ezmax_api_definition__full_agentGetListV1_EORDERBY_dtAgentLeavedate_ASC, ezmax_api_definition__full_agentGetListV1_EORDERBY_dtAgentLeavedate_DESC, ezmax_api_definition__full_agentGetListV1_EORDERBY_bAgentTranquillit_ASC, ezmax_api_definition__full_agentGetListV1_EORDERBY_bAgentTranquillit_DESC, ezmax_api_definition__full_agentGetListV1_EORDERBY_bAgentResidentiallicense_ASC, ezmax_api_definition__full_agentGetListV1_EORDERBY_bAgentResidentiallicense_DESC, ezmax_api_definition__full_agentGetListV1_EORDERBY_bAgentCommerciallicense_ASC, ezmax_api_definition__full_agentGetListV1_EORDERBY_bAgentCommerciallicense_DESC, ezmax_api_definition__full_agentGetListV1_EORDERBY_bAgentMortgagelicense_ASC, ezmax_api_definition__full_agentGetListV1_EORDERBY_bAgentMortgagelicense_DESC, ezmax_api_definition__full_agentGetListV1_EORDERBY_bAgentPaidbyofficetranquillit_ASC, ezmax_api_definition__full_agentGetListV1_EORDERBY_bAgentPaidbyofficetranquillit_DESC, ezmax_api_definition__full_agentGetListV1_EORDERBY_dtAgentFintraccertification_ASC, ezmax_api_definition__full_agentGetListV1_EORDERBY_dtAgentFintraccertification_DESC, ezmax_api_definition__full_agentGetListV1_EORDERBY_sContactFirstname_ASC, ezmax_api_definition__full_agentGetListV1_EORDERBY_sContactFirstname_DESC, ezmax_api_definition__full_agentGetListV1_EORDERBY_sContactLastname_ASC, ezmax_api_definition__full_agentGetListV1_EORDERBY_sContactLastname_DESC, ezmax_api_definition__full_agentGetListV1_EORDERBY_dtContactBirthdate_ASC, ezmax_api_definition__full_agentGetListV1_EORDERBY_dtContactBirthdate_DESC, ezmax_api_definition__full_agentGetListV1_EORDERBY_sEmailAddress_ASC, ezmax_api_definition__full_agentGetListV1_EORDERBY_sEmailAddress_DESC, ezmax_api_definition__full_agentGetListV1_EORDERBY_sPhoneE164_ASC, ezmax_api_definition__full_agentGetListV1_EORDERBY_sPhoneE164_DESC, ezmax_api_definition__full_agentGetListV1_EORDERBY_sAddressCivic_ASC, ezmax_api_definition__full_agentGetListV1_EORDERBY_sAddressCivic_DESC, ezmax_api_definition__full_agentGetListV1_EORDERBY_sAddressStreet_ASC, ezmax_api_definition__full_agentGetListV1_EORDERBY_sAddressStreet_DESC, ezmax_api_definition__full_agentGetListV1_EORDERBY_sAddressSuite_ASC, ezmax_api_definition__full_agentGetListV1_EORDERBY_sAddressSuite_DESC, ezmax_api_definition__full_agentGetListV1_EORDERBY_sAddressCity_ASC, ezmax_api_definition__full_agentGetListV1_EORDERBY_sAddressCity_DESC, ezmax_api_definition__full_agentGetListV1_EORDERBY_sAddressZip_ASC, ezmax_api_definition__full_agentGetListV1_EORDERBY_sAddressZip_DESC, ezmax_api_definition__full_agentGetListV1_EORDERBY_sProvinceNameX_ASC, ezmax_api_definition__full_agentGetListV1_EORDERBY_sProvinceNameX_DESC, ezmax_api_definition__full_agentGetListV1_EORDERBY_sCountryNameX_ASC, ezmax_api_definition__full_agentGetListV1_EORDERBY_sCountryNameX_DESC, ezmax_api_definition__full_agentGetListV1_EORDERBY_bAgentIsactive_ASC, ezmax_api_definition__full_agentGetListV1_EORDERBY_bAgentIsactive_DESC } ezmax_api_definition__full_agentGetListV1_eOrderBy_e;

// Enum  for ObjectAgentAPI_agentGetListV1
typedef enum  { ezmax_api_definition__full_agentGetListV1__NULL = 0, ezmax_api_definition__full_agentGetListV1__*, ezmax_api_definition__full_agentGetListV1__en, ezmax_api_definition__full_agentGetListV1__fr } ezmax_api_definition__full_agentGetListV1_Accept-Language_e;


// Download multiples attachments from a Agent
//
binary_t*
ObjectAgentAPI_agentBatchDownloadV1(apiClient_t *apiClient, int *pkiAgentID, agent_batch_download_v1_request_t *agent_batch_download_v1_request);


// Retrieve Agent's attachments
//
agent_get_attachments_v1_response_t*
ObjectAgentAPI_agentGetAttachmentsV1(apiClient_t *apiClient, int *pkiAgentID);


// Retrieve Agents and IDs
//
// Get the list of Agent to be used in a dropdown or autocomplete control.
//
agent_get_autocomplete_v2_response_t*
ObjectAgentAPI_agentGetAutocompleteV2(apiClient_t *apiClient, ezmax_api_definition__full_agentGetAutocompleteV2_sSelector_e sSelector, ezmax_api_definition__full_agentGetAutocompleteV2_eFilterActive_e eFilterActive, char *sQuery, header_accept_language_e Accept_Language);


// Retrieve Agent list
//
// 
//
agent_get_list_v1_response_t*
ObjectAgentAPI_agentGetListV1(apiClient_t *apiClient, ezmax_api_definition__full_agentGetListV1_eOrderBy_e eOrderBy, int *iRowMax, int *iRowOffset, header_accept_language_e Accept_Language, char *sFilter);


// Import attachments into the Agent
//
// 
//
agent_import_into_edm_v1_response_t*
ObjectAgentAPI_agentImportIntoEDMV1(apiClient_t *apiClient, int *pkiAgentID, agent_import_into_edm_v1_request_t *agent_import_into_edm_v1_request);


