#include <stdlib.h>
#include <stdio.h>
#include "../include/apiClient.h"
#include "../include/list.h"
#include "../external/cJSON.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"
#include "../model/common_response_error.h"
#include "../model/header_accept_language.h"
#include "../model/supplier_get_list_v1_response.h"
#include "../model/supplier_import_into_edm_v1_request.h"
#include "../model/supplier_import_into_edm_v1_response.h"

// Enum EORDERBY for ObjectSupplierAPI_supplierGetListV1
typedef enum  { ezmax_api_definition__full_supplierGetListV1_EORDERBY_NULL = 0, ezmax_api_definition__full_supplierGetListV1_EORDERBY_pkiSupplierID_ASC, ezmax_api_definition__full_supplierGetListV1_EORDERBY_pkiSupplierID_DESC, ezmax_api_definition__full_supplierGetListV1_EORDERBY_fkiPaymentmethodID_ASC, ezmax_api_definition__full_supplierGetListV1_EORDERBY_fkiPaymentmethodID_DESC, ezmax_api_definition__full_supplierGetListV1_EORDERBY_sSupplierName_ASC, ezmax_api_definition__full_supplierGetListV1_EORDERBY_sSupplierName_DESC, ezmax_api_definition__full_supplierGetListV1_EORDERBY_sSupplierCode_ASC, ezmax_api_definition__full_supplierGetListV1_EORDERBY_sSupplierCode_DESC, ezmax_api_definition__full_supplierGetListV1_EORDERBY_sSupplierAccount_ASC, ezmax_api_definition__full_supplierGetListV1_EORDERBY_sSupplierAccount_DESC, ezmax_api_definition__full_supplierGetListV1_EORDERBY_bSupplierIsactive_ASC, ezmax_api_definition__full_supplierGetListV1_EORDERBY_bSupplierIsactive_DESC, ezmax_api_definition__full_supplierGetListV1_EORDERBY_sEmailAddress_ASC, ezmax_api_definition__full_supplierGetListV1_EORDERBY_sEmailAddress_DESC, ezmax_api_definition__full_supplierGetListV1_EORDERBY_sAddressCivic_ASC, ezmax_api_definition__full_supplierGetListV1_EORDERBY_sAddressCivic_DESC, ezmax_api_definition__full_supplierGetListV1_EORDERBY_sAddressStreet_ASC, ezmax_api_definition__full_supplierGetListV1_EORDERBY_sAddressStreet_DESC, ezmax_api_definition__full_supplierGetListV1_EORDERBY_sAddressSuite_ASC, ezmax_api_definition__full_supplierGetListV1_EORDERBY_sAddressSuite_DESC, ezmax_api_definition__full_supplierGetListV1_EORDERBY_sAddressCity_ASC, ezmax_api_definition__full_supplierGetListV1_EORDERBY_sAddressCity_DESC, ezmax_api_definition__full_supplierGetListV1_EORDERBY_sAddressZip_ASC, ezmax_api_definition__full_supplierGetListV1_EORDERBY_sAddressZip_DESC, ezmax_api_definition__full_supplierGetListV1_EORDERBY_sProvinceNameX_ASC, ezmax_api_definition__full_supplierGetListV1_EORDERBY_sProvinceNameX_DESC, ezmax_api_definition__full_supplierGetListV1_EORDERBY_sCountryNameX_ASC, ezmax_api_definition__full_supplierGetListV1_EORDERBY_sCountryNameX_DESC, ezmax_api_definition__full_supplierGetListV1_EORDERBY_sPaymentmethodDescriptionX_ASC, ezmax_api_definition__full_supplierGetListV1_EORDERBY_sPaymentmethodDescriptionX_DESC, ezmax_api_definition__full_supplierGetListV1_EORDERBY_sElectronicfundstransferbankaccountTransit_ASC, ezmax_api_definition__full_supplierGetListV1_EORDERBY_sElectronicfundstransferbankaccountTransit_DESC, ezmax_api_definition__full_supplierGetListV1_EORDERBY_sElectronicfundstransferbankaccountInstitution_ASC, ezmax_api_definition__full_supplierGetListV1_EORDERBY_sElectronicfundstransferbankaccountInstitution_DESC, ezmax_api_definition__full_supplierGetListV1_EORDERBY_sElectronicfundstransferbankaccountAccount_ASC, ezmax_api_definition__full_supplierGetListV1_EORDERBY_sElectronicfundstransferbankaccountAccount_DESC } ezmax_api_definition__full_supplierGetListV1_eOrderBy_e;

// Enum  for ObjectSupplierAPI_supplierGetListV1
typedef enum  { ezmax_api_definition__full_supplierGetListV1__NULL = 0, ezmax_api_definition__full_supplierGetListV1__*, ezmax_api_definition__full_supplierGetListV1__en, ezmax_api_definition__full_supplierGetListV1__fr } ezmax_api_definition__full_supplierGetListV1_Accept-Language_e;


// Retrieve Supplier list
//
// 
//
supplier_get_list_v1_response_t*
ObjectSupplierAPI_supplierGetListV1(apiClient_t *apiClient, ezmax_api_definition__full_supplierGetListV1_eOrderBy_e eOrderBy, int *iRowMax, int *iRowOffset, header_accept_language_e Accept_Language, char *sFilter);


// Import attachments into the Supplier
//
// 
//
supplier_import_into_edm_v1_response_t*
ObjectSupplierAPI_supplierImportIntoEDMV1(apiClient_t *apiClient, int *pkiSupplierID, supplier_import_into_edm_v1_request_t *supplier_import_into_edm_v1_request);


