#include <stdlib.h>
#include <stdio.h>
#include "../include/apiClient.h"
#include "../include/list.h"
#include "../external/cJSON.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"
#include "../model/common_response_error.h"
#include "../model/header_accept_language.h"
#include "../model/inscriptionnotauthenticated_fill_inscriptionnotauthenticatedcondition_v1_request.h"
#include "../model/inscriptionnotauthenticated_fill_inscriptionnotauthenticatedcondition_v1_response.h"
#include "../model/inscriptionnotauthenticated_get_communication_count_v1_response.h"
#include "../model/inscriptionnotauthenticated_get_communication_list_v1_response.h"
#include "../model/inscriptionnotauthenticated_get_communicationrecipients_v1_response.h"
#include "../model/inscriptionnotauthenticated_get_communicationsenders_v1_response.h"
#include "../model/inscriptionnotauthenticated_get_inscriptionnotauthenticatedconditions_v1_response.h"
#include "../model/inscriptionnotauthenticated_get_list_v1_response.h"
#include "../model/inscriptionnotauthenticated_import_into_edm_v1_request.h"
#include "../model/inscriptionnotauthenticated_import_into_edm_v1_response.h"

// Enum EORDERBY for ObjectInscriptionnotauthenticatedAPI_inscriptionnotauthenticatedGetListV1
typedef enum  { ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_NULL = 0, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_pkiInscriptionID_ASC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_pkiInscriptionID_DESC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_pkiInscriptionnotauthenticatedID_ASC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_pkiInscriptionnotauthenticatedID_DESC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_fkiInscriptiontypeID_ASC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_fkiInscriptiontypeID_DESC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_sInscriptiontypeNameX_ASC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_sInscriptiontypeNameX_DESC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_eInscriptionStep_ASC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_eInscriptionStep_DESC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_sInscriptionCivicend_ASC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_sInscriptionCivicend_DESC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_sInscriptionMLS_ASC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_sInscriptionMLS_DESC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_dInscriptionSaleprice_ASC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_dInscriptionSaleprice_DESC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_dInscriptionRentprice_ASC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_dInscriptionRentprice_DESC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_dtInscriptionDate_ASC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_dtInscriptionDate_DESC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_dtInscriptionExpirationdate_ASC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_dtInscriptionExpirationdate_DESC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_dtInscriptionNotarydate_ASC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_dtInscriptionNotarydate_DESC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_bInscriptionInspection_ASC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_bInscriptionInspection_DESC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_bInscriptionIsactive_ASC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_bInscriptionIsactive_DESC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_dtInscriptionnotauthenticatedNotaryscheduledate_ASC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_dtInscriptionnotauthenticatedNotaryscheduledate_DESC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_dtInscriptionnotauthenticatedTransactiondate_ASC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_dtInscriptionnotauthenticatedTransactiondate_DESC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_dtInscriptionnotauthenticatedTransactiondateReal_ASC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_dtInscriptionnotauthenticatedTransactiondateReal_DESC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_bInscriptionnotauthenticatedConditional_ASC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_bInscriptionnotauthenticatedConditional_DESC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_bInscriptionnotauthenticatedIsactive_ASC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_bInscriptionnotauthenticatedIsactive_DESC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_sAddressCivic_ASC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_sAddressCivic_DESC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_sAddressStreet_ASC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_sAddressStreet_DESC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_sAddressSuite_ASC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_sAddressSuite_DESC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_sAddressCity_ASC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_sAddressCity_DESC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_sAddressZip_ASC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_sAddressZip_DESC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_sProvinceNameX_ASC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_sProvinceNameX_DESC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_sCountryNameX_ASC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_sCountryNameX_DESC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_iInscriptionnotauthenticatedCanceled_ASC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_iInscriptionnotauthenticatedCanceled_DESC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_sInscriptionnotauthenticatedOffertopurchasenumber_ASC, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_EORDERBY_sInscriptionnotauthenticatedOffertopurchasenumber_DESC } ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_eOrderBy_e;

// Enum  for ObjectInscriptionnotauthenticatedAPI_inscriptionnotauthenticatedGetListV1
typedef enum  { ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1__NULL = 0, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1__*, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1__en, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1__fr } ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_Accept-Language_e;


// Fills the Inscriptionnotauthenticatedcondition in the Inscriptionnotauthenticated
//
// 
//
inscriptionnotauthenticated_fill_inscriptionnotauthenticatedcondition_v1_response_t*
ObjectInscriptionnotauthenticatedAPI_inscriptionnotauthenticatedFillInscriptionnotauthenticatedconditionV1(apiClient_t *apiClient, int *pkiInscriptionnotauthenticatedID, inscriptionnotauthenticated_fill_inscriptionnotauthenticatedcondition_v1_request_t *inscriptionnotauthenticated_fill_inscriptionnotauthenticatedcondition_v1_request);


// Retrieve Communication count
//
// 
//
inscriptionnotauthenticated_get_communication_count_v1_response_t*
ObjectInscriptionnotauthenticatedAPI_inscriptionnotauthenticatedGetCommunicationCountV1(apiClient_t *apiClient, int *pkiInscriptionnotauthenticatedID);


// Retrieve Communication list
//
// 
//
inscriptionnotauthenticated_get_communication_list_v1_response_t*
ObjectInscriptionnotauthenticatedAPI_inscriptionnotauthenticatedGetCommunicationListV1(apiClient_t *apiClient, int *pkiInscriptionnotauthenticatedID);


// Retrieve Inscriptionnotauthenticated's Communicationrecipient
//
// 
//
inscriptionnotauthenticated_get_communicationrecipients_v1_response_t*
ObjectInscriptionnotauthenticatedAPI_inscriptionnotauthenticatedGetCommunicationrecipientsV1(apiClient_t *apiClient, int *pkiInscriptionnotauthenticatedID);


// Retrieve Inscriptionnotauthenticated's Communicationsender
//
// 
//
inscriptionnotauthenticated_get_communicationsenders_v1_response_t*
ObjectInscriptionnotauthenticatedAPI_inscriptionnotauthenticatedGetCommunicationsendersV1(apiClient_t *apiClient, int *pkiInscriptionnotauthenticatedID);


// Retrieve Inscriptionnotauthenticated conditions
//
// 
//
inscriptionnotauthenticated_get_inscriptionnotauthenticatedconditions_v1_response_t*
ObjectInscriptionnotauthenticatedAPI_inscriptionnotauthenticatedGetInscriptionnotauthenticatedconditionsV1(apiClient_t *apiClient, int *pkiInscriptionnotauthenticatedID);


// Retrieve Inscriptionnotauthenticated list
//
// Enum values that can be filtered in query parameter *sFilter*:  | Variable | Valid values | |---|---| | eInscriptionStep | TemporaryNotAuthenticated<br>ImportedInscription<br>Inscription<br>ModifiedInscription<br>ContractEnded<br>ExpiredInscription<br>Out-market<br>ImportedNotauthenticated<br>NotAuthenticated<br>ModifiedNotauthenticated<br>Authenticated |
//
inscriptionnotauthenticated_get_list_v1_response_t*
ObjectInscriptionnotauthenticatedAPI_inscriptionnotauthenticatedGetListV1(apiClient_t *apiClient, ezmax_api_definition__full_inscriptionnotauthenticatedGetListV1_eOrderBy_e eOrderBy, int *iRowMax, int *iRowOffset, header_accept_language_e Accept_Language, char *sFilter);


// Import attachments into the Inscriptionnotauthenticated
//
// 
//
inscriptionnotauthenticated_import_into_edm_v1_response_t*
ObjectInscriptionnotauthenticatedAPI_inscriptionnotauthenticatedImportIntoEDMV1(apiClient_t *apiClient, int *pkiInscriptionnotauthenticatedID, inscriptionnotauthenticated_import_into_edm_v1_request_t *inscriptionnotauthenticated_import_into_edm_v1_request);


