#include <stdlib.h>
#include <stdio.h>
#include "../include/apiClient.h"
#include "../include/list.h"
#include "../external/cJSON.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"
#include "../model/clonehistory_get_list_v1_response.h"
#include "../model/common_response_error.h"
#include "../model/header_accept_language.h"

// Enum EORDERBY for ObjectClonehistoryAPI_clonehistoryGetListV1
typedef enum  { ezmax_api_definition__full_clonehistoryGetListV1_EORDERBY_NULL = 0, ezmax_api_definition__full_clonehistoryGetListV1_EORDERBY_pkiClonehistoryID_ASC, ezmax_api_definition__full_clonehistoryGetListV1_EORDERBY_pkiClonehistoryID_DESC, ezmax_api_definition__full_clonehistoryGetListV1_EORDERBY_fkiUserIDCloning_ASC, ezmax_api_definition__full_clonehistoryGetListV1_EORDERBY_fkiUserIDCloning_DESC, ezmax_api_definition__full_clonehistoryGetListV1_EORDERBY_fkiUserIDCloned_ASC, ezmax_api_definition__full_clonehistoryGetListV1_EORDERBY_fkiUserIDCloned_DESC, ezmax_api_definition__full_clonehistoryGetListV1_EORDERBY_dtClonehistoryFirsthit_ASC, ezmax_api_definition__full_clonehistoryGetListV1_EORDERBY_dtClonehistoryFirsthit_DESC, ezmax_api_definition__full_clonehistoryGetListV1_EORDERBY_dtClonehistoryLasthit_ASC, ezmax_api_definition__full_clonehistoryGetListV1_EORDERBY_dtClonehistoryLasthit_DESC, ezmax_api_definition__full_clonehistoryGetListV1_EORDERBY_sUserLoginnameCloning_ASC, ezmax_api_definition__full_clonehistoryGetListV1_EORDERBY_sUserLoginnameCloning_DESC, ezmax_api_definition__full_clonehistoryGetListV1_EORDERBY_sUserFirstnameCloning_ASC, ezmax_api_definition__full_clonehistoryGetListV1_EORDERBY_sUserFirstnameCloning_DESC, ezmax_api_definition__full_clonehistoryGetListV1_EORDERBY_sUserLastnameCloning_ASC, ezmax_api_definition__full_clonehistoryGetListV1_EORDERBY_sUserLastnameCloning_DESC, ezmax_api_definition__full_clonehistoryGetListV1_EORDERBY_sUserLoginnameCloned_ASC, ezmax_api_definition__full_clonehistoryGetListV1_EORDERBY_sUserLoginnameCloned_DESC, ezmax_api_definition__full_clonehistoryGetListV1_EORDERBY_sUserFirstnameCloned_ASC, ezmax_api_definition__full_clonehistoryGetListV1_EORDERBY_sUserFirstnameCloned_DESC, ezmax_api_definition__full_clonehistoryGetListV1_EORDERBY_sUserLastnameCloned_ASC, ezmax_api_definition__full_clonehistoryGetListV1_EORDERBY_sUserLastnameCloned_DESC } ezmax_api_definition__full_clonehistoryGetListV1_eOrderBy_e;

// Enum  for ObjectClonehistoryAPI_clonehistoryGetListV1
typedef enum  { ezmax_api_definition__full_clonehistoryGetListV1__NULL = 0, ezmax_api_definition__full_clonehistoryGetListV1__*, ezmax_api_definition__full_clonehistoryGetListV1__en, ezmax_api_definition__full_clonehistoryGetListV1__fr } ezmax_api_definition__full_clonehistoryGetListV1_Accept-Language_e;


// Retrieve Clonehistory list
//
// 
//
clonehistory_get_list_v1_response_t*
ObjectClonehistoryAPI_clonehistoryGetListV1(apiClient_t *apiClient, ezmax_api_definition__full_clonehistoryGetListV1_eOrderBy_e eOrderBy , int iRowMax , int iRowOffset , header_accept_language_e Accept_Language , char * sFilter );


