#include <stdlib.h>
#include <stdio.h>
#include "../include/apiClient.h"
#include "../include/list.h"
#include "../external/cJSON.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"
#include "../model/header_accept_language.h"
#include "../model/realestateassociation_get_autocomplete_v2_response.h"

// Enum SSELECTOR for ObjectRealestateassociationAPI_realestateassociationGetAutocompleteV2
typedef enum  { ezmax_api_definition__full_realestateassociationGetAutocompleteV2_SSELECTOR_NULL = 0, ezmax_api_definition__full_realestateassociationGetAutocompleteV2_SSELECTOR_All } ezmax_api_definition__full_realestateassociationGetAutocompleteV2_sSelector_e;

// Enum EFILTERACTIVE for ObjectRealestateassociationAPI_realestateassociationGetAutocompleteV2
typedef enum  { ezmax_api_definition__full_realestateassociationGetAutocompleteV2_EFILTERACTIVE_NULL = 0, ezmax_api_definition__full_realestateassociationGetAutocompleteV2_EFILTERACTIVE_All, ezmax_api_definition__full_realestateassociationGetAutocompleteV2_EFILTERACTIVE_Active, ezmax_api_definition__full_realestateassociationGetAutocompleteV2_EFILTERACTIVE_Inactive } ezmax_api_definition__full_realestateassociationGetAutocompleteV2_eFilterActive_e;

// Enum  for ObjectRealestateassociationAPI_realestateassociationGetAutocompleteV2
typedef enum  { ezmax_api_definition__full_realestateassociationGetAutocompleteV2__NULL = 0, ezmax_api_definition__full_realestateassociationGetAutocompleteV2__*, ezmax_api_definition__full_realestateassociationGetAutocompleteV2__en, ezmax_api_definition__full_realestateassociationGetAutocompleteV2__fr } ezmax_api_definition__full_realestateassociationGetAutocompleteV2_Accept-Language_e;


// Retrieve Realestateassociations and IDs
//
// Get the list of realestateassociation to be used in a dropdown or autocomplete control.
//
realestateassociation_get_autocomplete_v2_response_t*
ObjectRealestateassociationAPI_realestateassociationGetAutocompleteV2(apiClient_t *apiClient, ezmax_api_definition__full_realestateassociationGetAutocompleteV2_sSelector_e sSelector, ezmax_api_definition__full_realestateassociationGetAutocompleteV2_eFilterActive_e eFilterActive, char *sQuery, header_accept_language_e Accept_Language);


