#include <stdlib.h>
#include <stdio.h>
#include "../include/apiClient.h"
#include "../include/list.h"
#include "../external/cJSON.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"
#include "../model/common_response_error.h"
#include "../model/deposittransitcheque_batch_download_v1_request.h"
#include "../model/deposittransitcheque_get_attachments_v1_response.h"
#include "../model/deposittransitcheque_get_communication_count_v1_response.h"
#include "../model/deposittransitcheque_get_communication_list_v1_response.h"
#include "../model/deposittransitcheque_get_communicationrecipients_v1_response.h"
#include "../model/deposittransitcheque_get_communicationsenders_v1_response.h"
#include "../model/deposittransitcheque_get_list_v1_response.h"
#include "../model/deposittransitcheque_import_into_edm_v1_request.h"
#include "../model/deposittransitcheque_import_into_edm_v1_response.h"
#include "../model/header_accept_language.h"

// Enum EORDERBY for ObjectDeposittransitchequeAPI_deposittransitchequeGetListV1
typedef enum  { ezmax_api_definition__full_deposittransitchequeGetListV1_EORDERBY_NULL = 0, ezmax_api_definition__full_deposittransitchequeGetListV1_EORDERBY_pkiDeposittransitchequeID_ASC, ezmax_api_definition__full_deposittransitchequeGetListV1_EORDERBY_pkiDeposittransitchequeID_DESC, ezmax_api_definition__full_deposittransitchequeGetListV1_EORDERBY_fkiBankaccountID_ASC, ezmax_api_definition__full_deposittransitchequeGetListV1_EORDERBY_fkiBankaccountID_DESC, ezmax_api_definition__full_deposittransitchequeGetListV1_EORDERBY_fkiDepositID_ASC, ezmax_api_definition__full_deposittransitchequeGetListV1_EORDERBY_fkiDepositID_DESC, ezmax_api_definition__full_deposittransitchequeGetListV1_EORDERBY_sDeposittransitchequeNumber_ASC, ezmax_api_definition__full_deposittransitchequeGetListV1_EORDERBY_sDeposittransitchequeNumber_DESC, ezmax_api_definition__full_deposittransitchequeGetListV1_EORDERBY_dtDeposittransitchequeDate_ASC, ezmax_api_definition__full_deposittransitchequeGetListV1_EORDERBY_dtDeposittransitchequeDate_DESC, ezmax_api_definition__full_deposittransitchequeGetListV1_EORDERBY_dDeposittransitchequeAmount_ASC, ezmax_api_definition__full_deposittransitchequeGetListV1_EORDERBY_dDeposittransitchequeAmount_DESC, ezmax_api_definition__full_deposittransitchequeGetListV1_EORDERBY_sBankaccountBankname_ASC, ezmax_api_definition__full_deposittransitchequeGetListV1_EORDERBY_sBankaccountBankname_DESC, ezmax_api_definition__full_deposittransitchequeGetListV1_EORDERBY_sPeriodYYYYMM_ASC, ezmax_api_definition__full_deposittransitchequeGetListV1_EORDERBY_sPeriodYYYYMM_DESC, ezmax_api_definition__full_deposittransitchequeGetListV1_EORDERBY_sCustomerName_ASC, ezmax_api_definition__full_deposittransitchequeGetListV1_EORDERBY_sCustomerName_DESC } ezmax_api_definition__full_deposittransitchequeGetListV1_eOrderBy_e;

// Enum  for ObjectDeposittransitchequeAPI_deposittransitchequeGetListV1
typedef enum  { ezmax_api_definition__full_deposittransitchequeGetListV1__NULL = 0, ezmax_api_definition__full_deposittransitchequeGetListV1__*, ezmax_api_definition__full_deposittransitchequeGetListV1__en, ezmax_api_definition__full_deposittransitchequeGetListV1__fr } ezmax_api_definition__full_deposittransitchequeGetListV1_Accept-Language_e;


// Download multiples attachments from a Deposittransitcheque
//
binary_t*
ObjectDeposittransitchequeAPI_deposittransitchequeBatchDownloadV1(apiClient_t *apiClient, int *pkiDeposittransitchequeID, deposittransitcheque_batch_download_v1_request_t *deposittransitcheque_batch_download_v1_request);


// Retrieve Deposittransitcheque's attachments
//
deposittransitcheque_get_attachments_v1_response_t*
ObjectDeposittransitchequeAPI_deposittransitchequeGetAttachmentsV1(apiClient_t *apiClient, int *pkiDeposittransitchequeID);


// Retrieve Communication count
//
deposittransitcheque_get_communication_count_v1_response_t*
ObjectDeposittransitchequeAPI_deposittransitchequeGetCommunicationCountV1(apiClient_t *apiClient, int *pkiDeposittransitchequeID);


// Retrieve Communication list
//
deposittransitcheque_get_communication_list_v1_response_t*
ObjectDeposittransitchequeAPI_deposittransitchequeGetCommunicationListV1(apiClient_t *apiClient, int *pkiDeposittransitchequeID);


// Retrieve Communication recipients
//
deposittransitcheque_get_communicationrecipients_v1_response_t*
ObjectDeposittransitchequeAPI_deposittransitchequeGetCommunicationrecipientsV1(apiClient_t *apiClient, int *pkiDeposittransitchequeID);


// Retrieve Communication senders
//
deposittransitcheque_get_communicationsenders_v1_response_t*
ObjectDeposittransitchequeAPI_deposittransitchequeGetCommunicationsendersV1(apiClient_t *apiClient, int *pkiDeposittransitchequeID);


// Retrieve Deposittransitcheque list
//
// 
//
deposittransitcheque_get_list_v1_response_t*
ObjectDeposittransitchequeAPI_deposittransitchequeGetListV1(apiClient_t *apiClient, ezmax_api_definition__full_deposittransitchequeGetListV1_eOrderBy_e eOrderBy, int *iRowMax, int *iRowOffset, header_accept_language_e Accept_Language, char *sFilter);


// Import attachments into the Deposittransitcheque
//
deposittransitcheque_import_into_edm_v1_response_t*
ObjectDeposittransitchequeAPI_deposittransitchequeImportIntoEDMV1(apiClient_t *apiClient, int *pkiDeposittransitchequeID, deposittransitcheque_import_into_edm_v1_request_t *deposittransitcheque_import_into_edm_v1_request);


