#include <stdlib.h>
#include <stdio.h>
#include "../include/apiClient.h"
#include "../include/list.h"
#include "../external/cJSON.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"
#include "../model/header_accept_language.h"
#include "../model/infrastructureregion_get_autocomplete_v2_response.h"

// Enum SSELECTOR for ObjectInfrastructureregionAPI_infrastructureregionGetAutocompleteV2
typedef enum  { ezmax_api_definition__full_infrastructureregionGetAutocompleteV2_SSELECTOR_NULL = 0, ezmax_api_definition__full_infrastructureregionGetAutocompleteV2_SSELECTOR_AWS, ezmax_api_definition__full_infrastructureregionGetAutocompleteV2_SSELECTOR_Programmer } ezmax_api_definition__full_infrastructureregionGetAutocompleteV2_sSelector_e;

// Enum EFILTERACTIVE for ObjectInfrastructureregionAPI_infrastructureregionGetAutocompleteV2
typedef enum  { ezmax_api_definition__full_infrastructureregionGetAutocompleteV2_EFILTERACTIVE_NULL = 0, ezmax_api_definition__full_infrastructureregionGetAutocompleteV2_EFILTERACTIVE_All, ezmax_api_definition__full_infrastructureregionGetAutocompleteV2_EFILTERACTIVE_Active, ezmax_api_definition__full_infrastructureregionGetAutocompleteV2_EFILTERACTIVE_Inactive } ezmax_api_definition__full_infrastructureregionGetAutocompleteV2_eFilterActive_e;

// Enum  for ObjectInfrastructureregionAPI_infrastructureregionGetAutocompleteV2
typedef enum  { ezmax_api_definition__full_infrastructureregionGetAutocompleteV2__NULL = 0, ezmax_api_definition__full_infrastructureregionGetAutocompleteV2__*, ezmax_api_definition__full_infrastructureregionGetAutocompleteV2__en, ezmax_api_definition__full_infrastructureregionGetAutocompleteV2__fr } ezmax_api_definition__full_infrastructureregionGetAutocompleteV2_Accept-Language_e;


// Retrieve Infrastructureregions and IDs
//
// Get the list of Infrastructureregion to be used in a dropdown or autocomplete control.
//
infrastructureregion_get_autocomplete_v2_response_t*
ObjectInfrastructureregionAPI_infrastructureregionGetAutocompleteV2(apiClient_t *apiClient, ezmax_api_definition__full_infrastructureregionGetAutocompleteV2_sSelector_e sSelector, ezmax_api_definition__full_infrastructureregionGetAutocompleteV2_eFilterActive_e eFilterActive, char *sQuery, header_accept_language_e Accept_Language);


