#include <stdlib.h>
#include <stdio.h>
#include "../include/apiClient.h"
#include "../include/list.h"
#include "../external/cJSON.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"
#include "../model/common_response_error.h"
#include "../model/header_accept_language.h"
#include "../model/salary_batch_download_v1_request.h"
#include "../model/salary_get_attachments_v1_response.h"
#include "../model/salary_get_list_v1_response.h"
#include "../model/salary_import_into_edm_v1_request.h"
#include "../model/salary_import_into_edm_v1_response.h"

// Enum EORDERBY for ObjectSalaryAPI_salaryGetListV1
typedef enum  { ezmax_api_definition__full_salaryGetListV1_EORDERBY_NULL = 0, ezmax_api_definition__full_salaryGetListV1_EORDERBY_pkiSalaryID_ASC, ezmax_api_definition__full_salaryGetListV1_EORDERBY_pkiSalaryID_DESC, ezmax_api_definition__full_salaryGetListV1_EORDERBY_fkiPeriodID_ASC, ezmax_api_definition__full_salaryGetListV1_EORDERBY_fkiPeriodID_DESC, ezmax_api_definition__full_salaryGetListV1_EORDERBY_fkiUSerIDCreated_ASC, ezmax_api_definition__full_salaryGetListV1_EORDERBY_fkiUSerIDCreated_DESC, ezmax_api_definition__full_salaryGetListV1_EORDERBY_fkiSalaryperiodID_ASC, ezmax_api_definition__full_salaryGetListV1_EORDERBY_fkiSalaryperiodID_DESC, ezmax_api_definition__full_salaryGetListV1_EORDERBY_dtSalaryPaymentdate_ASC, ezmax_api_definition__full_salaryGetListV1_EORDERBY_dtSalaryPaymentdate_DESC, ezmax_api_definition__full_salaryGetListV1_EORDERBY_sSalaryperiod_ASC, ezmax_api_definition__full_salaryGetListV1_EORDERBY_sSalaryperiod_DESC, ezmax_api_definition__full_salaryGetListV1_EORDERBY_sPeriodYYYYMM_ASC, ezmax_api_definition__full_salaryGetListV1_EORDERBY_sPeriodYYYYMM_DESC, ezmax_api_definition__full_salaryGetListV1_EORDERBY_iSalarypreparationCount_ASC, ezmax_api_definition__full_salaryGetListV1_EORDERBY_iSalarypreparationCount_DESC, ezmax_api_definition__full_salaryGetListV1_EORDERBY_dSalarypreparationTotal_ASC, ezmax_api_definition__full_salaryGetListV1_EORDERBY_dSalarypreparationTotal_DESC, ezmax_api_definition__full_salaryGetListV1_EORDERBY_dtSalaryperiodStart_ASC, ezmax_api_definition__full_salaryGetListV1_EORDERBY_dtSalaryperiodStart_DESC, ezmax_api_definition__full_salaryGetListV1_EORDERBY_dtSalaryperiodEnd_ASC, ezmax_api_definition__full_salaryGetListV1_EORDERBY_dtSalaryperiodEnd_DESC, ezmax_api_definition__full_salaryGetListV1_EORDERBY_sUserLoginname_ASC, ezmax_api_definition__full_salaryGetListV1_EORDERBY_sUserLoginname_DESC, ezmax_api_definition__full_salaryGetListV1_EORDERBY_dtCreatedDate_ASC, ezmax_api_definition__full_salaryGetListV1_EORDERBY_dtCreatedDate_DESC, ezmax_api_definition__full_salaryGetListV1_EORDERBY_bSalarypreparationIspaid_ASC, ezmax_api_definition__full_salaryGetListV1_EORDERBY_bSalarypreparationIspaid_DESC, ezmax_api_definition__full_salaryGetListV1_EORDERBY_iSalaryperiodgroupYear_ASC, ezmax_api_definition__full_salaryGetListV1_EORDERBY_iSalaryperiodgroupYear_DESC } ezmax_api_definition__full_salaryGetListV1_eOrderBy_e;

// Enum  for ObjectSalaryAPI_salaryGetListV1
typedef enum  { ezmax_api_definition__full_salaryGetListV1__NULL = 0, ezmax_api_definition__full_salaryGetListV1__*, ezmax_api_definition__full_salaryGetListV1__en, ezmax_api_definition__full_salaryGetListV1__fr } ezmax_api_definition__full_salaryGetListV1_Accept-Language_e;


// Download multiples attachments from a Reconciliation
//
binary_t*
ObjectSalaryAPI_salaryBatchDownloadV1(apiClient_t *apiClient, int *pkiSalaryID, salary_batch_download_v1_request_t *salary_batch_download_v1_request);


// Retrieve Salary's attachments
//
salary_get_attachments_v1_response_t*
ObjectSalaryAPI_salaryGetAttachmentsV1(apiClient_t *apiClient, int *pkiSalaryID);


// Retrieve Salary list
//
// 
//
salary_get_list_v1_response_t*
ObjectSalaryAPI_salaryGetListV1(apiClient_t *apiClient, ezmax_api_definition__full_salaryGetListV1_eOrderBy_e eOrderBy, int *iRowMax, int *iRowOffset, header_accept_language_e Accept_Language, char *sFilter);


// Import attachments into the Salary
//
salary_import_into_edm_v1_response_t*
ObjectSalaryAPI_salaryImportIntoEDMV1(apiClient_t *apiClient, int *pkiSalaryID, salary_import_into_edm_v1_request_t *salary_import_into_edm_v1_request);


