#include <stdlib.h>
#include <stdio.h>
#include "../include/apiClient.h"
#include "../include/list.h"
#include "../external/cJSON.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"
#include "../model/activesession_get_current_v1_response.h"
#include "../model/activesession_get_list_v1_response.h"
#include "../model/common_response_error.h"
#include "../model/common_response_redirect_s_secretquestion_text_x.h"
#include "../model/header_accept_language.h"

// Enum EORDERBY for ObjectActivesessionAPI_activesessionGetListV1
typedef enum  { ezmax_api_definition__full_activesessionGetListV1_EORDERBY_NULL = 0, ezmax_api_definition__full_activesessionGetListV1_EORDERBY_pkiActivesessionID_ASC, ezmax_api_definition__full_activesessionGetListV1_EORDERBY_pkiActivesessionID_DESC, ezmax_api_definition__full_activesessionGetListV1_EORDERBY_fkiUserID_ASC, ezmax_api_definition__full_activesessionGetListV1_EORDERBY_fkiUserID_DESC, ezmax_api_definition__full_activesessionGetListV1_EORDERBY_fkiComputerID_ASC, ezmax_api_definition__full_activesessionGetListV1_EORDERBY_fkiComputerID_DESC, ezmax_api_definition__full_activesessionGetListV1_EORDERBY_fkiCompanyID_ASC, ezmax_api_definition__full_activesessionGetListV1_EORDERBY_fkiCompanyID_DESC, ezmax_api_definition__full_activesessionGetListV1_EORDERBY_fkiDepartmentID_ASC, ezmax_api_definition__full_activesessionGetListV1_EORDERBY_fkiDepartmentID_DESC, ezmax_api_definition__full_activesessionGetListV1_EORDERBY_sCompanyNameX_ASC, ezmax_api_definition__full_activesessionGetListV1_EORDERBY_sCompanyNameX_DESC, ezmax_api_definition__full_activesessionGetListV1_EORDERBY_sDepartmentNameX_ASC, ezmax_api_definition__full_activesessionGetListV1_EORDERBY_sDepartmentNameX_DESC, ezmax_api_definition__full_activesessionGetListV1_EORDERBY_sActivesessionLoginname_ASC, ezmax_api_definition__full_activesessionGetListV1_EORDERBY_sActivesessionLoginname_DESC, ezmax_api_definition__full_activesessionGetListV1_EORDERBY_sComputerDescription_ASC, ezmax_api_definition__full_activesessionGetListV1_EORDERBY_sComputerDescription_DESC, ezmax_api_definition__full_activesessionGetListV1_EORDERBY_dtActivesessionFirsthit_ASC, ezmax_api_definition__full_activesessionGetListV1_EORDERBY_dtActivesessionFirsthit_DESC, ezmax_api_definition__full_activesessionGetListV1_EORDERBY_dtActivesessionLasthit_ASC, ezmax_api_definition__full_activesessionGetListV1_EORDERBY_dtActivesessionLasthit_DESC, ezmax_api_definition__full_activesessionGetListV1_EORDERBY_sActivesessionIP_ASC, ezmax_api_definition__full_activesessionGetListV1_EORDERBY_sActivesessionIP_DESC } ezmax_api_definition__full_activesessionGetListV1_eOrderBy_e;

// Enum  for ObjectActivesessionAPI_activesessionGetListV1
typedef enum  { ezmax_api_definition__full_activesessionGetListV1__NULL = 0, ezmax_api_definition__full_activesessionGetListV1__*, ezmax_api_definition__full_activesessionGetListV1__en, ezmax_api_definition__full_activesessionGetListV1__fr } ezmax_api_definition__full_activesessionGetListV1_Accept-Language_e;


// Get Current Activesession
//
// Retrieve the details about the current activesession
//
activesession_get_current_v1_response_t*
ObjectActivesessionAPI_activesessionGetCurrentV1(apiClient_t *apiClient);


// Retrieve Activesession list
//
activesession_get_list_v1_response_t*
ObjectActivesessionAPI_activesessionGetListV1(apiClient_t *apiClient, ezmax_api_definition__full_activesessionGetListV1_eOrderBy_e eOrderBy, int *iRowMax, int *iRowOffset, header_accept_language_e Accept_Language, char *sFilter);


