#include <stdlib.h>
#include <stdio.h>
#include "../include/apiClient.h"
#include "../include/list.h"
#include "../external/cJSON.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"
#include "../model/ezdoctemplatefieldtypecategory_get_autocomplete_v2_response.h"
#include "../model/header_accept_language.h"

// Enum SSELECTOR for ObjectEzdoctemplatefieldtypecategoryAPI_ezdoctemplatefieldtypecategoryGetAutocompleteV2
typedef enum  { ezmax_api_definition__full_ezdoctemplatefieldtypecategoryGetAutocompleteV2_SSELECTOR_NULL = 0, ezmax_api_definition__full_ezdoctemplatefieldtypecategoryGetAutocompleteV2_SSELECTOR_All } ezmax_api_definition__full_ezdoctemplatefieldtypecategoryGetAutocompleteV2_sSelector_e;

// Enum EFILTERACTIVE for ObjectEzdoctemplatefieldtypecategoryAPI_ezdoctemplatefieldtypecategoryGetAutocompleteV2
typedef enum  { ezmax_api_definition__full_ezdoctemplatefieldtypecategoryGetAutocompleteV2_EFILTERACTIVE_NULL = 0, ezmax_api_definition__full_ezdoctemplatefieldtypecategoryGetAutocompleteV2_EFILTERACTIVE_All, ezmax_api_definition__full_ezdoctemplatefieldtypecategoryGetAutocompleteV2_EFILTERACTIVE_Active, ezmax_api_definition__full_ezdoctemplatefieldtypecategoryGetAutocompleteV2_EFILTERACTIVE_Inactive } ezmax_api_definition__full_ezdoctemplatefieldtypecategoryGetAutocompleteV2_eFilterActive_e;

// Enum  for ObjectEzdoctemplatefieldtypecategoryAPI_ezdoctemplatefieldtypecategoryGetAutocompleteV2
typedef enum  { ezmax_api_definition__full_ezdoctemplatefieldtypecategoryGetAutocompleteV2__NULL = 0, ezmax_api_definition__full_ezdoctemplatefieldtypecategoryGetAutocompleteV2__*, ezmax_api_definition__full_ezdoctemplatefieldtypecategoryGetAutocompleteV2__en, ezmax_api_definition__full_ezdoctemplatefieldtypecategoryGetAutocompleteV2__fr } ezmax_api_definition__full_ezdoctemplatefieldtypecategoryGetAutocompleteV2_Accept-Language_e;


// Retrieve Ezdoctemplatefieldtypecategorys and IDs
//
// Get the list of Ezdoctemplatefieldtypecategory to be used in a dropdown or autocomplete control.
//
ezdoctemplatefieldtypecategory_get_autocomplete_v2_response_t*
ObjectEzdoctemplatefieldtypecategoryAPI_ezdoctemplatefieldtypecategoryGetAutocompleteV2(apiClient_t *apiClient, ezmax_api_definition__full_ezdoctemplatefieldtypecategoryGetAutocompleteV2_sSelector_e sSelector, ezmax_api_definition__full_ezdoctemplatefieldtypecategoryGetAutocompleteV2_eFilterActive_e eFilterActive, char *sQuery, header_accept_language_e Accept_Language);


