#include <stdlib.h>
#include <stdio.h>
#include "../include/apiClient.h"
#include "../include/list.h"
#include "../external/cJSON.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"
#include "../model/common_response_error.h"
#include "../model/ezsignsigningreason_create_object_v1_request.h"
#include "../model/ezsignsigningreason_create_object_v1_response.h"
#include "../model/ezsignsigningreason_edit_object_v1_request.h"
#include "../model/ezsignsigningreason_edit_object_v1_response.h"
#include "../model/ezsignsigningreason_get_autocomplete_v2_response.h"
#include "../model/ezsignsigningreason_get_list_v1_response.h"
#include "../model/ezsignsigningreason_get_object_v2_response.h"
#include "../model/header_accept_language.h"

// Enum SSELECTOR for ObjectEzsignsigningreasonAPI_ezsignsigningreasonGetAutocompleteV2
typedef enum  { ezmax_api_definition__full_ezsignsigningreasonGetAutocompleteV2_SSELECTOR_NULL = 0, ezmax_api_definition__full_ezsignsigningreasonGetAutocompleteV2_SSELECTOR_All, ezmax_api_definition__full_ezsignsigningreasonGetAutocompleteV2_SSELECTOR_Active } ezmax_api_definition__full_ezsignsigningreasonGetAutocompleteV2_sSelector_e;

// Enum EFILTERACTIVE for ObjectEzsignsigningreasonAPI_ezsignsigningreasonGetAutocompleteV2
typedef enum  { ezmax_api_definition__full_ezsignsigningreasonGetAutocompleteV2_EFILTERACTIVE_NULL = 0, ezmax_api_definition__full_ezsignsigningreasonGetAutocompleteV2_EFILTERACTIVE_All, ezmax_api_definition__full_ezsignsigningreasonGetAutocompleteV2_EFILTERACTIVE_Active, ezmax_api_definition__full_ezsignsigningreasonGetAutocompleteV2_EFILTERACTIVE_Inactive } ezmax_api_definition__full_ezsignsigningreasonGetAutocompleteV2_eFilterActive_e;

// Enum  for ObjectEzsignsigningreasonAPI_ezsignsigningreasonGetAutocompleteV2
typedef enum  { ezmax_api_definition__full_ezsignsigningreasonGetAutocompleteV2__NULL = 0, ezmax_api_definition__full_ezsignsigningreasonGetAutocompleteV2__*, ezmax_api_definition__full_ezsignsigningreasonGetAutocompleteV2__en, ezmax_api_definition__full_ezsignsigningreasonGetAutocompleteV2__fr } ezmax_api_definition__full_ezsignsigningreasonGetAutocompleteV2_Accept-Language_e;

// Enum EORDERBY for ObjectEzsignsigningreasonAPI_ezsignsigningreasonGetListV1
typedef enum  { ezmax_api_definition__full_ezsignsigningreasonGetListV1_EORDERBY_NULL = 0, ezmax_api_definition__full_ezsignsigningreasonGetListV1_EORDERBY_pkiEzsignsigningreasonID_ASC, ezmax_api_definition__full_ezsignsigningreasonGetListV1_EORDERBY_pkiEzsignsigningreasonID_DESC, ezmax_api_definition__full_ezsignsigningreasonGetListV1_EORDERBY_sEzsignsigningreasonDescriptionX_ASC, ezmax_api_definition__full_ezsignsigningreasonGetListV1_EORDERBY_sEzsignsigningreasonDescriptionX_DESC, ezmax_api_definition__full_ezsignsigningreasonGetListV1_EORDERBY_bEzsignsigningreasonIsactive_ASC, ezmax_api_definition__full_ezsignsigningreasonGetListV1_EORDERBY_bEzsignsigningreasonIsactive_DESC } ezmax_api_definition__full_ezsignsigningreasonGetListV1_eOrderBy_e;

// Enum  for ObjectEzsignsigningreasonAPI_ezsignsigningreasonGetListV1
typedef enum  { ezmax_api_definition__full_ezsignsigningreasonGetListV1__NULL = 0, ezmax_api_definition__full_ezsignsigningreasonGetListV1__*, ezmax_api_definition__full_ezsignsigningreasonGetListV1__en, ezmax_api_definition__full_ezsignsigningreasonGetListV1__fr } ezmax_api_definition__full_ezsignsigningreasonGetListV1_Accept-Language_e;


// Create a new Ezsignsigningreason
//
// The endpoint allows to create one or many elements at once.
//
ezsignsigningreason_create_object_v1_response_t*
ObjectEzsignsigningreasonAPI_ezsignsigningreasonCreateObjectV1(apiClient_t *apiClient, ezsignsigningreason_create_object_v1_request_t *ezsignsigningreason_create_object_v1_request);


// Edit an existing Ezsignsigningreason
//
// 
//
ezsignsigningreason_edit_object_v1_response_t*
ObjectEzsignsigningreasonAPI_ezsignsigningreasonEditObjectV1(apiClient_t *apiClient, int *pkiEzsignsigningreasonID, ezsignsigningreason_edit_object_v1_request_t *ezsignsigningreason_edit_object_v1_request);


// Retrieve Ezsignsigningreasons and IDs
//
// Get the list of Ezsignsigningreason to be used in a dropdown or autocomplete control.
//
ezsignsigningreason_get_autocomplete_v2_response_t*
ObjectEzsignsigningreasonAPI_ezsignsigningreasonGetAutocompleteV2(apiClient_t *apiClient, ezmax_api_definition__full_ezsignsigningreasonGetAutocompleteV2_sSelector_e sSelector, ezmax_api_definition__full_ezsignsigningreasonGetAutocompleteV2_eFilterActive_e eFilterActive, char *sQuery, header_accept_language_e Accept_Language);


// Retrieve Ezsignsigningreason list
//
// 
//
ezsignsigningreason_get_list_v1_response_t*
ObjectEzsignsigningreasonAPI_ezsignsigningreasonGetListV1(apiClient_t *apiClient, ezmax_api_definition__full_ezsignsigningreasonGetListV1_eOrderBy_e eOrderBy, int *iRowMax, int *iRowOffset, header_accept_language_e Accept_Language, char *sFilter);


// Retrieve an existing Ezsignsigningreason
//
// 
//
ezsignsigningreason_get_object_v2_response_t*
ObjectEzsignsigningreasonAPI_ezsignsigningreasonGetObjectV2(apiClient_t *apiClient, int *pkiEzsignsigningreasonID);


