#include <stdlib.h>
#include <stdio.h>
#include "../include/apiClient.h"
#include "../include/list.h"
#include "../external/cJSON.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"
#include "../model/common_response_error.h"
#include "../model/ezmaxpartner_get_custom_developpers_v1_response.h"
#include "../model/ezmaxpartner_get_object_v2_response.h"
#include "../model/header_accept_language.h"

// Enum EORDERBY for ObjectEzmaxpartnerAPI_ezmaxpartnerGetCustomDeveloppersV1
typedef enum  { ezmax_api_definition__full_ezmaxpartnerGetCustomDeveloppersV1_EORDERBY_NULL = 0, ezmax_api_definition__full_ezmaxpartnerGetCustomDeveloppersV1_EORDERBY_pkiEzmaxpartnerID_ASC, ezmax_api_definition__full_ezmaxpartnerGetCustomDeveloppersV1_EORDERBY_pkiEzmaxpartnerID_DESC, ezmax_api_definition__full_ezmaxpartnerGetCustomDeveloppersV1_EORDERBY_sEzmaxpartnerAddressX_ASC, ezmax_api_definition__full_ezmaxpartnerGetCustomDeveloppersV1_EORDERBY_sEzmaxpartnerAddressX_DESC, ezmax_api_definition__full_ezmaxpartnerGetCustomDeveloppersV1_EORDERBY_sEzmaxpartnerEmailaddressX_ASC, ezmax_api_definition__full_ezmaxpartnerGetCustomDeveloppersV1_EORDERBY_sEzmaxpartnerEmailaddressX_DESC, ezmax_api_definition__full_ezmaxpartnerGetCustomDeveloppersV1_EORDERBY_sEzmaxpartnerShortdescriptionX_ASC, ezmax_api_definition__full_ezmaxpartnerGetCustomDeveloppersV1_EORDERBY_sEzmaxpartnerShortdescriptionX_DESC, ezmax_api_definition__full_ezmaxpartnerGetCustomDeveloppersV1_EORDERBY_sEzmaxpartnerNameX_ASC, ezmax_api_definition__full_ezmaxpartnerGetCustomDeveloppersV1_EORDERBY_sEzmaxpartnerNameX_DESC, ezmax_api_definition__full_ezmaxpartnerGetCustomDeveloppersV1_EORDERBY_sEzmaxpartnerPhoneE164X_ASC, ezmax_api_definition__full_ezmaxpartnerGetCustomDeveloppersV1_EORDERBY_sEzmaxpartnerPhoneE164X_DESC, ezmax_api_definition__full_ezmaxpartnerGetCustomDeveloppersV1_EORDERBY_sEzmaxpartnerUrlX_ASC, ezmax_api_definition__full_ezmaxpartnerGetCustomDeveloppersV1_EORDERBY_sEzmaxpartnerUrlX_DESC } ezmax_api_definition__full_ezmaxpartnerGetCustomDeveloppersV1_eOrderBy_e;

// Enum  for ObjectEzmaxpartnerAPI_ezmaxpartnerGetCustomDeveloppersV1
typedef enum  { ezmax_api_definition__full_ezmaxpartnerGetCustomDeveloppersV1__NULL = 0, ezmax_api_definition__full_ezmaxpartnerGetCustomDeveloppersV1__*, ezmax_api_definition__full_ezmaxpartnerGetCustomDeveloppersV1__en, ezmax_api_definition__full_ezmaxpartnerGetCustomDeveloppersV1__fr } ezmax_api_definition__full_ezmaxpartnerGetCustomDeveloppersV1_Accept-Language_e;


// Retrieve Ezmaxpartner custom developpers list
//
ezmaxpartner_get_custom_developpers_v1_response_t*
ObjectEzmaxpartnerAPI_ezmaxpartnerGetCustomDeveloppersV1(apiClient_t *apiClient, ezmax_api_definition__full_ezmaxpartnerGetCustomDeveloppersV1_eOrderBy_e eOrderBy, int *iRowMax, int *iRowOffset, header_accept_language_e Accept_Language, char *sFilter);


// Retrieve an existing Ezmaxpartner
//
// 
//
ezmaxpartner_get_object_v2_response_t*
ObjectEzmaxpartnerAPI_ezmaxpartnerGetObjectV2(apiClient_t *apiClient, int *pkiEzmaxpartnerID);


