#include <stdlib.h>
#include <stdio.h>
#include "../include/apiClient.h"
#include "../include/list.h"
#include "../external/cJSON.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"
#include "../model/common_response_error.h"
#include "../model/employee_get_list_v1_response.h"
#include "../model/employee_import_into_edm_v1_request.h"
#include "../model/employee_import_into_edm_v1_response.h"
#include "../model/header_accept_language.h"

// Enum EORDERBY for ObjectEmployeeAPI_employeeGetListV1
typedef enum  { ezmax_api_definition__full_employeeGetListV1_EORDERBY_NULL = 0, ezmax_api_definition__full_employeeGetListV1_EORDERBY_pkiEmployeeID_ASC, ezmax_api_definition__full_employeeGetListV1_EORDERBY_pkiEmployeeID_DESC, ezmax_api_definition__full_employeeGetListV1_EORDERBY_fkiDepartmentID_ASC, ezmax_api_definition__full_employeeGetListV1_EORDERBY_fkiDepartmentID_DESC, ezmax_api_definition__full_employeeGetListV1_EORDERBY_sEmployeeCode_ASC, ezmax_api_definition__full_employeeGetListV1_EORDERBY_sEmployeeCode_DESC, ezmax_api_definition__full_employeeGetListV1_EORDERBY_sEmployeeInternalcode_ASC, ezmax_api_definition__full_employeeGetListV1_EORDERBY_sEmployeeInternalcode_DESC, ezmax_api_definition__full_employeeGetListV1_EORDERBY_bEmployeeIsactive_ASC, ezmax_api_definition__full_employeeGetListV1_EORDERBY_bEmployeeIsactive_DESC, ezmax_api_definition__full_employeeGetListV1_EORDERBY_dtEmployeeHiredate_ASC, ezmax_api_definition__full_employeeGetListV1_EORDERBY_dtEmployeeHiredate_DESC, ezmax_api_definition__full_employeeGetListV1_EORDERBY_dtEmployeeLeavedate_ASC, ezmax_api_definition__full_employeeGetListV1_EORDERBY_dtEmployeeLeavedate_DESC, ezmax_api_definition__full_employeeGetListV1_EORDERBY_sDepartmentNameX_ASC, ezmax_api_definition__full_employeeGetListV1_EORDERBY_sDepartmentNameX_DESC, ezmax_api_definition__full_employeeGetListV1_EORDERBY_sContactFirstname_ASC, ezmax_api_definition__full_employeeGetListV1_EORDERBY_sContactFirstname_DESC, ezmax_api_definition__full_employeeGetListV1_EORDERBY_sContactLastname_ASC, ezmax_api_definition__full_employeeGetListV1_EORDERBY_sContactLastname_DESC, ezmax_api_definition__full_employeeGetListV1_EORDERBY_sPhoneE164_ASC, ezmax_api_definition__full_employeeGetListV1_EORDERBY_sPhoneE164_DESC, ezmax_api_definition__full_employeeGetListV1_EORDERBY_sEmailAddress_ASC, ezmax_api_definition__full_employeeGetListV1_EORDERBY_sEmailAddress_DESC, ezmax_api_definition__full_employeeGetListV1_EORDERBY_sAddressCivic_ASC, ezmax_api_definition__full_employeeGetListV1_EORDERBY_sAddressCivic_DESC, ezmax_api_definition__full_employeeGetListV1_EORDERBY_sAddressStreet_ASC, ezmax_api_definition__full_employeeGetListV1_EORDERBY_sAddressStreet_DESC, ezmax_api_definition__full_employeeGetListV1_EORDERBY_sAddressSuite_ASC, ezmax_api_definition__full_employeeGetListV1_EORDERBY_sAddressSuite_DESC, ezmax_api_definition__full_employeeGetListV1_EORDERBY_sAddressCity_ASC, ezmax_api_definition__full_employeeGetListV1_EORDERBY_sAddressCity_DESC, ezmax_api_definition__full_employeeGetListV1_EORDERBY_sAddressZip_ASC, ezmax_api_definition__full_employeeGetListV1_EORDERBY_sAddressZip_DESC, ezmax_api_definition__full_employeeGetListV1_EORDERBY_sProvinceNameX_ASC, ezmax_api_definition__full_employeeGetListV1_EORDERBY_sProvinceNameX_DESC, ezmax_api_definition__full_employeeGetListV1_EORDERBY_sCountryNameX_ASC, ezmax_api_definition__full_employeeGetListV1_EORDERBY_sCountryNameX_DESC } ezmax_api_definition__full_employeeGetListV1_eOrderBy_e;

// Enum  for ObjectEmployeeAPI_employeeGetListV1
typedef enum  { ezmax_api_definition__full_employeeGetListV1__NULL = 0, ezmax_api_definition__full_employeeGetListV1__*, ezmax_api_definition__full_employeeGetListV1__en, ezmax_api_definition__full_employeeGetListV1__fr } ezmax_api_definition__full_employeeGetListV1_Accept-Language_e;


// Retrieve Employee list
//
// 
//
employee_get_list_v1_response_t*
ObjectEmployeeAPI_employeeGetListV1(apiClient_t *apiClient, ezmax_api_definition__full_employeeGetListV1_eOrderBy_e eOrderBy, int *iRowMax, int *iRowOffset, header_accept_language_e Accept_Language, char *sFilter);


// Import attachments into the Employee
//
// 
//
employee_import_into_edm_v1_response_t*
ObjectEmployeeAPI_employeeImportIntoEDMV1(apiClient_t *apiClient, int *pkiEmployeeID, employee_import_into_edm_v1_request_t *employee_import_into_edm_v1_request);


