#include <stdlib.h>
#include <stdio.h>
#include "../include/apiClient.h"
#include "../include/list.h"
#include "../external/cJSON.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"
#include "../model/common_response_error.h"
#include "../model/ezdoctemplatedocument_create_object_v1_request.h"
#include "../model/ezdoctemplatedocument_create_object_v1_response.h"
#include "../model/ezdoctemplatedocument_edit_object_v1_request.h"
#include "../model/ezdoctemplatedocument_edit_object_v1_response.h"
#include "../model/ezdoctemplatedocument_get_autocomplete_v2_response.h"
#include "../model/ezdoctemplatedocument_get_list_v1_response.h"
#include "../model/ezdoctemplatedocument_get_object_v2_response.h"
#include "../model/ezdoctemplatedocument_patch_object_v1_request.h"
#include "../model/ezdoctemplatedocument_patch_object_v1_response.h"
#include "../model/header_accept_language.h"

// Enum SSELECTOR for ObjectEzdoctemplatedocumentAPI_ezdoctemplatedocumentGetAutocompleteV2
typedef enum  { ezmax_api_definition__full_ezdoctemplatedocumentGetAutocompleteV2_SSELECTOR_NULL = 0, ezmax_api_definition__full_ezdoctemplatedocumentGetAutocompleteV2_SSELECTOR_All, ezmax_api_definition__full_ezdoctemplatedocumentGetAutocompleteV2_SSELECTOR_Ezsignfolder, ezmax_api_definition__full_ezdoctemplatedocumentGetAutocompleteV2_SSELECTOR_Ezsignfoldersignerassociations } ezmax_api_definition__full_ezdoctemplatedocumentGetAutocompleteV2_sSelector_e;

// Enum ETYPE for ObjectEzdoctemplatedocumentAPI_ezdoctemplatedocumentGetAutocompleteV2
typedef enum  { ezmax_api_definition__full_ezdoctemplatedocumentGetAutocompleteV2_ETYPE_NULL = 0, ezmax_api_definition__full_ezdoctemplatedocumentGetAutocompleteV2_ETYPE_User, ezmax_api_definition__full_ezdoctemplatedocumentGetAutocompleteV2_ETYPE_Company, ezmax_api_definition__full_ezdoctemplatedocumentGetAutocompleteV2_ETYPE_Ezsignfoldertype, ezmax_api_definition__full_ezdoctemplatedocumentGetAutocompleteV2_ETYPE_CompanyUser, ezmax_api_definition__full_ezdoctemplatedocumentGetAutocompleteV2_ETYPE_CompanyEzsignfoldertype } ezmax_api_definition__full_ezdoctemplatedocumentGetAutocompleteV2_eType_e;

// Enum EFILTERACTIVE for ObjectEzdoctemplatedocumentAPI_ezdoctemplatedocumentGetAutocompleteV2
typedef enum  { ezmax_api_definition__full_ezdoctemplatedocumentGetAutocompleteV2_EFILTERACTIVE_NULL = 0, ezmax_api_definition__full_ezdoctemplatedocumentGetAutocompleteV2_EFILTERACTIVE_All, ezmax_api_definition__full_ezdoctemplatedocumentGetAutocompleteV2_EFILTERACTIVE_Active, ezmax_api_definition__full_ezdoctemplatedocumentGetAutocompleteV2_EFILTERACTIVE_Inactive } ezmax_api_definition__full_ezdoctemplatedocumentGetAutocompleteV2_eFilterActive_e;

// Enum  for ObjectEzdoctemplatedocumentAPI_ezdoctemplatedocumentGetAutocompleteV2
typedef enum  { ezmax_api_definition__full_ezdoctemplatedocumentGetAutocompleteV2__NULL = 0, ezmax_api_definition__full_ezdoctemplatedocumentGetAutocompleteV2__*, ezmax_api_definition__full_ezdoctemplatedocumentGetAutocompleteV2__en, ezmax_api_definition__full_ezdoctemplatedocumentGetAutocompleteV2__fr } ezmax_api_definition__full_ezdoctemplatedocumentGetAutocompleteV2_Accept-Language_e;

// Enum EORDERBY for ObjectEzdoctemplatedocumentAPI_ezdoctemplatedocumentGetListV1
typedef enum  { ezmax_api_definition__full_ezdoctemplatedocumentGetListV1_EORDERBY_NULL = 0, ezmax_api_definition__full_ezdoctemplatedocumentGetListV1_EORDERBY_pkiEzdoctemplatedocumentID_ASC, ezmax_api_definition__full_ezdoctemplatedocumentGetListV1_EORDERBY_pkiEzdoctemplatedocumentID_DESC, ezmax_api_definition__full_ezdoctemplatedocumentGetListV1_EORDERBY_fkiLanguageID_ASC, ezmax_api_definition__full_ezdoctemplatedocumentGetListV1_EORDERBY_fkiLanguageID_DESC, ezmax_api_definition__full_ezdoctemplatedocumentGetListV1_EORDERBY_fkiEzdoctemplatetypeID_ASC, ezmax_api_definition__full_ezdoctemplatedocumentGetListV1_EORDERBY_fkiEzdoctemplatetypeID_DESC, ezmax_api_definition__full_ezdoctemplatedocumentGetListV1_EORDERBY_fkiEzdoctemplatefieldtypecategoryID_ASC, ezmax_api_definition__full_ezdoctemplatedocumentGetListV1_EORDERBY_fkiEzdoctemplatefieldtypecategoryID_DESC, ezmax_api_definition__full_ezdoctemplatedocumentGetListV1_EORDERBY_bEzdoctemplatedocumentIsactive_ASC, ezmax_api_definition__full_ezdoctemplatedocumentGetListV1_EORDERBY_bEzdoctemplatedocumentIsactive_DESC, ezmax_api_definition__full_ezdoctemplatedocumentGetListV1_EORDERBY_sEzdoctemplatedocumentNameX_ASC, ezmax_api_definition__full_ezdoctemplatedocumentGetListV1_EORDERBY_sEzdoctemplatedocumentNameX_DESC } ezmax_api_definition__full_ezdoctemplatedocumentGetListV1_eOrderBy_e;

// Enum  for ObjectEzdoctemplatedocumentAPI_ezdoctemplatedocumentGetListV1
typedef enum  { ezmax_api_definition__full_ezdoctemplatedocumentGetListV1__NULL = 0, ezmax_api_definition__full_ezdoctemplatedocumentGetListV1__*, ezmax_api_definition__full_ezdoctemplatedocumentGetListV1__en, ezmax_api_definition__full_ezdoctemplatedocumentGetListV1__fr } ezmax_api_definition__full_ezdoctemplatedocumentGetListV1_Accept-Language_e;


// Create a new Ezdoctemplatedocument
//
// The endpoint allows to create one or many elements at once.
//
ezdoctemplatedocument_create_object_v1_response_t*
ObjectEzdoctemplatedocumentAPI_ezdoctemplatedocumentCreateObjectV1(apiClient_t *apiClient, ezdoctemplatedocument_create_object_v1_request_t *ezdoctemplatedocument_create_object_v1_request);


// Retrieve the content
//
// Using this endpoint, you can retrieve the content of an ezdoctemplatedocument.
//
void
ObjectEzdoctemplatedocumentAPI_ezdoctemplatedocumentDownloadV1(apiClient_t *apiClient, int *pkiEzdoctemplatedocumentID);


// Edit an existing Ezdoctemplatedocument
//
// 
//
ezdoctemplatedocument_edit_object_v1_response_t*
ObjectEzdoctemplatedocumentAPI_ezdoctemplatedocumentEditObjectV1(apiClient_t *apiClient, int *pkiEzdoctemplatedocumentID, ezdoctemplatedocument_edit_object_v1_request_t *ezdoctemplatedocument_edit_object_v1_request);


// Retrieve Ezdoctemplatedocuments and IDs
//
// Get the list of Ezdoctemplatedocument to be used in a dropdown or autocomplete control.
//
ezdoctemplatedocument_get_autocomplete_v2_response_t*
ObjectEzdoctemplatedocumentAPI_ezdoctemplatedocumentGetAutocompleteV2(apiClient_t *apiClient, ezmax_api_definition__full_ezdoctemplatedocumentGetAutocompleteV2_sSelector_e sSelector, ezmax_api_definition__full_ezdoctemplatedocumentGetAutocompleteV2_eType_e eType, char *fkiEzsignfoldertypeID, ezmax_api_definition__full_ezdoctemplatedocumentGetAutocompleteV2_eFilterActive_e eFilterActive, char *sQuery, header_accept_language_e Accept_Language);


// Retrieve Ezdoctemplatedocument list
//
// 
//
ezdoctemplatedocument_get_list_v1_response_t*
ObjectEzdoctemplatedocumentAPI_ezdoctemplatedocumentGetListV1(apiClient_t *apiClient, ezmax_api_definition__full_ezdoctemplatedocumentGetListV1_eOrderBy_e eOrderBy, int *iRowMax, int *iRowOffset, header_accept_language_e Accept_Language, char *sFilter);


// Retrieve an existing Ezdoctemplatedocument
//
// 
//
ezdoctemplatedocument_get_object_v2_response_t*
ObjectEzdoctemplatedocumentAPI_ezdoctemplatedocumentGetObjectV2(apiClient_t *apiClient, int *pkiEzdoctemplatedocumentID);


// Patch an existing Ezdoctemplatedocument
//
// 
//
ezdoctemplatedocument_patch_object_v1_response_t*
ObjectEzdoctemplatedocumentAPI_ezdoctemplatedocumentPatchObjectV1(apiClient_t *apiClient, int *pkiEzdoctemplatedocumentID, ezdoctemplatedocument_patch_object_v1_request_t *ezdoctemplatedocument_patch_object_v1_request);


