#include <stdlib.h>
#include <stdio.h>
#include "../include/apiClient.h"
#include "../include/list.h"
#include "../external/cJSON.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"
#include "../model/common_response_error.h"
#include "../model/ezsignbulksend_get_list_v1_response.h"
#include "../model/ezsignbulksend_get_object_v1_response.h"
#include "../model/header_accept_language.h"

// Enum EORDERBY for ObjectEzsignbulksendAPI_ezsignbulksendGetListV1
typedef enum  { ezmax_api_definition_ezsignbulksendGetListV1_EORDERBY_NULL = 0, ezmax_api_definition_ezsignbulksendGetListV1_EORDERBY_pkiEzsignbulksendID_ASC, ezmax_api_definition_ezsignbulksendGetListV1_EORDERBY_pkiEzsignbulksendID_DESC, ezmax_api_definition_ezsignbulksendGetListV1_EORDERBY_fkiEzsignfoldertypeID_ASC, ezmax_api_definition_ezsignbulksendGetListV1_EORDERBY_fkiEzsignfoldertypeID_DESC, ezmax_api_definition_ezsignbulksendGetListV1_EORDERBY_sEzsignbulksendDescription_ASC, ezmax_api_definition_ezsignbulksendGetListV1_EORDERBY_sEzsignbulksendDescription_DESC, ezmax_api_definition_ezsignbulksendGetListV1_EORDERBY_sEzsignfoldertypeNameX_ASC, ezmax_api_definition_ezsignbulksendGetListV1_EORDERBY_sEzsignfoldertypeNameX_DESC, ezmax_api_definition_ezsignbulksendGetListV1_EORDERBY_eEzsignfoldertypePrivacylevel_ASC, ezmax_api_definition_ezsignbulksendGetListV1_EORDERBY_eEzsignfoldertypePrivacylevel_DESC, ezmax_api_definition_ezsignbulksendGetListV1_EORDERBY_bEzsignbulksendIsactive_ASC, ezmax_api_definition_ezsignbulksendGetListV1_EORDERBY_bEzsignbulksendIsactive_DESC, ezmax_api_definition_ezsignbulksendGetListV1_EORDERBY_iEzsignbulksendtransmission_ASC, ezmax_api_definition_ezsignbulksendGetListV1_EORDERBY_iEzsignbulksendtransmission_DESC, ezmax_api_definition_ezsignbulksendGetListV1_EORDERBY_iEzsignfolder_ASC, ezmax_api_definition_ezsignbulksendGetListV1_EORDERBY_iEzsignfolder_DESC, ezmax_api_definition_ezsignbulksendGetListV1_EORDERBY_iEzsigndocument_ASC, ezmax_api_definition_ezsignbulksendGetListV1_EORDERBY_iEzsigndocument_DESC, ezmax_api_definition_ezsignbulksendGetListV1_EORDERBY_iEzsignsignature_ASC, ezmax_api_definition_ezsignbulksendGetListV1_EORDERBY_iEzsignsignature_DESC, ezmax_api_definition_ezsignbulksendGetListV1_EORDERBY_iEzsignsignatureSigned_ASC, ezmax_api_definition_ezsignbulksendGetListV1_EORDERBY_iEzsignsignatureSigned_DESC } ezmax_api_definition_ezsignbulksendGetListV1_eOrderBy_e;

// Enum  for ObjectEzsignbulksendAPI_ezsignbulksendGetListV1
typedef enum  { ezmax_api_definition_ezsignbulksendGetListV1__NULL = 0, ezmax_api_definition_ezsignbulksendGetListV1__*, ezmax_api_definition_ezsignbulksendGetListV1__en, ezmax_api_definition_ezsignbulksendGetListV1__fr } ezmax_api_definition_ezsignbulksendGetListV1_Accept-Language_e;


// Retrieve Ezsignbulksend list
//
// Enum values that can be filtered in query parameter *sFilter*:  | Variable | Valid values | |---|---| | eEzsignfoldertypePrivacylevel | User<br>Usergroup |
//
ezsignbulksend_get_list_v1_response_t*
ObjectEzsignbulksendAPI_ezsignbulksendGetListV1(apiClient_t *apiClient, ezmax_api_definition_ezsignbulksendGetListV1_eOrderBy_e eOrderBy , int iRowMax , int iRowOffset , header_accept_language_e Accept_Language , char * sFilter );


// Retrieve an existing Ezsignbulksend
//
// 
//
ezsignbulksend_get_object_v1_response_t*
ObjectEzsignbulksendAPI_ezsignbulksendGetObjectV1(apiClient_t *apiClient, int pkiEzsignbulksendID );


