#include <stdlib.h>
#include <stdio.h>
#include "../include/apiClient.h"
#include "../include/list.h"
#include "../external/cJSON.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"
#include "../model/glaccountcontainer_get_autocomplete_v2_response.h"
#include "../model/header_accept_language.h"

// Enum SSELECTOR for ObjectGlaccountcontainerAPI_glaccountcontainerGetAutocompleteV2
typedef enum  { ezmax_api_definition__full_glaccountcontainerGetAutocompleteV2_SSELECTOR_NULL = 0, ezmax_api_definition__full_glaccountcontainerGetAutocompleteV2_SSELECTOR_All, ezmax_api_definition__full_glaccountcontainerGetAutocompleteV2_SSELECTOR_Supply } ezmax_api_definition__full_glaccountcontainerGetAutocompleteV2_sSelector_e;

// Enum EFILTERACTIVE for ObjectGlaccountcontainerAPI_glaccountcontainerGetAutocompleteV2
typedef enum  { ezmax_api_definition__full_glaccountcontainerGetAutocompleteV2_EFILTERACTIVE_NULL = 0, ezmax_api_definition__full_glaccountcontainerGetAutocompleteV2_EFILTERACTIVE_All, ezmax_api_definition__full_glaccountcontainerGetAutocompleteV2_EFILTERACTIVE_Active, ezmax_api_definition__full_glaccountcontainerGetAutocompleteV2_EFILTERACTIVE_Inactive } ezmax_api_definition__full_glaccountcontainerGetAutocompleteV2_eFilterActive_e;

// Enum  for ObjectGlaccountcontainerAPI_glaccountcontainerGetAutocompleteV2
typedef enum  { ezmax_api_definition__full_glaccountcontainerGetAutocompleteV2__NULL = 0, ezmax_api_definition__full_glaccountcontainerGetAutocompleteV2__*, ezmax_api_definition__full_glaccountcontainerGetAutocompleteV2__en, ezmax_api_definition__full_glaccountcontainerGetAutocompleteV2__fr } ezmax_api_definition__full_glaccountcontainerGetAutocompleteV2_Accept-Language_e;


// Retrieve Glaccountcontainers and IDs
//
// Get the list of Glaccountcontainer to be used in a dropdown or autocomplete control.
//
glaccountcontainer_get_autocomplete_v2_response_t*
ObjectGlaccountcontainerAPI_glaccountcontainerGetAutocompleteV2(apiClient_t *apiClient, ezmax_api_definition__full_glaccountcontainerGetAutocompleteV2_sSelector_e sSelector, ezmax_api_definition__full_glaccountcontainerGetAutocompleteV2_eFilterActive_e eFilterActive, char *sQuery, header_accept_language_e Accept_Language);


