#include <stdlib.h>
#include <stdio.h>
#include "../include/apiClient.h"
#include "../include/list.h"
#include "../external/cJSON.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"
#include "../model/common_response_error.h"
#include "../model/disclosure_batch_download_v1_request.h"
#include "../model/disclosure_get_attachments_v1_response.h"
#include "../model/disclosure_get_communication_count_v1_response.h"
#include "../model/disclosure_get_communication_list_v1_response.h"
#include "../model/disclosure_get_communicationrecipients_v1_response.h"
#include "../model/disclosure_get_communicationsenders_v1_response.h"
#include "../model/disclosure_get_list_v1_response.h"
#include "../model/disclosure_import_into_edm_v1_request.h"
#include "../model/disclosure_import_into_edm_v1_response.h"
#include "../model/header_accept_language.h"

// Enum EORDERBY for ObjectDisclosureAPI_disclosureGetListV1
typedef enum  { ezmax_api_definition__full_disclosureGetListV1_EORDERBY_NULL = 0, ezmax_api_definition__full_disclosureGetListV1_EORDERBY_pkiDisclosureID_ASC, ezmax_api_definition__full_disclosureGetListV1_EORDERBY_pkiDisclosureID_DESC, ezmax_api_definition__full_disclosureGetListV1_EORDERBY_fkiAgentID_ASC, ezmax_api_definition__full_disclosureGetListV1_EORDERBY_fkiAgentID_DESC, ezmax_api_definition__full_disclosureGetListV1_EORDERBY_fkiBrokerID_ASC, ezmax_api_definition__full_disclosureGetListV1_EORDERBY_fkiBrokerID_DESC, ezmax_api_definition__full_disclosureGetListV1_EORDERBY_eDisclosureInteresttype_ASC, ezmax_api_definition__full_disclosureGetListV1_EORDERBY_eDisclosureInteresttype_DESC, ezmax_api_definition__full_disclosureGetListV1_EORDERBY_sDisclosureRelation_ASC, ezmax_api_definition__full_disclosureGetListV1_EORDERBY_sDisclosureRelation_DESC, ezmax_api_definition__full_disclosureGetListV1_EORDERBY_dtDisclosureRedactiondate_ASC, ezmax_api_definition__full_disclosureGetListV1_EORDERBY_dtDisclosureRedactiondate_DESC, ezmax_api_definition__full_disclosureGetListV1_EORDERBY_dtDisclosureAcceptationdate_ASC, ezmax_api_definition__full_disclosureGetListV1_EORDERBY_dtDisclosureAcceptationdate_DESC, ezmax_api_definition__full_disclosureGetListV1_EORDERBY_dtDisclosureReceptiondate_ASC, ezmax_api_definition__full_disclosureGetListV1_EORDERBY_dtDisclosureReceptiondate_DESC, ezmax_api_definition__full_disclosureGetListV1_EORDERBY_bDisclosureIsactive_ASC, ezmax_api_definition__full_disclosureGetListV1_EORDERBY_bDisclosureIsactive_DESC, ezmax_api_definition__full_disclosureGetListV1_EORDERBY_sDisclosureNumber_ASC, ezmax_api_definition__full_disclosureGetListV1_EORDERBY_sDisclosureNumber_DESC, ezmax_api_definition__full_disclosureGetListV1_EORDERBY_sContactFirstname_ASC, ezmax_api_definition__full_disclosureGetListV1_EORDERBY_sContactFirstname_DESC, ezmax_api_definition__full_disclosureGetListV1_EORDERBY_sContactLastname_ASC, ezmax_api_definition__full_disclosureGetListV1_EORDERBY_sContactLastname_DESC, ezmax_api_definition__full_disclosureGetListV1_EORDERBY_sBrokerName_ASC, ezmax_api_definition__full_disclosureGetListV1_EORDERBY_sBrokerName_DESC } ezmax_api_definition__full_disclosureGetListV1_eOrderBy_e;

// Enum  for ObjectDisclosureAPI_disclosureGetListV1
typedef enum  { ezmax_api_definition__full_disclosureGetListV1__NULL = 0, ezmax_api_definition__full_disclosureGetListV1__*, ezmax_api_definition__full_disclosureGetListV1__en, ezmax_api_definition__full_disclosureGetListV1__fr } ezmax_api_definition__full_disclosureGetListV1_Accept-Language_e;


// Download multiples attachments from a Disclosure
//
binary_t*
ObjectDisclosureAPI_disclosureBatchDownloadV1(apiClient_t *apiClient, int *pkiDisclosureID, disclosure_batch_download_v1_request_t *disclosure_batch_download_v1_request);


// Retrieve Disclosure's attachments
//
disclosure_get_attachments_v1_response_t*
ObjectDisclosureAPI_disclosureGetAttachmentsV1(apiClient_t *apiClient, int *pkiDisclosureID);


// Retrieve Communication count
//
disclosure_get_communication_count_v1_response_t*
ObjectDisclosureAPI_disclosureGetCommunicationCountV1(apiClient_t *apiClient, int *pkiDisclosureID);


// Retrieve Communication list
//
disclosure_get_communication_list_v1_response_t*
ObjectDisclosureAPI_disclosureGetCommunicationListV1(apiClient_t *apiClient, int *pkiDisclosureID);


// Retrieve Communication recipients
//
disclosure_get_communicationrecipients_v1_response_t*
ObjectDisclosureAPI_disclosureGetCommunicationrecipientsV1(apiClient_t *apiClient, int *pkiDisclosureID);


// Retrieve Communication senders
//
disclosure_get_communicationsenders_v1_response_t*
ObjectDisclosureAPI_disclosureGetCommunicationsendersV1(apiClient_t *apiClient, int *pkiDisclosureID);


// Retrieve Disclosure list
//
// Enum values that can be filtered in query parameter *sFilter*:  | Variable | Valid values | |---|---| | eDisclosureInteresttype | Direct<br>Indirect |
//
disclosure_get_list_v1_response_t*
ObjectDisclosureAPI_disclosureGetListV1(apiClient_t *apiClient, ezmax_api_definition__full_disclosureGetListV1_eOrderBy_e eOrderBy, int *iRowMax, int *iRowOffset, header_accept_language_e Accept_Language, char *sFilter);


// Import attachments into the Disclosure
//
disclosure_import_into_edm_v1_response_t*
ObjectDisclosureAPI_disclosureImportIntoEDMV1(apiClient_t *apiClient, int *pkiDisclosureID, disclosure_import_into_edm_v1_request_t *disclosure_import_into_edm_v1_request);


